### ISSUE TITLE
Unaccounted lost time in Helix workitem processing

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/arcade#10168]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

I was looking at logs from job https://helix.dot.net/api/jobs/fb0d553f-40cc-48b8-8ff2-5e7ca6762430/workitems?api-version=2019-06-17 that ran on the ARM64 queue.

I found it surprising that each of these workitems took minutes to finish, even though I know most of these tests complete in seconds.

We're losing machine time somewhere I couldn't pinpoint where from the logs:

The console log for the System.Collections.Tests workitem has this:

```
Console log: 'System.Collections.Tests' from job fb0d553f-40cc-48b8-8ff2-5e7ca6762430 workitem 35fcc6c3-ed55-4c7f-9b23-953d667f7502 (windows.10.arm64.open) executed on machine DDARM64S-033

C:\h\w\B668097B\w\B5910958\e>taskkill.exe /f /im corerun.exe 
ERROR: The process "corerun.exe" not found.

C:\h\w\B668097B\w\B5910958\e>call RunTests.cmd --runtime-path C:\h\w\B668097B\p 
----- start Wed 07/27/2022  2:41:39.11 ===============  To repro directly: ===================================================== 
pushd C:\h\w\B668097B\w\B5910958\e\
System.Collections.Tests.exe -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -xml testResults.xml 
popd
===========================================================================================================

C:\h\w\B668097B\w\B5910958\e>System.Collections.Tests.exe -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -xml testResults.xml  

/* Skipping for brevity */

Finished System.Collections.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

Tests run: 32511, Errors: 0, Failures: 0, Skipped: 109. Time: 5.1977535s
----- end Wed 07/27/2022  2:41:48.11 ----- exit code 0 ----------------------------------------------------------
2022-07-27T09:41:50.817Z	INFO   	run.py	run(48)	main	Beginning reading of test results.
2022-07-27T09:41:50.833Z	INFO   	run.py	__init__(42)	read_results	Searching 'C:\h\w\B668097B\w\B5910958\e' for test results files
2022-07-27T09:41:50.833Z	INFO   	run.py	__init__(48)	read_results	Found results file C:\h\w\B668097B\w\B5910958\e\testResults.xml with format xunit
2022-07-27T09:41:53.301Z	INFO   	run.py	__init__(42)	read_results	Searching 'C:\h\w\B668097B\w\B5910958\uploads' for test results files
2022-07-27T09:41:53.301Z	INFO   	run.py	packing_test_reporter(30)	report_results	Packing 32511 test reports to 'C:\h\w\B668097B\w\B5910958\e\__test_report.json'
2022-07-27T09:41:53.848Z	INFO   	run.py	packing_test_reporter(33)	report_results	Packed 12542843 bytes
Did not find dumps, skipping dump docs generation.
```

So we know the "useful work" finished in less than 20 seconds. Of course I expect some overhead due to downloading and uploading, but it doesn't explain the `"Queued":"2022-07-27T07:27:47.745+00:00","Started":"2022-07-27T09:41:09.609+00:00","Finished":"2022-07-27T09:47:58.545+00:00","Delay":"02:13:21.8640000","Duration":"00:06:48.9360000"`. Where did we spend the other 6 minutes?

Digging into the `run_client.py` log, I see:

```
2022-07-27T09:41:38.864Z	INFO   	executor(833)	_execute_command	running %HELIX_CORRELATION_PAYLOAD%\scripts\0f507811259646bf86fd7d51a4ddb483\execute.cmd in C:\h\w\B668097B\w\B5910958\e max 2700 seconds
2022-07-27T09:41:54.411Z	INFO   	job(38)	wait	Work item's process exited normally.
2022-07-27T09:42:41.259Z	INFO   	interval(82)	event	Invoke callback for timer, arguments: None
2022-07-27T09:42:41.259Z	INFO   	servicebusrepository(106)	renew_workitem_lock	Renewing lock for ServiceBus item MessageId 'ed43292dcc4840348b0966a2025fd012' with url 'https://nethelix.servicebus.windows.net/windows.10.arm64.open/messages/3732380/d8ac9553-6b65-4f19-b839-66ab560b90d4'
2022-07-27T09:42:41.406Z	INFO   	saferequests(87)	request_with_retry	Response complete with status code '200'
2022-07-27T09:42:41.406Z	INFO   	servicebusrepository(116)	renew_workitem_lock	Renewed work item lock. Status Code: 200
2022-07-27T09:42:41.406Z	INFO   	interval(54)	setup_timer	Timer set to 90 seconds
2022-07-27T09:44:11.418Z	INFO   	interval(82)	event	Invoke callback for timer, arguments: None
2022-07-27T09:44:11.418Z	INFO   	servicebusrepository(106)	renew_workitem_lock	Renewing lock for ServiceBus item MessageId 'ed43292dcc4840348b0966a2025fd012' with url 'https://nethelix.servicebus.windows.net/windows.10.arm64.open/messages/3732380/d8ac9553-6b65-4f19-b839-66ab560b90d4'
2022-07-27T09:44:11.559Z	INFO   	saferequests(87)	request_with_retry	Response complete with status code '200'
2022-07-27T09:44:11.559Z	INFO   	servicebusrepository(116)	renew_workitem_lock	Renewed work item lock. Status Code: 200
2022-07-27T09:44:11.559Z	INFO   	interval(54)	setup_timer	Timer set to 90 seconds
2022-07-27T09:45:28.108Z	INFO   	interval(70)	cancel_abort_after	Cancel abort_after for timer
2022-07-27T09:45:28.108Z	INFO   	interval(67)	set_abort_after_timer	Set the timer's abort_after to 660 seconds from now: abort_after = 2022-07-27 02:56:28.108918
2022-07-27T09:45:28.108Z	INFO   	executor(759)	_dump_file_upload	No dump files to upload.
2022-07-27T09:45:28.108Z	INFO   	interval(67)	set_abort_after_timer	Set the timer's abort_after to 180 seconds from now: abort_after = 2022-07-27 02:48:28.108918
2022-07-27T09:45:28.108Z	INFO   	executor(959)	_upload_files	Allowing maximum 0.0 seconds to upload 0 bytes of files.
2022-07-27T09:45:28.108Z	INFO   	interval(67)	set_abort_after_timer	Set the timer's abort_after to 60.0 seconds from now: abort_after = 2022-07-27 02:46:28.108918
2022-07-27T09:45:28.108Z	INFO   	executor(877)	_execute_command	Finished _execute_command, exit code: 0
2022-07-27T09:45:28.108Z	INFO   	executor(920)	_upload_single_file	Uploading the file console.6425316b.log
```

So we see that the workitem exited at 09:41:54 but it looks like we spent three and a half minutes until 09:45:28 doing nothing?

Then we spend another 2 minutes publishing the results:

```
2022-07-27T09:45:53.168Z	INFO   	azure_devops_result_publisher(153)	_process	uploaded 997 results
2022-07-27T09:46:11.535Z	INFO   	azure_devops_result_publisher(153)	_process	uploaded 1962 results
2022-07-27T09:46:38.378Z	INFO   	azure_devops_result_publisher(153)	_process	uploaded 2959 results
2022-07-27T09:47:05.906Z	INFO   	azure_devops_result_publisher(153)	_process	uploaded 3957 results
2022-07-27T09:47:12.438Z	INFO   	interval(82)	event	Invoke callback for timer, arguments: None
2022-07-27T09:47:12.516Z	INFO   	servicebusrepository(106)	renew_workitem_lock	Renewing lock for ServiceBus item MessageId 'ed43292dcc4840348b0966a2025fd012' with url 'https://nethelix.servicebus.windows.net/windows.10.arm64.open/messages/3732380/d8ac9553-6b65-4f19-b839-66ab560b90d4'
2022-07-27T09:47:13.156Z	INFO   	saferequests(87)	request_with_retry	Response complete with status code '200'
2022-07-27T09:47:13.344Z	INFO   	servicebusrepository(116)	renew_workitem_lock	Renewed work item lock. Status Code: 200
2022-07-27T09:47:13.438Z	INFO   	interval(54)	setup_timer	Timer set to 90 seconds
2022-07-27T09:47:27.007Z	INFO   	azure_devops_result_publisher(153)	_process	uploaded 4860 results
2022-07-27T09:47:44.195Z	INFO   	azure_devops_result_publisher(153)	_process	uploaded 5600 results
```

It feels like we should be able to do something to make this more efficient.

**Comment by MattGal** [comment]
This is an interesting find.  I believe this all relates to how we run python on ARM64 windows. Unfortunately, until a native ARM64 version of Python exists (and likely, some of our dependencies publish compatible updates) this will remain a problem for ARM64 windows machines.  Note that _all_ x86 processes on ARM64 windows machines are human-visibly slower in general, and this is the only way to run python on this platform today.

Picking apart one piece of this slowness, from a [recent AMD version of this same workitem](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-73005-merge-6eebddb3f7734e7daf/System.Collections.Tests/c1d670f2-15a1-43af-9c61-b2fa5eef8763.log?helixlogtype=result)

```
2022-07-28T17:02:21.048Z	INFO   	job(38)	wait	Work item's process exited normally.
...
2022-07-28T17:02:21.064Z	INFO   	executor(897)	_execute_command	Finished _execute_command, exit code: 0
```

The delta between when the work item exits and the executor logs that this happened is a scorching 0.016 seconds, pretty darn fast.

The same time delta, as you noticed, in ARM64 windows is a whopping 3:53.

```
2022-07-28T11:43:23.685Z	INFO   	job(38)	wait	Work item's process exited normally.
...
2022-07-28T11:47:14.239Z	INFO   	executor(897)	_execute_command	Finished _execute_command, exit code: 0
```

Note identical python code is used for both logs here.   I reviewed what happens between these lines, and a quick summary:
-	Executor calls Job.wait, which logs the first line; the process exited without having to be told to.
  - Inside wait():
    - Timer object is nulled out
    - Job checks if the work item timed out and was killed; it was not so no action taken
    - kill_any_leaked_workitem_processes() is called; this walks every process on the machine and is clearly fast on AMD64, but due to the abstraction layer (x86 emulation is often very noticeably slow) this process seems to take a VERY long time.
  - Executor nulls out a timer object (nigh instantaneous)
  - Executor checks exit code and decides not to sleep at all since it’s 0 (would otherwise wait for some dumps)
  - Executor checks for whether dump files exist (they don’t) so it does nothing.
  - Executor uploads log file (in your case, almost instant, 14 KB file)
  - Executor logs the 2nd line.
   
The only interesting work that actually happens at all here is the process walk, and an x86 process running on an emulation layer walking the ARM, ARM64, and x86 processes of a machine is just slow. 

It would be pretty easy to introduce a workaround here to skip kill_any_leaked_workitem_processes() if we are running on an ARM64 windows machine, but this function more or less exists to serve on-premises machines since they live much, much longer than our ephemeral AMD64 VMs and processes can and do leak.

Eventually we will have both ARM64 Azure capacity (so the machines become ephemeral) and we’ll have native-Windows-ARM64 python (rumors say in 3.11) and this problem won’t exist.  Until then, I don’t think this can be made better without removing the leaked work item check.

**Comment by MichalStrehovsky** [comment]
Thank you for the analysis! This is very puzzling.

@marek-safar do you know what's the status of ARM64 Windows Python? This also looks like something that might be worth investigating by the Windows team too - an action that takes less than a second natively takes minutes under emulation on ARM64. We're running into something pathological. Marek - do you have any contacts for that?

**Comment by vitek-karas** [comment]
FYI @pragmanomos - who might have some insights into this

**Comment by marek-safar** [comment]
@pragmanomos please try to help here.

**Comment by pragmanomos** [comment]
Hello, you can find experimental pre-release builds of WoARM64 Python [here](https://www.nuget.org/packages/pythonarm64). Official support will be introduced starting with 3.11 (see [here](https://www.linaro.org/windows-on-arm/python/)).

**Comment by MattGal** [comment]
Doing a few experiments, I realized this doesn't _always_ happen.  From the separate email thread, I think we'll hold off on trying ARM64 python until it's ready to go (experimentally trying, the one above can't install our dependency list) but I will convert the machines in the staging environment over to AMD64 manually and see if this poses any problems; if it doesn't, we might as well move all our Windows machines over to 64-bit python3 anyways.

**Comment by MattGal** [comment]
I realized that this doesn't seem to happen on the closed queue (see work item 5303d8f1-e9a7-4096-bf7b-64941d9952ad for an example of near identical jobs not hitting it; nor did staging).    One interesting variance between the machines with the slowdown and not is that the ones in the .open queue (the slow ones) are running Windows 10 20H1, which is end of life anyways.

I filed https://portal.microsofticm.com/imp/v3/incidents/details/324098710/home to track reimaging them to a supported OS; if this solves the problem, great (it certainly seems to be correlated with this taking less time).  Putting this issue into tracking while that is ongoing.

**Comment by MattGal** [comment]
I spent some time checking out the reimaged machines today.  They definitely have newer Windows on them but hit the same symptom.

However, given that the version of Windows 10 these machines have still cannot run AMD64 executables, and the ARM64 version of Windows python3 is still not compatible with the libraries the helix client we need, I don't think there's anything we can do beyond updating the OS to a non-expired version; we do not want to have the process-walking behavior change for a specific queue, especially one which needs such functionality.

**Comment by jkotas** [comment]
@MattGal Do we have an issue somewhere that tracks fixing the python3 compatibility issues and updating the Windows Helix machines to use them?

There is more pressure coming from hardware budgets and this inefficiency should not be a rocket science to fix. I do not think this should be closed.

**Comment by Chrisboh** [comment]
@jkotas the dependencies in question are external dependencies that we do not currently own.  Most dependencies with native components don't have natively compiled versions available (i.e. Requests or Cryptography) and until Python for ARM64 Windows reaches RTM I doubt there is much we can do at this time.

**Comment by jkotas** [comment]
https://www.python.org/downloads/windows/ has Python Windows Arm64 RC2. Does the RC2 have everything we need? If not, is somebody on the Windows Arm64 ecosystem team working on filling the missing parts?

**Comment by MattGal** [comment]
The RC2 does not have everything we need.  I don't think it's the Windows ARM64 team's problem though, rather lots of the packages we depend on (in this case, 'cryptography') don't pre-provide ARM64 binaries.

This leads to errors like the below when trying to install / update them via pip.

``` 
  Downloading cryptography-38.0.1.tar.gz (599 kB)
     ---------------------------------------- 599.4/599.4 kB 19.0 MB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      Collecting setuptools!=60.9.0,>=40.6.0
        Using cached setuptools-65.3.0-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting cffi>=1.12
        Using cached cffi-1.15.1.tar.gz (508 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'error'
        error: subprocess-exited-with-error

        python setup.py egg_info did not run successfully.
        exit code: 1

        [24 lines of output]
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "D:\Users\dotnet-bot\AppData\Local\Temp\pip-install-6oj8hxxn\cffi_dbfe551166d940f59c09a9e2527a841e\setup.py", line 126, in <module>
            if sys.platform == "win32" and uses_msvc():
                                           ^^^^^^^^^^^
          File "D:\Users\dotnet-bot\AppData\Local\Temp\pip-install-6oj8hxxn\cffi_dbfe551166d940f59c09a9e2527a841e\setup.py", line 105, in uses_msvc
            return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "D:\python3-arm64\Lib\site-packages\setuptools\_distutils\command\config.py", line 223, in try_compile
            self._compile(body, headers, include_dirs, lang)
          File "D:\python3-arm64\Lib\site-packages\setuptools\_distutils\command\config.py", line 128, in _compile
            self.compiler.compile([src], include_dirs=include_dirs)
          File "D:\python3-arm64\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 361, in compile
            self.initialize()
          File "D:\python3-arm64\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 241, in initialize
            vc_env = _get_vc_env(plat_spec)
                     ^^^^^^^^^^^^^^^^^^^^^^
          File "D:\python3-arm64\Lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
            return _msvc14_get_vc_env(plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "D:\python3-arm64\Lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
            raise distutils.errors.DistutilsPlatformError(
        distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
```
We hit this with lots of the dependencies from https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines?path=/resources/helix-scripts/runtime_python_requirements.txt.  Until 100% of these succeed with a native ARM64 python 3 there's no easy way to run helix clients on them.

**Comment by jkotas** [comment]
> I don't think it's the Windows ARM64 team's problem though

It is Windows Arm64 ecosystem team problem that is led by @pragmanomos . Have you talk to them about this?

**Comment by MattGal** [comment]
> > I don't think it's the Windows ARM64 team's problem though
> 
> It is Windows Arm64 ecosystem team problem. The team is led by @pragmanomos . Have you talk to them about this?

We've been in touch in the past, yes, but given the Windows ARM64 support is not fully RTMed yet and the problems installing our dependencies as listed above (lots of our other dependencies depend on the cryptography library) it just hasn't been a high priority for our team as the helix work items still function and the queue is not backed up beyond usability.

If @pragmanomos gives us some kind of ETA when this might work (I tried this morning) I will make a note to check back at that point.

**Comment by vladimir-aubrecht** [comment]
@MattGal I'll let @pragmanomos get back to you on ETA topic (he is coming on vacation coming back on 15 September 2022), but in the meantime I can dig into those incompatible dependencies.

Did you already analyse which of those dependencies you shared are incompatible and which are compatible? I'll create work items on our side to investigate on status or create the fix.

**Comment by MattGal** [comment]
This work item was about an investigation as to why we lost some time running work items in a specific environment.  This has been root-caused and understood, and we have explored as far as we can for now.  

@vladimir-aubrecht I am happy to follow up offline any time we think that progress has been made here (hit me up on Teams or email ideally)  Unfortunately, since so many of our dependencies depend on the pypi **cryptography** library, it's very hard to make a list of every incompatible package for you;  corollary being, getting that one right will go a long way!  Suffice it to say that until I can install a compatible version of this package it's not worth exploring the rest.   Our users are not blocked and this is not a "First responders" type issue.   

@jkotas : If you have concerns, please contact myself and CC @Chrisboh  before reactivating this issue.

**Comment by MichalStrehovsky** [comment]
@vladimir-aubrecht @pragmanomos Do you have any contacts on the Windows team who could look into why emulation performs so bad? If I was in charge of the x86 on ARM64 emulation, I would definitely want to investigate. Some slowdown is expected, but this is something that takes less than a second natively taking minutes under emulation.

**Comment by vladimir-aubrecht** [comment]
We definitely have contact! 😊 It should be handled by Mixed-Architecture Computing team (macdev@microsoft.com). I created an email thread with them, included you and added also @pragmanomos for awareness.

**Comment by zooba** [comment]
Just had a quick skim, and you may want to try running under x64 emulation rather than x86. I've noticed when testing Python under emulation that there are a few bugs that don't exist under x64, and at least one related to process termination (I forget the specifics now, sorry).

**Comment by MattGal** [comment]
> Just had a quick skim, and you may want to try running under x64 emulation rather than x86. I've noticed when testing Python under emulation that there are a few bugs that don't exist under x64, and at least one related to process termination (I forget the specifics now, sorry).

That was the first thing I tried, and it'd be very cheap to do, but none of our Windows 10 Enterprise ARM64 10.0.19044 (21H2) builds of seem to run amd64 exes.  I'm happy to explore that route if you can help me understand what I may be doing wrong.

**Comment by zooba** [comment]
Unfortunately, I have no ideas what you may be doing wrong - launching amd64 binaries seems all too easy to me.

Possibly Windows 11 (10.0.22200) was the first to bring x64 emulation? I've only ever tried it with private OS builds set up by other people, and haven't been keeping close track of which versions they were.
