### ISSUE TITLE
`SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC` when downloading .NET SDK for work items

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#10351]
Originally reported in https://github.com/dotnet/xharness/issues/935 but not related to XHarness, we fail to download .NET 7.0 preview 5 SDK for work item:
```
2022-08-09T10:54:17.206Z	INFO   	executor(425)	_download_to	requesting https://dotnetbuilds.blob.core.windows.net/public/Sdk/7.0.100-preview.5.22307.18/dotnet-sdk-7.0.100-preview.5.22307.18-osx-x64.tar.gz
2022-08-09T10:54:17.372Z	INFO   	saferequests(87)	request_with_retry	Response complete with status code '200'
2022-08-09T10:54:17.372Z	INFO   	executor(431)	_download_request	response received. Status: 200 Elapsed time: 0:00:00.163530
2022-08-09T10:54:18.203Z	INFO   	executor(451)	_download_request	Caught Hang: <class 'ssl.SSLError'>
2022-08-09T10:54:18.203Z	INFO   	executor(452)	_download_request	Downloaded: 12582912   Total: 186069223
2022-08-09T10:54:18.204Z	INFO   	executor(473)	_download_to	Payload Download Interruption Data: Type: <class 'ssl.SSLError'>, Object: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2622), Trace: <traceback object at 0x7fd7b0aecc00>
2022-08-09T10:54:18.205Z	INFO   	executor(332)	_download_and_unpack	Connection Interruption: Adding 2 retries.
2022-08-09T10:54:18.205Z	INFO   	executor(915)	_delete_if_exists	Deleting file: /tmp/helix/working/A8BA09CF/w/dotnet-sdk-7.0.100-preview.5.22307.18-osx-x64.tar.gz.partial
2022-08-09T10:54:18.206Z	ERROR  	executor(338)	_download_and_unpack	Exception "[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2622)" seen downloading: 
Traceback (most recent call last):
  File "/private/etc/helix/scripts/helix/executor.py", line 308, in _download_and_unpack
    self._download_to(uri, partial_file_path)
  File "/private/etc/helix/scripts/helix/executor.py", line 476, in _download_to
    raise exc_obj
  File "/private/etc/helix/scripts/helix/executor.py", line 439, in _download_request
    for chunk in response.iter_content(chunk_size=1024): # hangs if there is a download cutoff
  File "/private/etc/helix/scripts/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/private/etc/helix/scripts/urllib3/response.py", line 496, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/private/etc/helix/scripts/urllib3/response.py", line 444, in read
    data = self._fp.read(amt)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 458, in read
    n = self.readinto(b)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2622)
```

Full logs: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-603569b1ff0c4b3c81/System.Runtime.ReflectionInvokeEmit.Tests.Attempt.3/bfe8f718-556c-4a3f-a29a-7f1e30cb78c4.log?%3Fhelixlogtype%3Dresult

More examples in https://github.com/dotnet/xharness/issues/935

**Comment by MattGal** [comment]
Seems like a transient service outage with Azure Storage and the existing retry logic made three attempts at it before quitting; what's the goal of opening an FR issue for this, would you like to change retries or ?

**Comment by MattGal** [comment]
OK I was wrong, it seems like dci-mac-build-349 is messed up, I offlined it and am creating an IcM ticket.

**Comment by MattGal** [comment]
https://portal.microsofticm.com/imp/v3/incidents/details/326656578/home

**Comment by MattGal** [comment]
Update:  still in progress, having some challenges around reimaging.

**Comment by MattGal** [comment]
As the system in question is due for decommissioning or full reimaging, I am closing this issue.
