### ISSUE TITLE
[Maestro] NullReferenceException when performing subscription update for corefx

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#1039]
Corefx subscriptions aren't updating, appears to be an exception in DarcLib

**Comment by mmitche** [comment]
Stack:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.DarcLib.Remote.CommitFilesForPullRequestAsync(String repoUri, String branch, String assetsProducedInCommit, IEnumerable`1 itemsToUpdate, String pullRequestBaseBranch) in E:\eng\dotnet\arcade\src\Microsoft.DotNet.Darc\src\DarcLib\Actions\Remote.cs:line 223
   at Microsoft.DotNet.DarcLib.Remote.CreatePullRequestAsync(String repoUri, String branch, String assetsProducedInCommit, IEnumerable`1 assets, String pullRequestBaseBranch, String pullRequestTitle, String pullRequestDescription) in E:\eng\dotnet\arcade\src\Microsoft.DotNet.Darc\src\DarcLib\Actions\Remote.cs:line 93
   at SubscriptionActorService.SubscriptionActor.UpdateAsyncImpl(Int32 buildId) in E:\eng\dotnet\arcade\src\Maestro\SubscriptionActorService\SubscriptionActor.cs:line 244
   at SubscriptionActorService.SubscriptionActor.RunAction(Func`1 run, String method, String messageFormat, Object[] arguments) in E:\eng\dotnet\arcade\src\Maestro\SubscriptionActorService\SubscriptionActor.cs:line 194
```

**Comment by mmitche** [comment]
FYI @alexperovich @jcagme I'm taking a look

**Comment by mmitche** [comment]
https://github.com/dotnet/arcade/pull/1043
