### ISSUE TITLE
VssUnauthorizedException in Data Migration processor in Helix staging environment. 

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#10417]
I'm putting the FR label on this to do a quick investigation today if I can, @alexperovich FYI in case this relates to your tweaks for the new org.

See this query.... we're hitting this exception trying to migrate jobs in staging.  it _may_ just be a broken secret?
```
Unhandled exception Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not authorized to access https://dev.azure.com.
at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
at Microsoft.Internal.Helix.DataMigration.DataMigrationMessageHandler.ProcessAzurePipelinesTestResults(JobFinishedNotification notification, AzurePipelinesTestRunInfo testRunInfo, List`1 allEvents, CancellationToken cancellationToken) in S:\src\ServiceFabric\Helix\DataMigration\DataMigrationMessageHandler.cs:line 366
at Microsoft.Internal.Helix.DataMigration.DataMigrationMessageHandler.HandleJobFinished(JobFinishedNotification notification, CancellationToken cancellationToken) in S:\src\ServiceFabric\Helix\DataMigration\DataMigrationMessageHandler.cs:line 331
at Microsoft.Internal.Helix.DataMigration.DataMigrationMessageHandler.HandleMessageAsync(IQueuedWork message, Boolean isLastAttempt, CancellationToken cancellationToken) in S:\src\ServiceFabric\Helix\DataMigration\DataMigrationMessageHandler.cs:line 101

```

https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2Fcab65fc3-d077-467d-931f-3932eabf36d3%2FresourceGroups%2Fdotnet-eng-int-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng-int/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA22QzQrCMAyA73uK4EkPla7bdP7eB76DZEvUgutGWxXFh7dTcEMMgRDCR%252FLlzB6atiAHG%252FAWK3bRE24ntgxe1%252Bw81i1sgdBz14%252BVVErIXMQKpFy%252Bc5rLVIaYABoaUOs%252FVNJT8hOT777AOTwyVI3xqI2DEWd5QpwpQWlyEOmcUeSLeSoyQlSHslQzqUaBd5e6RqsfDOU92LBFrxuzL2gV%252FTgNh6ANjN%252Fu3Q2NJbYd3wsQuwq%252BqOMrW%252B3vu1DP4SXxC%252F4HGq87AQAA

**Comment by MattGal** [comment]
Created https://github.com/dotnet/arcade/pull/10419 to repro then hopefully un-repro if a secret has been invalidated.

**Comment by MattGal** [comment]
Hrm.  as this worked just fine for now, I am going to close it as only experimental runs hit it anyways.
