### ISSUE TITLE
[Release/6.0] Arcade-validation official build failing

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#10769]
- [X] This issue is blocking 
This blocks arcade promotion for the .net 6 eng channel
- [ ] This issue is causing unreasonable pain

The builds for the release/6.0 branch are failing because they seem to be missing .NET 6 to be able to run darc as seen in https://dev.azure.com/dnceng/internal/_build/results?buildId=1986351&view=logs&j=56ebfe15-69d8-5dd1-65e4-c65998c8d8a6&t=89bcf844-d360-55ae-2e4e-177de977d691

```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '6.0.0' was not found.
  - The following frameworks were found:
      2.1.30 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.22 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.14 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=win10-x64

```

I think we should move to the same build images we use in the main branch, as they don't have this problem.

**Comment by riarenas** [comment]
I have an experimental build of this change here: 
https://dev.azure.com/dnceng/internal/_build/results?buildId=1986861&view=results

**Comment by riarenas** [comment]
The resulting build after merging the PR was able to get past the previous error, but a new one popped up in the validate-publishing leg: https://dev.azure.com/dnceng/internal/_build/results?buildId=1987332&view=logs&j=bad36439-c803-59a2-8c30-53d67b909383&t=0311db42-8847-5041-3af3-5c8f503b3778

```
Adding build '148229' to channel 'General Testing'
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      A '400 - BadRequest' status was returned for a HTTP request. We'll set the retries amount to 0. Error details: {"$id":"1","innerException":null,"message":"Unexpected parameter 'UseServicingBuildPool'","typeName":"Microsoft.Azure.Pipelines.WebApi.PipelineValidationException, Microsoft.Azure.Pipelines.WebApi","typeKey":"PipelineValidationException","errorCode":0,"eventId":3000}
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      There was an error executing method 'POST' against URI '_apis/pipelines/750/runs' after 15 attempts. Exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs:line 96
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Error: Failed to assign build '148229' to channel 'General Testing'.
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs:line 96
         at Microsoft.DotNet.DarcLib.AzureDevOpsClient.ExecuteAzureDevOpsAPIRequestAsync(HttpMethod method, String accountName, String projectName, String requestPath, ILogger logger, String body, String versionOverride, Boolean logFailure, String baseAddressSubpath, Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs:line 875
         at Microsoft.DotNet.DarcLib.AzureDevOpsClient.StartNewBuildAsync(String accountName, String projectName, Int32 azdoDefinitionId, String sourceBranch, String sourceVersion, Dictionary`2 queueTimeVariables, Dictionary`2 templateParameters) in /_/src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs:line 1225
         at Microsoft.DotNet.Darc.Operations.AddBuildToChannelOperation.PromoteBuildAsync(Build build, List`1 targetChannels, IRemote remote) in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs:line 280
         at Microsoft.DotNet.Darc.Operations.AddBuildToChannelOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs:line 154
Problems using Darc to promote build '148229' to channel 'General Testing'. Stopping execution...
Cleaning up val/arcade-6.0.0-beta.22457.3 branch.
```

@dotnet/dnceng I'm adding this to FR and removing my assignment as the build is still blocked, and this require some more investigation that I can't perform right now. I should be able to help later today if it's still blocked. 

Also tagging @MattGal in case he has ideas as this is refering to the new parameter. 
> Unexpected parameter 'UseServicingBuildPool

My initial guess is that we're using the wrong source-branch when we call the add-build-to-channel command here: https://github.com/dotnet/arcade-validation/blob/release/6.0/eng/validation/test-publishing.ps1, and that source-branch does not have the new parameter in the promotion pipeline's yaml?

**Comment by MattGal** [comment]
I can take an initial look here.  I added that parameter but my understanding was that all v3 publishing occurred against the main branch of arcade so I didn't think this could be possible.

**Comment by MattGal** [comment]
I think https://github.com/dotnet/arcade/pull/10778 should fix this once merged.

**Comment by riarenas** [comment]
The build is unblocked now. Thanks @MattGal
