### ISSUE TITLE
darc authenticate hangs

### ISSUE THREAD

**Issue by AdamYoblick** [dotnet/arcade#1152]
Hello,

I'm setting up dependency flow for winforms. I'm at the step when I run darc authenticate and paste in my token. I do that, save the file, and close it, but the command prompt just hangs, so I have no idea if it's successful.

I will try the subsequent steps but I just wanted to let you know :)

@alexperovich 
@jcagme 
@mmitche

**Comment by AdamYoblick** [comment]
Nope, definitely doesn't work. When I try to run darc add-subscription, I get this:

e:\src\repos\github\winforms>darc add-subscription --channel ".NET Tools Latest" --source-repo https://github.com/dotnet/arcade --target-repo https://github.com/dotnet/winforms --target-branch master --update-frequency everyDay --ignore-checks WIP,license/cla --all-checks-passed -q
warn: Microsoft.DotNet.Darc.Operations.Operation[0]
      Failed to load the darc settings file, may be corrupted
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\advolker\.darc\settings'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Microsoft.DotNet.Darc.Helpers.EncodedFile.Read(String fileName) in /_/src/Microsoft.DotNet.Darc/src/Darc/Helpers/EncodedFile.cs:line 34
   at Microsoft.DotNet.Darc.Helpers.LocalSettings.LoadSettings() in /_/src/Microsoft.DotNet.Darc/src/Darc/Helpers/LocalSettings.cs:line 37
   at Microsoft.DotNet.Darc.Helpers.LocalCommands.GetSettings(CommandLineOptions options, ILogger logger) in /_/src/Microsoft.DotNet.Darc/src/Darc/Helpers/LocalCommands.cs:line 27
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Failed to create subscription.
System.ArgumentException: Must supply a build asset registry password
   at Microsoft.DotNet.DarcLib.Remote.CheckForValidBarClient() in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs:line 265
   at Microsoft.DotNet.DarcLib.Remote.CreateSubscriptionAsync(String channelName, String sourceRepo, String targetRepo, String targetBranch, String updateFrequency, List`1 mergePolicies) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs:line 124
   at Microsoft.DotNet.Darc.Operations.AddSubscriptionOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/AddSubscriptionOperation.cs:line 125

**Comment by mmitche** [comment]
I want to take a look at the former problem,  but you should be able to pass the token directly to the command.

**Comment by jcagme** [comment]
Synced with Adam offline and he uses `code` as an editor. I have not tried that on my end but I don't see why would that be different that any other...

**Comment by alexperovich** [comment]
The vscode editor for git requires that core.editor be set to `code --wait` so that the code process will wait for the file to be closed.

**Comment by AdamYoblick** [comment]
Ah ok, sounds like this isn't the default setting. I will try both.

@mmitche Can you provide the syntax for passing in the token directly so I can try that as well?

**Comment by mmitche** [comment]
Add “--bar-uri <token>”

**Comment by AdamYoblick** [comment]
I tried adding --bar-uri to both darc authenticate and darc add-subscription, and neither worked. The first opened the config file for editing again, and the second errored out with the corrupt settings file message.

I will change my vscode settings and try again.

**Comment by mmitche** [comment]
It wouldn't mean anything on authenticate.  What did it say when you did it on add-subscription?

**Comment by AdamYoblick** [comment]
Same error as before, "failed to load the darc settings file, may be corrupted".

I ran the following command now:

git config --global core.editor "code --wait"

And I was able to get past the darc authenticate (it didn't hang, but there was no success message either).

But now when I run:

darc add-subscription --channel ".NET Tools Latest" --source-repo https://github.com/dotnet/arcade --target-repo https://github.com/dotnet/winforms --target-branch master --update-frequency everyDay --ignore-checks WIP,license/cla --all-checks-passed -q

I get this:

fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Failed to create subscription.
Microsoft.DotNet.Maestro.Client.Models.ApiErrorException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.DotNet.Maestro.Client.Subscriptions.CreateWithHttpMessagesAsync(SubscriptionData subscription, Dictionary`2 customHeaders, CancellationToken cancellationToken) in /_/src/Maestro/Client/src/Generated/Subscriptions.cs:line 338
   at Microsoft.DotNet.Maestro.Client.SubscriptionsExtensions.CreateAsync(ISubscriptions operations, SubscriptionData subscription, CancellationToken cancellationToken) in /_/src/Maestro/Client/src/Generated/SubscriptionsExtensions.cs:line 51
   at Microsoft.DotNet.DarcLib.Remote.CreateSubscriptionAsync(String channelName, String sourceRepo, String targetRepo, String targetBranch, String updateFrequency, List`1 mergePolicies) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs:line 136
   at Microsoft.DotNet.Darc.Operations.AddSubscriptionOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/AddSubscriptionOperation.cs:line 125

**Comment by AdamYoblick** [comment]
Spoke with Matt offline and it works now. Here's the fixes:

- Channel name was wrong. It should have been ".NET Tools - Latest". He has updated the doc.
- Our repo had been renamed and this was messing up the maestro logic. He fixed this in the db and now it works.

I will verify the PR happens tomorrow :)

**Comment by jcagme** [comment]
> Our repo had been renamed and this was messing up the maestro logic. He fixed this in the db and now it works.

Just curious, what was before and how did this mess the maestro logic?

**Comment by jcagme** [comment]
Never mind, just saw #1159
