### ISSUE TITLE
Improve dev UX for synchronizing the vmr when local changes have not been pushed to remote

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/arcade#12089]
Steps to Reproduce:
1. Make source-build change in installer and commit.
2. Run vmr-sync.sh e.g. `./eng/vmr-sync.sh -t ../tmp/ -v ../dotnet`

Results:
Failure 

```
fail: Failed to synchronize repo installer
      Required dependency file 'eng/Version.Details.xml' in repository 'dotnet/installer' branch 'cea92f3626c016b4141a961465594db0b9a5efe2' was not found..
dbug: Microsoft.DotNet.DarcLib.DependencyFileNotFoundException: Required dependency file 'eng/Version.Details.xml' in repository 'dotnet/installer' branch 'cea92f3626c016b4141a961465594db0b9a5efe2' was not found.
       ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount)
         at Microsoft.DotNet.DarcLib.GitHubClient.ExecuteRemoteGitCommandAsync(HttpMethod method, String requestUri, ILogger logger, String body, String versionOverride, Int32 retryCount, Boolean logFailure)
         at Microsoft.DotNet.DarcLib.GitHubClient.GetFileContentsAsync(String owner, String repo, String filePath, String branch)
         --- End of inner exception stack trace ---
         at Microsoft.DotNet.DarcLib.GitHubClient.GetFileContentsAsync(String owner, String repo, String filePath, String branch)
         at Microsoft.DotNet.DarcLib.GitHubClient.GetFileContentsAsync(String filePath, String repoUri, String branch)
         at Microsoft.DotNet.DarcLib.GitFileManager.ReadXmlFileAsync(String filePath, String repoUri, String branch)
         at Microsoft.DotNet.DarcLib.GitFileManager.ReadVersionDetailsXmlAsync(String repoUri, String branch)
         at Microsoft.DotNet.DarcLib.GitFileManager.ParseVersionDetailsXmlAsync(String repoUri, String branch, Boolean includePinned)
         at Microsoft.DotNet.DarcLib.VirtualMonoRepo.VmrManagerBase.GetRepoDependencies(String remoteRepoUri, String commitSha)
         at Microsoft.DotNet.DarcLib.VirtualMonoRepo.VmrManagerBase.GetAllDependencies(VmrDependencyUpdate root, CancellationToken cancellationToken)
         at Microsoft.DotNet.DarcLib.VirtualMonoRepo.VmrUpdater.UpdateRepositoryRecursively(VmrDependencyUpdate rootUpdate, Boolean noSquash, CancellationToken cancellationToken)
         at Microsoft.DotNet.Darc.Operations.VirtualMonoRepo.UpdateOperation.ExecuteInternalAsync(IVmrUpdater vmrManager, SourceMapping mapping, String targetRevision, CancellationToken cancellationToken)
         at Microsoft.DotNet.Darc.Operations.VirtualMonoRepo.VmrOperationBase`1.ExecuteAsync(TVmrManager vmrManager, SourceMapping mapping, String targetRevision, CancellationToken cancellationToken)
```

Expected results:

**Preferred**:  the vmr-sync process would support local changes.
**MVP**: the vmr-sync process would give an explicit error message indicating local changes were not pushed.

Note:

I realize the script assumes the following:

  The following scenario is assumed:
  - There is a PR in dotnet/installer
  - The PR is failing on the 'VMR Source-Build' job in the 'Synchronize dotnet/dotnet' step

I am asking for broader support to better support dev workflows.

**Comment by MichaelSimons** [comment]
cc @premun - Is this reasonably possible?

**Comment by premun** [comment]
@MichaelSimons the behaviour you're proposing is actually my plan from the beginning and I am intending to improve this.  There were some features we need to implement first but the last piece (https://github.com/dotnet/arcade/issues/11386) I started working on today.

The end result is that when synchronizing installer, we can start with the installer folder and nothing else by having something like:
```
darc vmr update --vmr ../dotnet --tmp ../tmp --recursive --add-remote installer:. installer
```

(this will make installer get your local commits)

I expect to have this ready by EOW, maybe early next week.

**Comment by premun** [comment]
@MichaelSimons I just had another idea - I could actually use call this `vmr-sync.sh` script to update the local VMR during the CI too because we need to pull changes there the same way. We will then get coverage for this script for free.

**Comment by premun** [comment]
@MichaelSimons this should work now. I have still one more thing to improve but the issue itself is fixed.
