### ISSUE TITLE
Improve the developer UX for quickly reproducing VMR build issues that surface in dependency flow PRs

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/arcade#12101]
Often times source-build issues arise in dependency flow PRs.  When these occur, repo owners are looped in to help investigate.  They often want a repro environment they can investigate and try new fixes in.  To do this, devs would need to pull the dependency flow branch, run the vmr sync process and build the VMR locally.  We should investigate ways to streamline this process and provide an already configured environment if possible.

Suggestions discussed by members of the unified build v-team:
1. Codespace - create a codespace configured with the VMR synchronized with the changes from the PR.
2. Container artifact - capture a container image as a build artifact from the PR.  This would contain the current working environment which the failure occurred in.
3. VMR tarball artifact - capture a tarball of the synchronized VMR as a build artifact from the PR.  It would probably be most valuable if the VMR was captured prior to the build.  Capturing the built VMR would be of limited value because you would only be able to build it in an equivalent environment used by CI.

**Comment by MichaelSimons** [comment]
cc @premun

**Comment by premun** [comment]
I think I formed an opinion on this:

1. Codespaces will give people the most flexibility while it will only be created when they actually need it. It doesn't require many changes, the devcontainer definition will be few lines of code.
2. Container just seems like Codespaces with extra steps?
3. Uploading artifacts with every build seems wasteful and also possibly useless as they won't get the environment to be able to reproduce the build to verify a fix.

Only downside of 1. is that we loose the error state but my understanding is that these failures that occur reproduce usually 100% of the time?

**Comment by MichaelSimons** [comment]
I don't recall encountering an intermittent issue.  I think Codespaces would be a fine solution.

**Comment by premun** [comment]
Okay, once we merge all the latest changes around getting commits from the local installer dir, this will be a piece of cake.

@MichaelSimons just one question about `prep.sh` work:
- Is it idempotent?
- Should it be already run as part of the image?

**Comment by MichaelSimons** [comment]
> Is it idempotent?

Yes

> Should it be already run as part of the image?

Yes

**Comment by premun** [comment]
@MichaelSimons I think it should be fairly easy to create the Codespace but I am hitting this issue with `unset RepositoryName`.

I tried to add this into various places but I don't have visibility into the hierarchy of how the Codespace is created so I failed to set this for the default shell. I am too afraid to put it in `.bashrc` for obvious reasons.

I am thinking of putting this into the `build.sh` script? We could condition this with some other preset variables set by Codespaces.

Otherwise, we'd have to have a README instruction about this and that seems suboptimal.

**Comment by premun** [comment]
I found that you can open files automatically for them. Maybe we could open some README suitable for the investigation - https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/automatically-opening-files-in-the-codespaces-for-a-repository

**Comment by premun** [comment]
I am poking at this while waiting for builds and it seems like I'm hitting a problem with the image:

```
LibGit2Sharp.LibGit2SharpException: could not load ssl libraries
    at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
    at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 172
    at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteHandle remote, IEnumerable`1 refSpecs, GitFetchOptions fetchOptions, String logMessage) in /_/LibGit2Sharp/Core/Proxy.cs:line 2285
    at LibGit2Sharp.Commands.Fetch(Repository repository, String remote, IEnumerable`1 refspecs, FetchOptions options, String logMessage) in /_/LibGit2Sharp/Commands/Fetch.cs:line 80
    at Microsoft.DotNet.DarcLib.LocalGitClient.AddRemoteIfMissing(String repoDir, String repoUrl, Boolean forceFetch)
    at Microsoft.DotNet.DarcLib.VirtualMonoRepo.RepositoryCloneManager.PrepareCloneInternal(String remoteUri, String dirName, CancellationToken cancellationToken)
    at Microsoft.DotNet.DarcLib.VirtualMonoRepo.RepositoryCloneManager.PrepareClone(SourceMapping mapping, String[] remoteUris, String checkoutRef, CancellationToken cancellationToken)
    at Microsoft.DotNet.DarcLib.VirtualMonoRepo.VmrUpdater.UpdateRepository(String mappingName, String targetRevision, String targetVersion, Boolean noSquash, Boolean updateDependencies, IReadOnlyCollection`1 additionalRemotes, CancellationToken cancellationToken)
    at Microsoft.DotNet.Darc.Operations.VirtualMonoRepo.UpdateOperation.ExecuteInternalAsync(IVmrUpdater vmrManager, String repoName, String targetRevision, IReadOnlyCollection`1 additionalRemotes, CancellationToken cancellationToken)
    at Microsoft.DotNet.Darc.Operations.VirtualMonoRepo.VmrOperationBase`1.ExecuteAsync(TVmrManager vmrManager, String repoName, String targetRevision, IReadOnlyCollection`1 additionalRemotes, CancellationToken cancellationToken)

```

Which leads me here: https://fossies.org/linux/libgit/src/libgit2/streams/openssl_dynamic.c (line 124)

**Comment by premun** [comment]
I will need this package in the image: `openssl1.1.x86_64`

**Comment by premun** [comment]
I have a working solution, just needs tidying up and a README that will open in the Codespace with instructions

**Comment by premun** [comment]
I believe this is completed now.
