### ISSUE TITLE
VMR tooling cannot tell if a sync is not needed

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#12273]
### Problem

When we are synchronizing `installer` to a SHA that's already in the VMR, it synchronizes everything and then fails on an empty commit.

### Expected behaviour

We should stop and say we're good.

### Repro:
1. Go to installer's main page
2. Start the `vmr-source-build` Codespace

### Log:
```
2023-01-19 16:12:56.773Z: [?1h2023-01-19 16:12:56.940Z: [?1h2023-01-19 16:12:56.940Z: [1.1.0-beta.23068.1+fbfe3ef4178f3e5ca05ee32ebd4a20599e72f115 / Microsoft.DotNet.Darc.exe] darc command issued: vmr update --vmr /workspaces/dotnet --tmp /workspaces/tmp --debug --recursive --additional-remotes installer:/workspaces/installer installer:d16b6058683c36009281b9e5a119d4964dbf2cbe
2023-01-19 16:12:57.259Z: dbug: Cloning https://github.com/dotnet/installer to /workspaces/tmp/installer
2023-01-19 16:12:57.261Z: info: Cloning https://github.com/dotnet/installer to /workspaces/tmp/installer
dbug: Cloning https://github.com/dotnet/installer to /workspaces/tmp/installer
2023-01-19 16:13:04.835Z: dbug: Clone of /workspaces/installer found in /workspaces/tmp/installer
2023-01-19 16:13:04.843Z: dbug: Adding /workspaces/installer remote to /workspaces/tmp/installer
2023-01-19 16:13:04.849Z: dbug: Executing command: 'git -C /workspaces/tmp/installer fetch /workspaces/installer'
2023-01-19 16:13:04.874Z: [?1h2023-01-19 16:13:04.885Z: dbug: Checking out d16b6058683c36009281b9e5a119d4964dbf2cbe
dbug: Reading local repo from /workspaces/tmp/installer
2023-01-19 16:13:04.886Z: dbug: Attempting to check out d16b6058683c36009281b9e5a119d4964dbf2cbe in /workspaces/tmp/installer
2023-01-19 16:13:04.887Z: dbug: Trying safe checkout of /workspaces/tmp/installer/ at d16b6058683c36009281b9e5a119d4964dbf2cbe
2023-01-19 16:13:04.993Z: dbug: Loading a new version of source mappings from /workspaces/tmp/installer/src/VirtualMonoRepo/source-mappings.json
2023-01-19 16:13:04.998Z: info: Recursive update for installer / d16b605 → d16b6058683c36009281b9e5a119d4964dbf2cbe
2023-01-19 16:13:05.001Z: info: Finding transitive dependencies for installer:d16b6058683c36009281b9e5a119d4964dbf2cbe..
2023-01-19 16:13:05.019Z: dbug: Detected installer's dependency runtime (https://github.com/dotnet/runtime / 19fc478d67c2fc55e62b50676935f903a77f5a4d)
dbug: Detected installer's dependency aspnetcore (https://github.com/dotnet/aspnetcore / d8f7f80ecc6d8d27c92b1cae7c9b3a0afb4b0e20)
dbug: Detected installer's dependency test-templates (https://github.com/dotnet/test-templates / bb3695688177f5f80eeb3c0498168612e31549d5)
dbug: Detected installer's dependency sdk (https://github.com/dotnet/sdk / be8529b23ca7d3748343df9f2e699b401abcd9ea)
dbug: Detected installer's dependency fsharp (https://github.com/dotnet/fsharp / 6ebe669cd147075a2e66699cf4e1b1a338f89fe5)
dbug: Detected installer's dependency vstest (https://github.com/microsoft/vstest / 5e9c3debd9d0007c53e7510ac030ea5e8fc483f4)
dbug: Detected installer's dependency linker (https://github.com/dotnet/linker / c790896f128957acd2999208f44f09ae1e826c8c)
dbug: Detected installer's dependency roslyn (https://github.com/dotnet/roslyn / 3bb9af87333b7453ada242d81fb7f38be42a9aef)
dbug: Detected installer's dependency msbuild (https://github.com/dotnet/msbuild / 98924b86bbc19aff3360f9cc3a2922df6a5c5d6a)
dbug: Detected installer's dependency nuget-client (https://github.com/nuget/nuget.client / 743503cb3c7e9ced2602ee2e29c38d63cc339451)
dbug: Detected installer's dependency deployment-tools (https://github.com/dotnet/deployment-tools / c3ad00ae84489071080a606f6a8e43c9a91a5cc2)
dbug: Detected installer's dependency source-build-externals (https://github.com/dotnet/source-build-externals / df9dd3b66b2fa6d86eb01bb5b2493435bdfa2649)
dbug: Detected installer's dependency symreader (https://github.com/dotnet/symreader / 7b9791daa3a3477eb22ec805946c9fff8b42d8ca)
dbug: Detected installer's dependency arcade (https://github.com/dotnet/arcade / 3600aa80a01e90f38a7b86b9d7c1264e091aa5a8)
dbug: Detected installer's dependency source-build-reference-packages (https://github.com/dotnet/source-build-reference-packages / 44c3e166651615f4ae66f0dfa236f082de84d7c5)
dbug: Detected installer's dependency sourcelink (https://github.com/dotnet/sourcelink / de25d2565e5b89ff1d7eee1bce066005b272e365)
dbug: Detected installer's dependency xliff-tasks (https://github.com/dotnet/xliff-tasks / db632746f5ea995c60cc63a25229818558434018)
2023-01-19 16:13:05.025Z: dbug: Detected aspnetcore's dependency xdt (https://github.com/dotnet/xdt / 9a1c3e1b7f0c8763d4c96e593961a61a72679a7b)
2023-01-19 16:13:05.027Z: dbug: Detected sdk's dependency templating (https://github.com/dotnet/templating / 4827cbc295e50af2f7162172e81514ad3b671bf0)
dbug: Detected sdk's dependency format (https://github.com/dotnet/format / 2cb3e68c6b9a966114572fd63f2a20d2cb54a288)
dbug: Detected sdk's dependency razor (https://github.com/dotnet/razor / b2d15be01c8b9615b819fb8cffed4ccd02cdff2f)
dbug: Detected sdk's dependency roslyn-analyzers (https://github.com/dotnet/roslyn-analyzers / b08c60aab8f6249ecccdeee580c35bea824e1276)
dbug: Detected sdk's dependency command-line-api (https://github.com/dotnet/command-line-api / 8374d5fca634a93458c84414b1604c12f765d1ab)
2023-01-19 16:13:05.027Z: dbug: Detected vstest's dependency diagnostics (https://github.com/dotnet/diagnostics / e3e1490a23f27a6e0ed30d323035660c3ffc52cd)
2023-01-19 16:13:05.032Z: info: Found 25 transitive dependencies for installer:d16b6058683c36009281b9e5a119d4964dbf2cbe..
2023-01-19 16:13:05.035Z: info: Creating a temporary work branch sync/installer/d16b605-d16b6058683c36009281b9e5a119d4964dbf2cbe
2023-01-19 16:13:10.144Z: dbug: Dependency installer is already at d16b6058683c36009281b9e5a119d4964dbf2cbe, skipping..
dbug: Dependency runtime is already at 19fc478d67c2fc55e62b50676935f903a77f5a4d, skipping..
dbug: Dependency aspnetcore is already at d8f7f80ecc6d8d27c92b1cae7c9b3a0afb4b0e20, skipping..
dbug: Dependency test-templates is already at bb3695688177f5f80eeb3c0498168612e31549d5, skipping..
dbug: Dependency sdk is already at be8529b23ca7d3748343df9f2e699b401abcd9ea, skipping..
dbug: Dependency fsharp is already at 6ebe669cd147075a2e66699cf4e1b1a338f89fe5, skipping..
dbug: Dependency vstest is already at 5e9c3debd9d0007c53e7510ac030ea5e8fc483f4, skipping..
dbug: Dependency linker is already at c790896f128957acd2999208f44f09ae1e826c8c, skipping..
dbug: Dependency roslyn is already at 3bb9af87333b7453ada242d81fb7f38be42a9aef, skipping..
dbug: Dependency msbuild is already at 98924b86bbc19aff3360f9cc3a2922df6a5c5d6a, skipping..
dbug: Dependency nuget-client is already at 743503cb3c7e9ced2602ee2e29c38d63cc339451, skipping..
dbug: Dependency deployment-tools is already at c3ad00ae84489071080a606f6a8e43c9a91a5cc2, skipping..
dbug: Dependency source-build-externals is already at df9dd3b66b2fa6d86eb01bb5b2493435bdfa2649, skipping..
dbug: Dependency symreader is already at 7b9791daa3a3477eb22ec805946c9fff8b42d8ca, skipping..
dbug: Dependency arcade is already at 3600aa80a01e90f38a7b86b9d7c1264e091aa5a8, skipping..
dbug: Dependency source-build-reference-packages is already at 44c3e166651615f4ae66f0dfa236f082de84d7c5, skipping..
dbug: Dependency sourcelink is already at de25d2565e5b89ff1d7eee1bce066005b272e365, skipping..
dbug: Dependency xliff-tasks is already at db632746f5ea995c60cc63a25229818558434018, skipping..
dbug: Dependency xdt is already at 9a1c3e1b7f0c8763d4c96e593961a61a72679a7b, skipping..
dbug: Dependency templating is already at 4827cbc295e50af2f7162172e81514ad3b671bf0, skipping..
dbug: Dependency format is already at 2cb3e68c6b9a966114572fd63f2a20d2cb54a288, skipping..
dbug: Dependency razor is already at b2d15be01c8b9615b819fb8cffed4ccd02cdff2f, skipping..
dbug: Dependency roslyn-analyzers is already at b08c60aab8f6249ecccdeee580c35bea824e1276, skipping..
dbug: Dependency command-line-api is already at 8374d5fca634a93458c84414b1604c12f765d1ab, skipping..
dbug: Dependency diagnostics is already at e3e1490a23f27a6e0ed30d323035660c3ffc52cd, skipping..
2023-01-19 16:13:10.144Z: info: Merging sync/installer/d16b605-d16b6058683c36009281b9e5a119d4964dbf2cbe into main
2023-01-19 16:13:12.052Z: fail: Failed to synchronize repo installer
      No changes; nothing to commit..
2023-01-19 16:13:12.061Z: dbug: LibGit2Sharp.EmptyCommitException: No changes; nothing to commit.
         at LibGit2Sharp.Repository.Commit(String message, Signature author, Signature committer, CommitOptions options) in /_/LibGit2Sharp/Repository.cs:line 1053
         at LibGit2Sharp.RepositoryExtensions.Commit(IRepository repository, String message, Signature author, Signature committer) in /_/LibGit2Sharp/RepositoryExtensions.cs:line 200
         at Microsoft.DotNet.DarcLib.VirtualMonoRepo.VmrManagerBase.WorkBranch.MergeBack(String commitMessage)
         at Microsoft.DotNet.DarcLib.VirtualMonoRepo.VmrUpdater.UpdateRepositoryRecursively(VmrDependencyUpdate rootUpdate, Boolean noSquash, IReadOnlyCollection`1 additionalRemotes, CancellationToken cancellationToken)
         at Microsoft.DotNet.DarcLib.VirtualMonoRepo.VmrUpdater.UpdateRepository(String mappingName, String targetRevision, String targetVersion, Boolean noSquash, Boolean updateDependencies, IReadOnlyCollection`1 additionalRemotes, CancellationToken cancellationToken)
         at Microsoft.DotNet.Darc.Operations.VirtualMonoRepo.UpdateOperation.ExecuteInternalAsync(IVmrUpdater vmrManager, String repoName, String targetRevision, IReadOnlyCollection`1 additionalRemotes, CancellationToken cancellationToken)
         at Microsoft.DotNet.Darc.Operations.VirtualMonoRepo.VmrOperationBase`1.ExecuteAsync(TVmrManager vmrManager, String repoName, String targetRevision, IReadOnlyCollection`1 additionalRemotes, CancellationToken cancellationToken)
2023-01-19 16:13:12.844Z: [?1h2023-01-19 16:13:12.863Z: + fail 'Synchronization of dotnet/dotnet to '\''d16b6058683c36009281b9e5a119d4964dbf2cbe'\'' failed!'
+ echo '> Synchronization of dotnet/dotnet to '\''d16b6058683c36009281b9e5a119d4964dbf2cbe'\'' failed!(B[m'
```

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
Not release notes worthy

**Comment by premun** [comment]
This is done
