### ISSUE TITLE
Latest requests package breaks helix installer

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#12332]
```
Traceback (most recent call last):
  File "installer.py", line 5, in <module>
    import requests
  File "C:\h\scripts\helix-scripts\requests\__init__.py", line 105, in <module>
    check_compatibility(
  File "C:\h\scripts\helix-scripts\requests\__init__.py", line 86, in check_compatibility
    raise Exception("You need either charset_normalizer or chardet installed")
```

First seen on on-prem machines, this seems to have started on 1/12/2023 when the requests library [got updated](https://pypi.org/project/requests/2.28.2/#history).  I am prepping a PR to staging to hopefully address this; we can discuss hotfixing later today once this looks good. 

### Release Note Description
Downgraded Helix client requests package to address issues seen with 1/12 release

**Comment by MattGal** [comment]
Merged bypassing policy (it's just changing the package lists) and am [watching the latest main run](https://dnceng.visualstudio.com/internal/_build/results?buildId=2097649&view=results)

**Comment by MattGal** [comment]
Rolled out last week and is holding.  #12335 tracks trying other approaches;  closing.
