### ISSUE TITLE
VMR synchronization failure

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/arcade#12347]
I have been seeing sporadic failures in the `Synchronize dotnet/dotnet` step in PR validation today.   This appears to be sporadic as retries have been passing.

Example failure - https://dev.azure.com/dnceng-public/public/_build/results?buildId=150924&view=logs&jobId=05882a6c-efef-5a6d-93ff-ade1c8185ed1&j=05882a6c-efef-5a6d-93ff-ade1c8185ed1&t=3fc0d7eb-9c2c-5bdf-e2c4-2f6647c01f1e

```
> Starting the synchronization to '1f621580da6333296362ca847c2da4474ff1c793'..
info: Cloning *** to /mnt/vss/_work/_temp/installer
info: Checkout of /mnt/vss/_work/_temp/installer/ at 1f621580da6333296362ca847c2da4474ff1c793 failed: LibGit2Sharp.NotFoundException: No valid git object identified by '1f621580da6333296362ca847c2da4474ff1c793' exists in the repository.
         at LibGit2Sharp.Core.Ensure.GitObjectIsNotNull(GitObject gitObject, String identifier) in /_/LibGit2Sharp/Core/Ensure.cs:line 265
         at LibGit2Sharp.Repository.RevParse(String revision, Reference& reference, GitObject& obj) in /_/LibGit2Sharp/Repository.cs:line 1750
         at LibGit2Sharp.Commands.Checkout(IRepository repository, String committishOrBranchSpec, CheckoutOptions options) in /_/LibGit2Sharp/Commands/Checkout.cs:line 47
         at Microsoft.DotNet.DarcLib.Helpers.LibGit2SharpHelpers.SafeCheckout(Repository repo, String commit, CheckoutOptions options, ILogger log)
info: Fetching before attempting individual files.
fail: Failed to synchronize repo installer
      Something went wrong when checking out 1f621580da6333296362ca847c2da4474ff1c793 in /mnt/vss/_work/_temp/installer.
> Synchronization of dotnet/dotnet to '1f621580da6333296362ca847c2da4474ff1c793' failed!
> '/mnt/vss/_work/1/vmr' is left in its last state (re-run of this script will reset it).
> Please inspect the logs which contain path to the failing patch file (use --debug to get all the details).
> Once you make changes to the conflicting VMR patch, commit it locally and re-run this script.
```

**Comment by MichaelSimons** [comment]
cc @premun

**Comment by premun** [comment]
This is really weird. Was there by any chance any force-pushing in the branch around the time this happened?

What's going on there is that AzDO shallow-clones the installer repo, whichever they do it, to fetch the PR branch, just like in any other build. Our tooling, when cloning installer to its temp later sets this original installer folder as an additional remote and fetches everything from it so that it has the commit we are running the build from.

**Comment by premun** [comment]
Ok so I think I have one possible cause. This seems to happen when we have a shallow clone of installer only. Git then fails to perform certain operations.

**Comment by premun** [comment]
Seems like we finally get another repro but with more verbose logging this time:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=198919&view=logs&j=941f2e24-48a0-594a-6b1a-0e16aaeb8606&t=9aff3b87-cb8c-5340-9b44-3b8bd573e8db&l=304
