### ISSUE TITLE
PublishBuildAssets doesn't control its dependencies

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#1315]
Here's the error:
```
2018-11-01T18:23:06.4201083Z   Starting build metadata push to the Build Asset Registry...
2018-11-01T18:23:12.6958537Z C:\Users\VssAdministrator\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.18526.9\tools\PublishBuildAssets.proj(25,5): error : Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
2018-11-01T18:23:12.6960954Z C:\Users\VssAdministrator\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.18526.9\tools\PublishBuildAssets.proj(25,5): error :    at Microsoft.DotNet.Maestro.Client.MaestroApi.Initialize()
2018-11-01T18:23:12.6961387Z C:\Users\VssAdministrator\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.18526.9\tools\PublishBuildAssets.proj(25,5): error :    at Microsoft.DotNet.Maestro.Client.MaestroApi..ctor(Uri baseUri, ServiceClientCredentials credentials, DelegatingHandler[] handlers)
2018-11-01T18:23:12.6961719Z C:\Users\VssAdministrator\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.18526.9\tools\PublishBuildAssets.proj(25,5): error :    at Microsoft.DotNet.Maestro.Client.ApiFactory.GetAuthenticated(String baseUri, String accessToken)
2018-11-01T18:23:12.6962047Z C:\Users\VssAdministrator\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.18526.9\tools\PublishBuildAssets.proj(25,5): error :    at Microsoft.DotNet.Maestro.Tasks.PushMetadataToBuildAssetRegistry.<PushMetadataAsync>d__16.MoveNext()
 ```

It appears that publishBuildAssets just assumes your repo's project is going to restore the dependencies it requires.  Likely because publishBuildAssets is a proj and not a csproj so it just relies on your sln / csproj's for asset restoration.

https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/PublishBuildAssets.proj

PublishBuildAssets should be self-contained so that if you're trying to publish, you can run independent of the repo state.

**Comment by chcosta** [comment]
A viable workaround appears to be to use the "dotnet" msbuild engine instead of relying on the desktop MSBuild.

https://dnceng.visualstudio.com/internal/_git/4b71a4ab-74f7-4d5a-a549-a976dd80cb07/commit/01ace5f8b973a56e252d5cfbc7bbb5294d19cdba/

The scenario is still slightly busted though since there's no reason to  do a full repo restore for a solution only to use this publish project.
