### ISSUE TITLE
Drops issue: VS30063: You are not authorized to access https://devdiv.artifacts.visualstudio.com

### ISSUE THREAD

**Issue by vzarytovskii** [dotnet/arcade#13193]
Build is failing with
```
DropExeWrapper Warning: 0 : Attempt 5 to create drop 'Products/internal/dotnet-fsharp/dev17.7/20230418.2' failed. Retrying...

Exception: Engineering.Shared.Vsts.ArtifactServices.VstsDrop.VstsDropException: The command 'D:\a\_work\_tasks\MicroBuildUploadVstsDropFolder_4305a8de-ba66-4d8b-b2d1-0dc4ecbbf5e8\1.5.2\VstsDrop\lib\net45\drop.exe Create --DropService "[https://devdiv.artifacts.visualstudio.com/"](https://devdiv.artifacts.visualstudio.com/%22) --PatAuthEnvVar "bad5e734-3621-4267-8759-a27aa7437ed3" --Timeout "10" --TraceLevel "Verbose" --Name "Products/internal/dotnet-fsharp/dev17.7/20230418.2" --ExpirationDate "4/18/2033 12:28:52 PM"' failed with exit code 100

at Engineering.Shared.Vsts.ArtifactServices.VstsDrop.Clients.DropExe.DropExeWrapper.<>c__DisplayClass55_0.<Execute>b__0()

at Engineering.Shared.Reliability.RetryUtilities.<>c__DisplayClass3_0.<Retry>b__0()

at Engineering.Shared.Reliability.RetryUtilities.Retry[T](Func`1 method, Int32 maxAttempts, TimeSpan delayBetweenAttempts, Action`2 onAttemptFailure, Func`2 isExceptionRetryable)
```

The issue seems to be related to the `dn-bot-devdiv-drop-rw-code-rw` access token.

https://dev.azure.com/dnceng/internal/_build/results?buildId=2161178&view=logs&j=e3072f97-b3f6-597b-f816-087a04d4fd77&t=ac45dc56-44bd-507b-e50c-548ef96d0dae&l=51

**Comment by vzarytovskii** [comment]
Going to close it and reopen via template
