### ISSUE TITLE
[Maestro] Dependency update failed in corefx

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#1366]
```
	
Octokit.ApiException: Server Error
   at Octokit.Connection.HandleErrors(IResponse response) in C:\projects\octokit-net\Octokit\Http\Connection.cs:line 665
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in C:\projects\octokit-net\Octokit\Http\Connection.cs:line 642
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in C:\projects\octokit-net\Octokit\Http\Connection.cs:line 626
   at Octokit.ApiConnection.Post[T](Uri uri, Object data, String accepts, String contentType)
   at Microsoft.DotNet.DarcLib.GitHubClient.RemoveFilesFromTree(String owner, String repo, String baseTreeSha, IEnumerable`1 filesToRemove) in E:\eng\dotnet\arcade\src\Microsoft.DotNet.Darc\src\DarcLib\GitHubClient.cs:line 856
   at Microsoft.DotNet.DarcLib.GitHubClient.CreateGitHubTreeAsync(String owner, String repo, IEnumerable`1 filesToCommit, TreeResponse baseTree) in E:\eng\dotnet\arcade\src\Microsoft.DotNet.Darc\src\DarcLib\GitHubClient.cs:line 727
   at Microsoft.DotNet.DarcLib.GitHubClient.PushFilesAsync(List`1 filesToCommit, String repoUri, String branch, String commitMessage) in E:\eng\dotnet\arcade\src\Microsoft.DotNet.Darc\src\DarcLib\GitHubClient.cs:line 162
   at Microsoft.DotNet.DarcLib.Remote.CommitUpdatesAsync(String repoUri, String branch, List`1 itemsToUpdate, String message) in E:\eng\dotnet\arcade\src\Microsoft.DotNet.Darc\src\DarcLib\Actions\Remote.cs:line 393
   at SubscriptionActorService.PullRequestActorImplementation.CommitUpdatesAsync(List`1 requiredUpdates, StringWriter description, IRemote darc, String targetRepository, String newBranchName) in E:\eng\dotnet\arcade\src\Maestro\SubscriptionActorService\PullRequestActor.cs:line 623
   at SubscriptionActorService.PullRequestActorImplementation.CreatePullRequestAsync(List`1 updates) in E:\eng\dotnet\arcade\src\Maestro\SubscriptionActorService\PullRequestActor.cs:line 562
   at SubscriptionActorService.PullRequestActorImplementation.UpdateAssetsAsync(Guid subscriptionId, Int32 buildId, String sourceSha, List`1 assets) in E:\eng\dotnet\arcade\src\Maestro\SubscriptionActorService\PullRequestActor.cs:line 525
   at SubscriptionActorService.ActionRunner.InvokeAction[T](IActionTracker target, ActionMethod method, Object[] arguments) in E:\eng\dotnet\arcade\src\Maestro\SubscriptionActorService\ActionRunner\ActionRunner.cs:line 95
{
  "message": "Server Error"
}
```

@jcagme

**Comment by alexperovich** [comment]
this is the github 500 we saw a weekish ago.

**Comment by jcagme** [comment]
This is failing when we try to create the new tree which doesn't include the files which are meant to be removed. My guess at this point is that github has some sort of tree "size" limit given that the tree we create for arcade is around 1,500 compared to that in corefx which is close to 20,000.

I haven't found any place where this number is documented so I've started a couple of threads with the GH community.

**Comment by mmitche** [comment]
@jcagme Maybe it would be better to not use octokit in these cases (just do a checkout in a temp repo, make changes, then push the branch)

**Comment by jcagme** [comment]
This is not an Octokit thing but the way the trees api is implemented by GH. At the end Octokit ends up making a request to GitHub. Unless there is some sort of quick and easy thing that we can set in the request to avoid this issue we may actually need to do what you suggest.

**Comment by jcagme** [comment]
https://github.com/dotnet/arcade/pull/1388

**Comment by mmitche** [comment]
This has been resolved and rolled out.
