### ISSUE TITLE
Arcade official build failing during onelocbuild job

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#13797]
- [X] This issue is blocking 
Blocking official build
- [ ] This issue is causing unreasonable pain

Latest builds of arcade's official build have been failing during the onelocbuild job https://dnceng.visualstudio.com/internal/_build/results?buildId=2198466&view=results

```
OneLocBuildClient.exe Information: 0 : Preparing localized file check-in...
OneLocBuildClient.exe Error: 0 : Octokit.AuthorizationException: Bad credentials
   at Octokit.Connection.HandleErrors(IResponse response) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 709
   at Octokit.Connection.<RunRequest>d__61.MoveNext() in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 686
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__60`1.MoveNext() in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 670
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Get>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Polly.Retry.AsyncRetryEngine.<ImplementationAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.AsyncPolicy.<ExecuteAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OneLocBuildClient.GitHubCheckin.<CallGitHubApiWithRetryAsync>d__24`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OneLocBuildClient.GitHubCheckin.<InitializeAsync>d__13.MoveNext() in C:\__w\1\s\src\OneLocBuildClient\GitHubCheckin.cs:line 189
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OneLocBuildClient.GitHubCheckin.<RunAsync>d__12.MoveNext() in C:\__w\1\s\src\OneLocBuildClient\GitHubCheckin.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OneLocBuildClient.LocController.<RunAsync>d__6.MoveNext() in C:\__w\1\s\src\OneLocBuildClient\LocController.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OneLocBuildClient.Program.Main(String[] args) in C:\__w\1\s\src\OneLocBuildClient\Program.cs:line 46
{"message":"Bad credentials","documentation_url":"[https://docs.github.com/rest"}](https://docs.github.com/rest%22%7D)
```

Smells like an expired PAT.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by riarenas** [comment]
This was fixed by @MilenaHristova. https://dnceng.visualstudio.com/internal/_build/results?buildId=2198803&view=results already went past the error.
