### ISSUE TITLE
System.ComponentModel.Win32Exception : An error occurred trying to start process 'notepad.exe' with working directory 'C:\h\w\9F8D0903\w\B7E309C0\e'. Access is denied

### ISSUE THREAD

**Issue by Maoni0** [dotnet/arcade#13793]
### Build

https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=302756

https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-87372-merge-563116f2d3404bad82/System.Diagnostics.Process.Tests/1/console.b1eb782a.log?helixlogtype=result

```
C:\h\w\9F8D0903\w\B7E309C0\e>"C:\h\w\9F8D0903\p\dotnet.exe" exec --runtimeconfig System.Diagnostics.Process.Tests.runtimeconfig.json --depsfile System.Diagnostics.Process.Tests.deps.json xunit.console.dll System.Diagnostics.Process.Tests.dll -xml testResults.xml -nologo -nocolor -trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing  
  Discovering: System.Diagnostics.Process.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Diagnostics.Process.Tests (found 12 of 290 test cases)
  Starting:    System.Diagnostics.Process.Tests (parallel test collections = on, max threads = 2)
    System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent_withArgumentList(useShellExecute: True) [FAIL]
      System.ComponentModel.Win32Exception : An error occurred trying to start process 'notepad.exe' with working directory 'C:\h\w\9F8D0903\w\B7E309C0\e'. Access is denied.
      Stack Trace:
        /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Win32.cs(92,0): at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
        /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Win32.cs(25,0): at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
        /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs(1282,0): at System.Diagnostics.Process.Start()
        /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs(1350,0): at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
        /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs(1308,0): at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent_withArgumentList(Boolean useShellExecute)
           at InvokeStub_ProcessStartInfoTests.StartInfo_NotepadWithContent_withArgumentList(Object, Object, IntPtr*)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
  Finished:    System.Diagnostics.Process.Tests
```

### Build leg reported

System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent_withArgumentList

### Pull Request

https://github.com/dotnet/runtime/pull/87372

### Known issue core information

Fill out the known issue JSON section by following the [step by step documentation on how to create a known issue](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step)

```json
 {
    "ErrorMessage" : "",
    "BuildRetry": false,
    "ErrorPattern": "System.ComponentModel.Win32Exception : An error occurred trying to start process .* with working directory",
    "ExcludeConsoleLog": false
 }
 ```

 @dotnet/dnceng

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by missymessa** [comment]
@Maoni0 It looks like this error is impacting Runtime only. Is this an infra failure or a failure specific to Runtime tests?
