### ISSUE TITLE
darc authenticate crashes without core.editor set

### ISSUE THREAD

**Issue by rynowak** [dotnet/arcade#1447]
Repro:

unset `core.editor` in your git config
run `darc authenticate`

```
D:\k\AspNetCore-Tooling [rynowak/publising]> darc authenticate
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      There was an error while running git.exe config --get core.editor
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      There was an exception while trying to pop up an editor window.
System.ComponentModel.Win32Exception (2): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Darc.Helpers.UxManager.PopUp(EditorPopUp popUp) in /_/src/Microsoft.DotNet.Darc/src/Darc/Helpers/
UxManager.cs:line 94
```

**Comment by mmitche** [comment]
Fix in: https://github.com/dotnet/arcade/pull/1519
