### ISSUE TITLE
Unhandled exception running darc add-subscription

### ISSUE THREAD

**Issue by rynowak** [dotnet/arcade#1502]
I'm trying to follow the instructions here: https://github.com/dotnet/arcade/blob/master/Documentation/DependencyFlowOnboarding.md#34-create-a-subscription-to-get-arcade-updates

This is failing on step 3.4
```
System.ArgumentException: Must supply a build asset registry password
   at Microsoft.DotNet.DarcLib.Remote.CheckForValidBarClient() in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs:line 456
   at Microsoft.DotNet.DarcLib.Remote.GetChannelsAsync(String classification) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs:line 414
   at Microsoft.DotNet.Darc.Operations.AddSubscriptionOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/AddSubscriptionOperation.cs:line 95
   at Microsoft.DotNet.Darc.Program.RunOperation(CommandLineOptions opts) in /_/src/Microsoft.DotNet.Darc/src/Darc/Program.cs:line 33
```

I have already done a `darc authorize` and added my access token.

**Comment by mmitche** [comment]
Can you try adding --password <bar password>?

**Comment by bricelam** [comment]
@mmitche That worked for me.

**Comment by jcagme** [comment]
@bricelam just to make sure I understand correctly. You passed the `--password` option and it worked, but did you try setting `bar_password` in the popup when executing `darc authenticate`?

**Comment by mmitche** [comment]
Fixed by https://github.com/dotnet/arcade/pull/1517
