### ISSUE TITLE
darc get-dependency-graph crashes

### ISSUE THREAD

**Issue by rynowak** [dotnet/arcade#1515]
```
C:\git\aspnet\AspNetCore-Tooling [master ≡ +1 ~4 -0 !]> darc get-dependency-graph -p <redacted_yo>
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Something failed while trying the fetch the dependencies of repo 'https://github.com/dotnet/arcade' at sha 'c3be73644108181b6c951c3ef8febd220a2a79f3'
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at Microsoft.DotNet.DarcLib.DependencyGraph.GetRepoPath(DependencyDetail dependency, IEnumerable`1 remotesMap, String reposFolder, ILogger logger) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyGraph.cs:line 103
   at Microsoft.DotNet.DarcLib.DependencyGraph.GetDependenciesAsync(DarcSettings darcSettings, Boolean remote, ILogger logger, DependencyGraphNode node, IEnumerable`1 remotesMap, String reposFolder, String testPath) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyGraph.cs:line 190
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Something failed while getting the dependency graph.
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at Microsoft.DotNet.DarcLib.DependencyGraph.GetRepoPath(DependencyDetail dependency, IEnumerable`1 remotesMap, String reposFolder, ILogger logger) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyGraph.cs:line 103
   at Microsoft.DotNet.DarcLib.DependencyGraph.GetDependenciesAsync(DarcSettings darcSettings, Boolean remote, ILogger logger, DependencyGraphNode node, IEnumerable`1 remotesMap, String reposFolder, String testPath) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyGraph.cs:line 190
   at Microsoft.DotNet.DarcLib.DependencyGraph.GetDependencyGraphAsync(DarcSettings darcSettings, DependencyDetail dependency, Boolean remote, ILogger logger, String reposFolder, IEnumerable`1 remotesMap, String testPath) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyGraph.cs:line 56
   at Microsoft.DotNet.Darc.Operations.GetDependencyGraphOperation.AddNodeToGraphAsync(DarcSettings darcSettings, DependencyDetail dependency, List`1 graph) in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/GetDependencyGraphOperation.cs:line 125
   at Microsoft.DotNet.Darc.Operations.GetDependencyGraphOperation.CreateGraphAsync(IEnumerable`1 dependencies, DarcSettings darcSettings) in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/GetDependencyGraphOperation.cs:line 98
   at Microsoft.DotNet.Darc.Operations.GetDependencyGraphOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/GetDependencyGraphOperation.cs:line 57
```

**Comment by jcagme** [comment]
Ack

**Comment by mmitche** [comment]
I've got this. The command is actually doing what it should, the ux is just not great.  It's bascially expecting that unless you specify --remote, it should only attempt to use local repositories to gather the graph.

This should be inverted so that the default is remote, with the initial set of dependencies from the local populated from the local repo.

**Comment by mmitche** [comment]
And improve the error case.

**Comment by mmitche** [comment]
Default behavior was confusing.  Fixed with gather drop command

**Comment by jcagme** [comment]
@mmitche this was fix IIRC, right?

**Comment by markwilkie** [comment]
fixed
