### ISSUE TITLE
darc update-dependencies errors out with System.ArgumentException: The personal access token is missing...

### ISSUE THREAD

**Issue by AdamYoblick** [dotnet/arcade#1623]
- Ran a fresh darc-init.ps1 to get the latest
- Ran darc update-dependencies
- Got the following error:
```
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Error: Failed to update dependencies to channel
System.ArgumentException: The personal access token is missing...
   at Microsoft.DotNet.DarcLib.Remote.ValidateSettings(DarcSettings settings) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs:line 479
   at Microsoft.DotNet.DarcLib.Remote..ctor(DarcSettings settings, ILogger logger) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs:line 26
   at Microsoft.DotNet.Darc.Operations.UpdateDependenciesOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateDependenciesOperation.cs:line 50
```

Note that passing in the PAT does NOT fix the issue.

**Comment by AdamYoblick** [comment]
Adding the github PAT to the darc authenticate file fixes this problem. :)
