### ISSUE TITLE
 Tool 'microsoft.dotnet.darc' failed to install. 

### ISSUE THREAD

**Issue by vijayrkn** [dotnet/arcade#1659]
```
2018-12-21T22:13:46.1568182Z STEP 2: Build using the local packages
2018-12-21T22:13:46.1616114Z Adding 'F:\vsagent\-containerSas\104\s\artifacts\validatesdk\packages\Release\NonShipping' to 'F:\vsagent\-containerSas\104\s\NuGet.config'...
2018-12-21T22:13:46.1844459Z 
2018-12-21T22:13:46.1980809Z Updating Dependencies using Darc...
2018-12-21T22:13:46.3877361Z Installing Darc CLI version 1.0.0-beta.18620.6...
2018-12-21T22:13:46.3884005Z You may need to restart your command window if this is the first dotnet tool you have installed.
2018-12-21T22:13:47.3783861Z   Restoring packages for C:\Users\vsagent\AppData\Local\Temp\kxq0oqyu.j2r\restore.csproj...
2018-12-21T22:13:47.4147810Z F:\vsagent\-containerSas\104\s\.dotnet\sdk\2.1.502\NuGet.targets(114,5): error : The local source 'F:\vsagent\-containerSas\104\s\artifacts\validatesdk\packages\Release\NonShipping' doesn't exist. [C:\Users\vsagent\AppData\Local\Temp\kxq0oqyu.j2r\restore.csproj]
2018-12-21T22:13:47.7630547Z The tool package could not be restored.
2018-12-21T22:13:47.7631052Z Tool 'microsoft.dotnet.darc' failed to install. This failure may have been caused by:
2018-12-21T22:13:47.7631225Z 
2018-12-21T22:13:47.7631490Z * You are attempting to install a preview release and did not use the --version option to specify the version.
2018-12-21T22:13:47.7631695Z * A package by this name was found, but it was not a .NET Core tool.
2018-12-21T22:13:47.7631940Z * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
2018-12-21T22:13:47.7632099Z * You mistyped the name of the tool.
2018-12-21T22:13:47.7818817Z The term 'C:\Users\vsagent\.dotnet\tools\darc.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2018-12-21T22:13:47.7840144Z System.Management.Automation.CommandNotFoundException: The term 'C:\Users\vsagent\.dotnet\tools\darc.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2018-12-21T22:13:47.7840695Z    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2018-12-21T22:13:47.7842394Z    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2018-12-21T22:13:47.7842935Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-12-21T22:13:47.7843452Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-12-21T22:13:47.7859719Z at <ScriptBlock>, F:\vsagent\-containerSas\104\s\eng\validate-sdk.ps1: line 85
2018-12-21T22:13:47.7860748Z at <ScriptBlock>, <No file>: line 1
```

**Comment by vijayrkn** [comment]
@mmitche - Is this an issue with newer version - 18620.6? Should I downgrade?

**Comment by jcagme** [comment]
Looks like this is failing in an official build? Could you please share the link to it?

**Comment by vijayrkn** [comment]
https://dnceng.visualstudio.com/internal/_build/results?buildId=62679

I removed the validation steps and now the official build succeeded.

**Comment by markwilkie** [comment]
@vijayrkn - is this still an issue for you?

**Comment by vijayrkn** [comment]
You can close this.
