### ISSUE TITLE
Publish to Azure DevOps Test explorer hits VstsServiceError: TF400813: The user '' is not authorized to access this resource

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/arcade#1752]
Started hitting this issue recently on Azure DevOps during running reporter\run.py on Helix machines (that published results to Test explorer)

Here is a log:
```
Main thread starting workers

Worker 0: starting...

Worker 1: starting...

Worker 2: starting...

Worker 3: starting...

Worker 4: starting...

Worker 5: starting...

Worker 6: starting...

Worker 7: starting...

Worker 8: starting...

Worker 9: starting...

Beginning reading of test results.

Searching 'C:\dotnetbuild\work\bc928cf9-2dd1-4bac-9766-d440810bd524\Work\b06b517f-70f5-4368-b216-d6ed24391fc9\Exec' for test results files

Found results file C:\dotnetbuild\work\bc928cf9-2dd1-4bac-9766-d440810bd524\Work\b06b517f-70f5-4368-b216-d6ed24391fc9\Exec\testResults.xml with format xunit

Uploading results in batches of size 1000

Main thread finished queueing batches

Worker 0: got error: Traceback (most recent call last):

  File "C:\dotnetbuild\work\bc928cf9-2dd1-4bac-9766-d440810bd524\Payload\reporter\run.py", line 39, in run

    self.__process(item)

  File "C:\dotnetbuild\work\bc928cf9-2dd1-4bac-9766-d440810bd524\Payload\reporter\run.py", line 30, in __process

    self.publisher.upload_batch(batch)

  File "C:\dotnetbuild\work\bc928cf9-2dd1-4bac-9766-d440810bd524\Payload\reporter\azure_devops_result_publisher.py", line 35, in upload_batch

    self.publish_results(test_case_results, results_with_attachments)

  File "C:\dotnetbuild\work\bc928cf9-2dd1-4bac-9766-d440810bd524\Payload\reporter\azure_devops_result_publisher.py", line 48, in publish_results

    published_results = test_client.add_test_results_to_test_run(list(test_case_results), self.team_project, self.test_run_id)  # type: List[TestCaseResult]

  File "C:\Users\runner\.vsts-env\lib\site-packages\vsts\test\v4_1\test_client.py", line 1161, in add_test_results_to_test_run

    returns_collection=True)

  File "C:\Users\runner\.vsts-env\lib\site-packages\vsts\vss_client.py", line 96, in _send

    response = self._send_request(request=request, headers=headers, content=content)

  File "C:\Users\runner\.vsts-env\lib\site-packages\vsts\vss_client.py", line 63, in _send_request

    self._handle_error(request, response)

  File "C:\Users\runner\.vsts-env\lib\site-packages\vsts\vss_client.py", line 239, in _handle_error

    raise VstsServiceError(wrapped_exception)

VstsServiceError: TF400813: The user '' is not authorized to access this resource.



Main thread exiting
```

This is one of the builds where I saw this happening 
https://dnceng.visualstudio.com/public/_build/results?buildId=68868

As a result of this issue, only few test jobs published their results to Azure DevOps Test explorer.

By the way, from the log I can see that System.AccessToken has been passed successfully to the script.

@alexperovich

**Comment by markwilkie** [comment]
@alexperovich - any update here?

**Comment by alexperovich** [comment]
I didn't see this before. I haven't seen this specific error before. @echesakovMSFT Can you give me the specific build leg and work item that had this problem?

**Comment by echesakovMSFT** [comment]
I should tell that I have seen this happening only once. For example, https://mc.dot.net/#/user/4ae9b87d-f80b-4977-8984-b4c67c7cd398/pr~2Fdotnet~2Fcoreclr~2Frefs~2Fpull~2F2~2Fmerge/test~2Ffunctional~2Fcli~2Fpri0/20190108.76/workItem/baseservices.compilerservices/wilogs Windows.10.Amd64.Open-x86:Checked (Job 487d97e5-fbf9-451b-8ff6-38548c751255)

The next submission (after I opened this issue) went fine. You can close this issue if you want - if it happens again I'll re-open it.

**Comment by alexperovich** [comment]
Okay, ping me if it happens again.
