### ISSUE TITLE
Cannot diagnose test failures on CI - xUnit test failures are published, but still do not appear in Azure Pipelines test results

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#1909]
Just converted https://github.com/aspnet/Extensions to Arcade, and now we cannot see test failures in Azure Pipelines.

Example: https://dev.azure.com/dnceng/public/_build/results?buildId=83148&view=logs

The console log shows which test project failed, but not which test:
![image](https://user-images.githubusercontent.com/2696087/52000712-9b300d00-2472-11e9-8345-e91b4ce61f28.png)

The test tab in VSTS shows tests were run, but does not show any failures.

![image](https://user-images.githubusercontent.com/2696087/52000760-b7cc4500-2472-11e9-801a-185358c55c5a.png)

Publishing test results is enabled for this repo:
![image](https://user-images.githubusercontent.com/2696087/52000780-c74b8e00-2472-11e9-9e50-5865badc317a.png)
https://github.com/aspnet/Extensions/blob/f41cfded3c12eec0efea89ece1dafe43afa9c6b8/azure-pipelines.yml#L22

**Comment by tmat** [comment]
Not sure why the  xunit runner did not produced test results. The log file is available in the log artifacts for the build. At the bottom you can see the command line passed to the test runner, which includes xml test results:
```
-xml "F:\vsagent\19\s\artifacts\TestResults\Debug\Microsoft.Extensions.Hosting.Tests_netcoreapp3.0_x64.xml"
```

```
xUnit.net Console Runner v2.4.0 (64-bit .NET Core 4.6.27322.0)
  Discovering: Microsoft.Extensions.Hosting.Tests
  Discovered:  Microsoft.Extensions.Hosting.Tests
  Starting:    Microsoft.Extensions.Hosting.Tests
info: Microsoft.Extensions.Hosting.HostTests[0]
      Request starting
Assertion Failed

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.CaptureDisposable(Object service) in /_/src/DependencyInjection/DI/src/ServiceLookup/ServiceProviderEngineScope.cs:line 44
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite scopedCallSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType) in /_/src/DependencyInjection/DI/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 90
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context) in /_/src/DependencyInjection/DI/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 52
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument) in /_/src/DependencyInjection/DI/src/ServiceLookup/CallSiteVisitor.cs:line 25
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context) in /_/src/DependencyInjection/DI/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 34
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument) in /_/src/DependencyInjection/DI/src/ServiceLookup/CallSiteVisitor.cs:line 46
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite scopedCallSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType) in /_/src/DependencyInjection/DI/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 84
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context) in /_/src/DependencyInjection/DI/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 52
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument) in /_/src/DependencyInjection/DI/src/ServiceLookup/CallSiteVisitor.cs:line 25
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context) in /_/src/DependencyInjection/DI/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 34
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument) in /_/src/DependencyInjection/DI/src/ServiceLookup/CallSiteVisitor.cs:line 46
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite scopedCallSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType) in /_/src/DependencyInjection/DI/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 84
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context) in /_/src/DependencyInjection/DI/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 52
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument) in /_/src/DependencyInjection/DI/src/ServiceLookup/CallSiteVisitor.cs:line 25
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context) in /_/src/DependencyInjection/DI/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 34
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument) in /_/src/DependencyInjection/DI/src/ServiceLookup/CallSiteVisitor.cs:line 46
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite scopedCallSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType) in /_/src/DependencyInjection/DI/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 84
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context) in /_/src/DependencyInjection/DI/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 52
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument) in /_/src/DependencyInjection/DI/src/ServiceLookup/CallSiteVisitor.cs:line 25
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope) in /_/src/DependencyInjection/DI/src/ServiceLookup/CallSiteRuntimeResolver.cs:line 11
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ILEmitResolverBuilder.Build(ServiceCallSite callSite) in /_/src/DependencyInjection/DI/src/ServiceLookup/ILEmit/ILEmitResolverBuilder.cs:line 69
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CompiledServiceProviderEngine.RealizeService(ServiceCallSite callSite) in /_/src/DependencyInjection/DI/src/ServiceLookup/CompiledServiceProviderEngine.cs:line 28
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>n__0(ServiceCallSite callSite)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__1() in /_/src/DependencyInjection/DI/src/ServiceLookup/DynamicServiceProviderEngine.cs:line 24
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
=== COMMAND LINE ===
"F:\vsagent\19\s\.dotnet\dotnet.exe" exec --depsfile "F:\vsagent\19\s\artifacts\bin\Microsoft.Extensions.Hosting.Tests\Debug\netcoreapp3.0\Microsoft.Extensions.Hosting.Tests.deps.json" --runtimeconfig "F:\vsagent\19\s\artifacts\bin\Microsoft.Extensions.Hosting.Tests\Debug\netcoreapp3.0\Microsoft.Extensions.Hosting.Tests.runtimeconfig.json" "F:\vsagent\19\s\.packages\xunit.runner.console/2.4.0/tools/netcoreapp2.0/xunit.console.dll" "F:\vsagent\19\s\artifacts\bin\Microsoft.Extensions.Hosting.Tests\Debug\netcoreapp3.0\Microsoft.Extensions.Hosting.Tests.dll" -noautoreporters -xml "F:\vsagent\19\s\artifacts\TestResults\Debug\Microsoft.Extensions.Hosting.Tests_netcoreapp3.0_x64.xml" -html "F:\vsagent\19\s\artifacts\TestResults\Debug\Microsoft.Extensions.Hosting.Tests_netcoreapp3.0_x64.html"  > "F:\vsagent\19\s\artifacts\log\Debug\Microsoft.Extensions.Hosting.Tests_netcoreapp3.0_x64.log" 2>&1
```

**Comment by natemcmaster** [comment]
Yeah, it's weird. The publish test results task shows that it found the .xml file, and successful tests show up. I wonder if this is another result of behavior differences between xunit.runner.visualstudio and xunit.runner.console. Before converting to Arcade, we were running tests with `dotnet vstest`. This problem started happening when switching to Arcade, which I believe is still using xunit.runner.console.

**Comment by natemcmaster** [comment]
Closing as an issue in aspnet code. It looks like what happens is that `Debug.Assert` crashes the xunit process, so there is no test result file written to disk.
