### ISSUE TITLE
Native tools onboarding  - failures during unzipping

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/arcade#2078]
We have a copy of Strawberry Perl uploaded to the Azure storage blob as part of the native onboarding process. We consume this by specifying the version in `global.json` like this:

```
 "native-tools": {
    "strawberry-perl": "5.28.0.1"
  }
```

In addition to this, we also have this in `eng\init-native-tools.ps1`:
```
#
# This file should be kept in sync across https://www.github.com/dotnet/wpf and dotnet-wpf-int repos. 
#

. $PsScriptRoot\common\init-tools-native.ps1 -InstallDirectory $PSScriptRoot\..\.tools\native -GlobalJsonFile $PSScriptRoot\..\global.json
```

This has been working well for us until lately. 

Recently, I've started noticing [errors ](https://dnceng.visualstudio.com/internal/_build/results?buildId=102015) like this:

```
Processing E:\A\_work\1\s\eng\..\global.json
File 'C:\Users\vsagent\.netcoreeng\native\temp\strawberry-perl-5.28.1.1-win64-x64.zip' already exists, skipping download
Exception calling "ExtractToDirectory" with "2" argument(s): "End of Central Directory record could not be found."
System.Management.Automation.MethodInvocationException: Exception calling "ExtractToDirectory" with "2" argument(s): "End of Central Directory record could not be found." ---> System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   at CallSite.Target(Closure , CallSite , Type , String , String )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[error]CommonLibrary\DownloadAndExtract : Unzip failed
##[error]At E:\A\_work\1\s\eng\common\native\install-tool.ps1:88 char:22
+     $InstallStatus = CommonLibrary\DownloadAndExtract -Uri $Uri `
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException

##[error]    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DownloadAndExtract

##[error] 
```

These errors are transient, and they seem to come and go. They affect CI builds the most (as against local/dev builds), which is unfortunate. 

I tried to create a new version of these packages and uploaded them (5.28.1.1), and validated that their MIME shows up in _Azure Storage Explorer_ correctly as `application/x-zip-compressed`. When these arel downloaded locally, they seem to be valid zip files with no problems whatsoever. 

What's the next best step here to troubleshoot the problem and get this to work more reliably? 

/cc @MattGal, @chcosta, @riarenas 
/cc @danzil

**Comment by riarenas** [comment]
Would you mind linking some of the builds where you are seeing this? Hoping it will let us narrow the problem down to see which pool, and which agent the builds that fail are running on.

**Comment by riarenas** [comment]
I found some additional failures:
https://dnceng.visualstudio.com/internal/_build/results?buildId=100976
https://dnceng.visualstudio.com/internal/_build/results?buildId=101958
https://dnceng.visualstudio.com/internal/_build/results?buildId=99987

It looks like it's specific to the dotnet-internal-vs2019-preview agent pool

**Comment by vatsan-madhavan** [comment]
You are right - it seems that pool is where the failures are happening.

**Comment by riarenas** [comment]
Moving this to core-eng so that first responders can take a look.

We should probably start by looking at the machines where this has been failing, and try to find why the machine ended up in that state.
