### ISSUE TITLE
run tests with -nocolor option in CI

### ISSUE THREAD

**Issue by wfurt** [dotnet/arcade#2098]
I was recently investigating some test failures like https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190222.1/workItem/System.Net.Ping.Functional.Tests/wilogs

```
~/dotnetbuild/work/4d1f03a2-8a44-4da6-b448-df041fe2cf02/Work/15c6cbee-44ce-42e3-b2bf-ce88affa07a5/Exec ~/dotnetbuild/work/4d1f03a2-8a44-4da6-b448-df041fe2cf02/Work/15c6cbee-44ce-42e3-b2bf-ce88affa07a5/Exec
[37m  Discovering: System.Net.Ping.Functional.Tests (method display = ClassAndMethod, method display options = None)
[m[37m  Discovered:  System.Net.Ping.Functional.Tests (found 38 of 46 test cases)
[m[37m  Starting:    System.Net.Ping.Functional.Tests (parallel test collections = on, max threads = 2)
[m[31;1m    System.Net.NetworkInformation.Tests.PingTest.SendPingToExternalHostWithLowTtlTest [FAIL]
[m[37m      System.Net.NetworkInformation.PingException : An exception occurred during a Ping request.
[m[37m      ---- System.InvalidOperationException : Cannot process request because the process (3040) has exited.
[m[30;1m      Stack Trace:
[m[37m        /__w/1/s/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.cs(408,0): at System.Net.NetworkInformation.Ping.GetAddressAndSendAsync(String hostNameOrAddress, Int32 timeout, Byte[] buffer, PingOptions options)
[m[37m        /__w/1/s/src/System.Net.Ping/tests/FunctionalTests/PingTest.cs(797,0): at System.Net.NetworkInformation.Tests.PingTest.SendPingToExternalHostWithLowTtlTest()
[m[37m        --- End of stack trace from previous location where exception was thrown ---
[m[37m        ----- Inner Stack Trace -----
[m[37m        /__w/1/s/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs(321,0): at System.Diagnostics.Process.ThrowIfExited(Boolean refresh)
[m[37m        /__w/1/s/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs(932,0): at System.Diagnostics.Process.EnsureState(State state)
[m[37m        /__w/1/s/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs(61,0): at System.Diagnostics.Process.Kill()
[m[37m        /__w/1/s/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.Unix.cs(334,0): at System.Net.NetworkInformation.Ping.SendWithPingUtilityAsync(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
[m[37m        /__w/1/s/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.Unix.cs(48,0): at System.Net.NetworkInformation.Ping.SendPingAsyncCore(IPAddress address, Byte[
```

You may notice the garbage characters on each line. 
They are ANSI color sequences and they have absolutely no use when  stdout is not tty terminal.  

With new XUnit, there is -nocolor option  we should always use when redirecting test output.

**Comment by wfurt** [comment]
This seems to be broken again after transition to runtime.
https://helix.dot.net/api/2019-06-17/jobs/d7ac50f0-b476-4df4-8040-3defb4944a85/workitems/System.Runtime.Tests/console

```
+ ./RunTests.sh --runtime-path /home/helixbot/work/d7ac50f0-b476-4df4-8040-3defb4944a85/Payload
----- start Tue Dec 3 05:24:43 UTC 2019 =============== To repro directly: =====================================================
pushd .
/home/helixbot/work/d7ac50f0-b476-4df4-8040-3defb4944a85/Payload/dotnet exec --runtimeconfig System.Runtime.Tests.runtimeconfig.json --depsfile System.Runtime.Tests.deps.json xunit.console.dll System.Runtime.Tests.dll -xml testResults.xml -nologo -trait category=OuterLoop -notrait category=failing -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests 
popd
===========================================================================================================
~/work/d7ac50f0-b476-4df4-8040-3defb4944a85/Work/cdd098db-2a70-4c59-9a65-6ae04339a307/Exec ~/work/d7ac50f0-b476-4df4-8040-3defb4944a85/Work/cdd098db-2a70-4c59-9a65-6ae04339a307/Exec
[37m  Discovering: System.Runtime.Tests (method display = ClassAndMethod, method display options = None)
[m[37m  Discovered:  System.Runtime.Tests (found 24 of 5420 test cases)
[m[37m  Starting:    System.Runtime.Tests (parallel test collections = on, max threads = 2)
[m[31;1m    System.Tests.ArrayTests.Copy_LargeMultiDimensionalArray [FAIL]
[m[37m      System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
[m[30;1m      Stack Trace:
[m[37m        /_/src/libraries/System.Runtime/tests/System/ArrayTests.cs(1332,0): at System.Tests.ArrayTests.Copy_LargeMultiDimensionalArray()
[m[37m  Finished:    System.Runtime.Tests
[m[37m=== TEST EXECUTION SUMMARY ===
[m[37m   System.Runtime.Tests  Total: 34, Errors: 0, Failed: 1, Skipped: 0, Time: 10.823s
[m[m~/work/d7ac50f0-b476-4df4-8040-3defb4944a85/Work/cdd098db-2a70-4c59-9a65-6ae04339a307/Exec
----- end Tue Dec 3 05:24:56 UTC 2019 ----- exit code 1 ----------------------------------------------------------

```

cc: @safern @ViktorHofer

**Comment by safern** [comment]
It seems like the `ArchiveTest` property is no longer being defined: https://github.com/dotnet/runtime/search?q=ArchiveTest&unscoped_q=ArchiveTest

The ArchiveTests logic was changed here: https://github.com/dotnet/runtime/commit/1d5de1533ad35b39f776701c4d22b68a3def2dd8

@ViktorHofer it seems like some projects set that property as well to avoid sending them to helix, so if we want to keep that we wouldn't be able to use the `ArchiveTests` property since that is passed as a global parameter.

**Comment by ViktorHofer** [comment]
This code doesn't live in Arcade any longer. Moving the issue to dotnet/runtime.
