### ISSUE TITLE
PushToBlobFeed needs a retry mechanism

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#2557]
Frequently official builds in corefx fail when publishing test assets to the blob feed via the PushToBlobFeed task. I believe there is no retry mechanism currently enabled for that task.

```
/__w/1/s/eng/publish.proj(129,5): error : Unable to upload to corefx-tests/4.6.0-preview5.19216.1/Linux.x64/netcoreapp/tests/AnyOS.AnyCPU.Release/System.Xml.RW.XmlWriter.Tests.zip due to System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
/__w/1/s/eng/publish.proj(129,5): error :    --- End of inner exception stack trace ---
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.HttpConnection.FillAsync()
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): error :    --- End of inner exception stack trace ---
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
/__w/1/s/eng/publish.proj(129,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.BlobFeed.CheckIfBlobExistsAsync(String blobPath) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/BlobFeed.cs:line 68
/__w/1/s/eng/publish.proj(129,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.BlobFeedAction.UploadAssetAsync(ITaskItem item, SemaphoreSlim clientThrottle, Int32 uploadTimeout, PushOptions options) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/BlobFeedAction.cs:line 216.
/__w/1/s/eng/publish.proj(129,5): error : The operation was canceled.
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
/__w/1/s/eng/publish.proj(129,5): error :    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
/__w/1/s/eng/publish.proj(129,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.BlobFeed.CheckIfBlobExistsAsync(String blobPath) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/BlobFeed.cs:line 68
/__w/1/s/eng/publish.proj(129,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.BlobFeedAction.UploadAssetAsync(ITaskItem item, SemaphoreSlim clientThrottle, Int32 uploadTimeout, PushOptions options) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/BlobFeedAction.cs:line 216
/__w/1/s/eng/publish.proj(129,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.BlobFeedAction.PublishToFlatContainerAsync(IEnumerable`1 taskItems, Int32 maxClients, Int32 uploadTimeoutInMinutes, PushOptions pushOptions) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/BlobFeedAction.cs:line 121
/__w/1/s/eng/publish.proj(129,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.PushToBlobFeed.ExecuteAsync() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PushToBlobFeed.cs:line 118

Build FAILED.
```

https://dnceng.visualstudio.com/internal/_build/results?buildId=157045&view=logs&jobId=7cc86366-6ece-5781-60ca-3d1c814b1449&taskId=1784d3c0-5471-5984-5cfd-eb7f4c6004e8&lineStart=241&lineEnd=242&colStart=1&colEnd=1

cc @Chrisboh

**Comment by JohnTortugo** [comment]
We have some issues on the backlog to work on that already:

https://github.com/dotnet/arcade/issues/563
https://github.com/dotnet/arcade/issues/2057

and we are also in the process of redesigning the publishing flow: https://github.com/dotnet/arcade/issues/1179

I'll close this issue but if you feel like the other issues don't cover the problem feel free to re-open it. Thanks

**Comment by markwilkie** [comment]
It's probably also worth noting that this work was originally slated to be done by P5.  @JohnTortugo - do you know if #563 is still tracking?

cc/ @Chrisboh

**Comment by JohnTortugo** [comment]
We should definitely work on #563. If time allows I'll see to get it done before P5..

**Comment by ViktorHofer** [comment]
We discussed this in our last CI Council meeting with SteveC. This is one of the reasons why official builds are randomly failing. I'm ok if https://github.com/dotnet/arcade/issues/563 tracks this already. Let's prioritize this accordingly as I'm sure nobody want's flaky builds in the release/3.0 branch.
