### ISSUE TITLE
Reporting xUnit tests results to AzDO Tests Explorer is broken on Linux x64

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/arcade#2759]
Reporting xUnit tests results is broken on Linux x64:
https://mc.dot.net/#/user/coreclr-ci/pr~2Fdotnet~2Fcoreclr~2Frefs~2Fpull~2F24554~2Fmerge/test~2Ffunctional~2Fcli~2F/20190513.718/workItem/PayloadGroup0/wilogs
```
2019-05-13T22:02:21Z
+ /home/helixbot/.vsts-env/bin/python /home/helixbot/work/2aacd476-35e3-4605-9309-088d644680c4/Payload/reporter/run.py https://dev.azure.com/dnceng/ public 4525536 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJlNDI4NWM4Yy0zZmQ1LTQyNjctOWIxYy00MjE5NWM0N2E1NTMiLCJzY3AiOiJsb2NhdGlvbnNlcnZpY2UuY29ubmVjdCByZWFkYW5kcHVibGlzaHRlc3Q6OWVlNmQ0NzgtZDI4OC00N2Y3LWFhY2MtZjZlNmQwODJhZTZkIHJlYWRhbmR1cGRhdGVidWlsZGJ5dXJpOjllZTZkNDc4LWQyODgtNDdmNy1hYWNjLWY2ZTZkMDgyYWU2ZC9kb3RuZXQvY29yZWNsci8yMjg6YnVpbGQvYnVpbGQvMTg3NzY1IiwiYXVpIjoiNTlhZTI1N2MtYzY4My00ZDhlLWI4MTctZGU5YjkwMjZiYWYyIiwic2lkIjoiZTUyOThiYjQtYjU1OC00NzE0LWI1NDYtN2NhZjI1NjM3MmE5IiwiaXNzIjoiYXBwLnZzdG9rZW4udmlzdWFsc3R1ZGlvLmNvbSIsImF1ZCI6ImFwcC52c3Rva2VuLnZpc3VhbHN0dWRpby5jb218dnNvOmI1NWRlNGVkLTRiNWEtNDIxNS1hOGU0LTBhMGE1ZjcxZTdkOCIsIm5iZiI6MTU1Nzc4MTYyMywiZXhwIjoxNTU3Nzk3MjIzfQ.Egffj6Srw_6x9HBecHGrqasUhMUVvzSSc-X3s987NOU-uCrA8KUNW5XsbAk4skIOUnmDZ4xevSJ8I_VPbA9s7I4fsr4DW7UT3tSGUCM7M-MJ3_DiQmBYPzTNxaVkUr2r9J9CjjS3uAIxCL3wzBAmiJuxiOW5u2AswN2-OEt5T3MBFTT3Pn1_RpKsvkSxsJhGUOlLbHMXuqBpBnEsCknL4fvjN40CRSdat5O_exYE5FdRJ9J23t-zCQpmCcn3_qCeWnp_0ryCv2Kn6-wnwUy4oQTI3F47cCjCy0ma2MXxsjJmY0V6FUOqQrB4DVt1h8D89mXOztd36k_UN0u-C2gAqA
Got args https://dev.azure.com/dnceng/ public 4525536 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJlNDI4NWM4Yy0zZmQ1LTQyNjctOWIxYy00MjE5NWM0N2E1NTMiLCJzY3AiOiJsb2NhdGlvbnNlcnZpY2UuY29ubmVjdCByZWFkYW5kcHVibGlzaHRlc3Q6OWVlNmQ0NzgtZDI4OC00N2Y3LWFhY2MtZjZlNmQwODJhZTZkIHJlYWRhbmR1cGRhdGVidWlsZGJ5dXJpOjllZTZkNDc4LWQyODgtNDdmNy1hYWNjLWY2ZTZkMDgyYWU2ZC9kb3RuZXQvY29yZWNsci8yMjg6YnVpbGQvYnVpbGQvMTg3NzY1IiwiYXVpIjoiNTlhZTI1N2MtYzY4My00ZDhlLWI4MTctZGU5YjkwMjZiYWYyIiwic2lkIjoiZTUyOThiYjQtYjU1OC00NzE0LWI1NDYtN2NhZjI1NjM3MmE5IiwiaXNzIjoiYXBwLnZzdG9rZW4udmlzdWFsc3R1ZGlvLmNvbSIsImF1ZCI6ImFwcC52c3Rva2VuLnZpc3VhbHN0dWRpby5jb218dnNvOmI1NWRlNGVkLTRiNWEtNDIxNS1hOGU0LTBhMGE1ZjcxZTdkOCIsIm5iZiI6MTU1Nzc4MTYyMywiZXhwIjoxNTU3Nzk3MjIzfQ.Egffj6Srw_6x9HBecHGrqasUhMUVvzSSc-X3s987NOU-uCrA8KUNW5XsbAk4skIOUnmDZ4xevSJ8I_VPbA9s7I4fsr4DW7UT3tSGUCM7M-MJ3_DiQmBYPzTNxaVkUr2r9J9CjjS3uAIxCL3wzBAmiJuxiOW5u2AswN2-OEt5T3MBFTT3Pn1_RpKsvkSxsJhGUOlLbHMXuqBpBnEsCknL4fvjN40CRSdat5O_exYE5FdRJ9J23t-zCQpmCcn3_qCeWnp_0ryCv2Kn6-wnwUy4oQTI3F47cCjCy0ma2MXxsjJmY0V6FUOqQrB4DVt1h8D89mXOztd36k_UN0u-C2gAqA
Main thread starting workers
Worker 0: starting...
Worker 1: starting...
Worker 2: starting...
Worker 3: starting...
Worker 4: starting...
Worker 5: starting...
Worker 6: starting...
Worker 7: starting...
Worker 8: starting...
Worker 9: starting...
Beginning reading of test results.
Uploading results in batches of size 1000
Searching '/home/helixbot/work/2aacd476-35e3-4605-9309-088d644680c4/Work/13f5408e-1bb3-4335-b55b-eaf068ba88d8/Exec/..' for log files
Found log '/home/helixbot/work/2aacd476-35e3-4605-9309-088d644680c4/Work/13f5408e-1bb3-4335-b55b-eaf068ba88d8/Exec/../console.5ccdf8cc.log'
Uri 'https://helixexternalresults.blob.core.windows.net/dotnet-coreclr-refs-pull-24554-merge-2aacd47635e3460593/PayloadGroup0/console.5ccdf8cc.log?sv=2017-07-29&sr=c&sig=yFjaDlTTu%2FIvJMOHcjc1qHnXGcB62Ih0VNA7Sb19ycA%3D&se=2019-05-23T21%3A38%3A41Z&sp=rl'
Generated log list: <ul><li><a href='https://helixexternalresults.blob.core.windows.net/dotnet-coreclr-refs-pull-24554-merge-2aacd47635e3460593/PayloadGroup0/console.5ccdf8cc.log?sv=2017-07-29&sr=c&sig=yFjaDlTTu%2FIvJMOHcjc1qHnXGcB62Ih0VNA7Sb19ycA%3D&se=2019-05-23T21%3A38%3A41Z&sp=rl' target='_blank'>console.5ccdf8cc.log</a></li></ul>
Searching '/home/helixbot/work/2aacd476-35e3-4605-9309-088d644680c4/Work/13f5408e-1bb3-4335-b55b-eaf068ba88d8/Exec' for test results files
Found results file /home/helixbot/work/2aacd476-35e3-4605-9309-088d644680c4/Work/13f5408e-1bb3-4335-b55b-eaf068ba88d8/Exec/testResults.xml with format xunit
Main thread finished queueing batches
Worker 0: got error: Traceback (most recent call last):
  File "/home/helixbot/work/2aacd476-35e3-4605-9309-088d644680c4/Payload/reporter/run.py", line 39, in run
    self.__process(item)
  File "/home/helixbot/work/2aacd476-35e3-4605-9309-088d644680c4/Payload/reporter/run.py", line 30, in __process
    self.publisher.upload_batch(batch)
  File "/home/helixbot/work/2aacd476-35e3-4605-9309-088d644680c4/Payload/reporter/azure_devops_result_publisher.py", line 36, in upload_batch
    self.publish_results(test_case_results, results_with_attachments)
  File "/home/helixbot/work/2aacd476-35e3-4605-9309-088d644680c4/Payload/reporter/azure_devops_result_publisher.py", line 57, in publish_results
    stream=base64.b64encode(text(attachment.text)),
  File "/home/helixbot/.vsts-env/lib/python3.6/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'

Main thread exiting
```

@alexperovich @sandreenko

**Comment by markwilkie** [comment]
@MattGal  - is this FR?

**Comment by MattGal** [comment]
@markwilkie  If it's still an issue yes, I think we already fixed this though.  I'll investigate and update.

**Comment by MattGal** [comment]
Ah I missed the date;  this was from the time when we moved the machines from Python 2 to 3 and while the Helix Arcade SDK had been updated, it wasn't in CoreCLR yet.  

All recent runs, such as https://mc.dot.net/#/user/coreclr-ci/pr~2Fdotnet~2Fcoreclr~2Frefs~2Fpull~2F24829~2Fmerge/test~2Ffunctional~2Fcli~2F/20190529.9 are good, so I'm closing this;  @echesakovMSFT please reactivate if I am mistaken.

**Comment by echesakovMSFT** [comment]
I don't think the issue has been fixed 

Ubuntu.1604.Amd64.Open-x64:Checked-gcstress0x3 
Details from Job b6c6e7c9-d7b3-4c65-bc6b-bc0852fcdac7
ExitCode: 1 
Ran on Machine: a0028DZ 
```
+ date -u +%FT%TZ
2019-05-29T10:24:31Z
+ /home/helixbot/.vsts-env/bin/python /home/helixbot/work/b6c6e7c9-d7b3-4c65-bc6b-bc0852fcdac7/Payload/reporter/run.py https://dev.azure.com/dnceng/ public 4944334 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJlNDI4NWM4Yy0zZmQ1LTQyNjctOWIxYy00MjE5NWM0N2E1NTMiLCJzY3AiOiJhcHBfdG9rZW4iLCJhdWkiOiJlYTlkYjdiYS1hZjgwLTRhNDMtOWViYi02YTAwOTYzMWNmODYiLCJzaWQiOiI5MmRmY2M4OS03NDI4LTQ3NmMtOGYwMy1jNWFhMDhmNmQxZjQiLCJpc3MiOiJhcHAudnN0b2tlbi52aXN1YWxzdHVkaW8uY29tIiwiYXVkIjoiYXBwLnZzdG9rZW4udmlzdWFsc3R1ZGlvLmNvbXx2c286YjU1ZGU0ZWQtNGI1YS00MjE1LWE4ZTQtMGEwYTVmNzFlN2Q4IiwibmJmIjoxNTU5MTEyNTUyLCJleHAiOjE1NTkxNDI1NTJ9.mXp17WGRiSRiXUKFacaxlTJEFK2KE_bOgRtTCYVGOjmXHtXq-xmgS4aYAuR-W4KSOlFw_iFbLqXzIRzjkUWE6g1NBUhU8criCNlDjvDoThR7J9z1pmHwiDMlt8sQdaKXVCKJ2r6FBbn9e3ltbPqS2_uC6c3ZX0bdGV42S2Lp1o1FXJ7-PinT3KT-JJb_9FZij0_flKv6OYeWE3cQnpJVqjNV1MMD0BuABfcMqNTkhUhjdnAlCtexv1b0y4quE4bC9zoPqp3DFwi_V3xYQTXPTfqmnijpk9ppPlVjMyWwueuPNFeb9xDe_VP-z_PeK5upO5U-Ya46D51w9Yp7WYaFuA
Got args https://dev.azure.com/dnceng/ public 4944334 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJlNDI4NWM4Yy0zZmQ1LTQyNjctOWIxYy00MjE5NWM0N2E1NTMiLCJzY3AiOiJhcHBfdG9rZW4iLCJhdWkiOiJlYTlkYjdiYS1hZjgwLTRhNDMtOWViYi02YTAwOTYzMWNmODYiLCJzaWQiOiI5MmRmY2M4OS03NDI4LTQ3NmMtOGYwMy1jNWFhMDhmNmQxZjQiLCJpc3MiOiJhcHAudnN0b2tlbi52aXN1YWxzdHVkaW8uY29tIiwiYXVkIjoiYXBwLnZzdG9rZW4udmlzdWFsc3R1ZGlvLmNvbXx2c286YjU1ZGU0ZWQtNGI1YS00MjE1LWE4ZTQtMGEwYTVmNzFlN2Q4IiwibmJmIjoxNTU5MTEyNTUyLCJleHAiOjE1NTkxNDI1NTJ9.mXp17WGRiSRiXUKFacaxlTJEFK2KE_bOgRtTCYVGOjmXHtXq-xmgS4aYAuR-W4KSOlFw_iFbLqXzIRzjkUWE6g1NBUhU8criCNlDjvDoThR7J9z1pmHwiDMlt8sQdaKXVCKJ2r6FBbn9e3ltbPqS2_uC6c3ZX0bdGV42S2Lp1o1FXJ7-PinT3KT-JJb_9FZij0_flKv6OYeWE3cQnpJVqjNV1MMD0BuABfcMqNTkhUhjdnAlCtexv1b0y4quE4bC9zoPqp3DFwi_V3xYQTXPTfqmnijpk9ppPlVjMyWwueuPNFeb9xDe_VP-z_PeK5upO5U-Ya46D51w9Yp7WYaFuA
Main thread starting workers
Worker 0: starting...
Worker 1: starting...
Worker 2: starting...
Worker 3: starting...
Worker 4: starting...
Worker 5: starting...
Worker 6: starting...
Worker 7: starting...
Worker 8: starting...
Worker 9: starting...
Beginning reading of test results.
Uploading results in batches of size 1000
Searching '/home/helixbot/work/b6c6e7c9-d7b3-4c65-bc6b-bc0852fcdac7/Work/86a96a10-b108-408b-b9de-98ffbc9e732f/Exec/..' for log files
Found log '/home/helixbot/work/b6c6e7c9-d7b3-4c65-bc6b-bc0852fcdac7/Work/86a96a10-b108-408b-b9de-98ffbc9e732f/Exec/../console.f062c8fb.log'
Uri 'https://helixexternalresults.blob.core.windows.net/dotnet-coreclr-refs-pull-24826-head-b6c6e7c9d7b34c65bc/baseservices.threading/console.f062c8fb.log?sv=2017-07-29&sr=c&sig=QJmi7XckUxt8Zi10LdKl0mc7T5AHL1YvewNew65FiY0%3D&se=2019-06-08T07%3A55%3A07Z&sp=rl'
Generated log list: <ul><li><a href='https://helixexternalresults.blob.core.windows.net/dotnet-coreclr-refs-pull-24826-head-b6c6e7c9d7b34c65bc/baseservices.threading/console.f062c8fb.log?sv=2017-07-29&sr=c&sig=QJmi7XckUxt8Zi10LdKl0mc7T5AHL1YvewNew65FiY0%3D&se=2019-06-08T07%3A55%3A07Z&sp=rl' target='_blank'>console.f062c8fb.log</a></li></ul>
Searching '/home/helixbot/work/b6c6e7c9-d7b3-4c65-bc6b-bc0852fcdac7/Work/86a96a10-b108-408b-b9de-98ffbc9e732f/Exec' for test results files
Found results file /home/helixbot/work/b6c6e7c9-d7b3-4c65-bc6b-bc0852fcdac7/Work/86a96a10-b108-408b-b9de-98ffbc9e732f/Exec/testResults.xml with format xunit
Main thread finished queueing batches
Worker 0: got error: Traceback (most recent call last):
  File "/home/helixbot/work/b6c6e7c9-d7b3-4c65-bc6b-bc0852fcdac7/Payload/reporter/run.py", line 39, in run
    self.__process(item)
  File "/home/helixbot/work/b6c6e7c9-d7b3-4c65-bc6b-bc0852fcdac7/Payload/reporter/run.py", line 30, in __process
    self.publisher.upload_batch(batch)
  File "/home/helixbot/work/b6c6e7c9-d7b3-4c65-bc6b-bc0852fcdac7/Payload/reporter/azure_devops_result_publisher.py", line 36, in upload_batch
    self.publish_results(test_case_results, results_with_attachments)
  File "/home/helixbot/work/b6c6e7c9-d7b3-4c65-bc6b-bc0852fcdac7/Payload/reporter/azure_devops_result_publisher.py", line 57, in publish_results
    stream=base64.b64encode(text(attachment.text)),
  File "/home/helixbot/.vsts-env/lib/python3.5/base64.py", line 59, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: a bytes-like object is required, not 'str'

Main thread exiting
+ date -u +%FT%TZ
2019-05-29T10:24:33Z
+ /usr/bin/python3 /home/helixbot/work/b6c6e7c9-d7b3-4c65-bc6b-bc0852fcdac7/Payload/xunit-reporter.py
2019-05-29 10:24:34,149: INFO: xunit-reporter(72): main: Uploading results from /home/helixbot/work/b6c6e7c9-d7b3-4c65-bc6b-bc0852fcdac7/Work/86a96a10-b108-408b-b9de-98ffbc9e732f/Exec/testResults.xml
2019-05-29 10:24:34,149: INFO: azure_storage(192): _upload: Uploading single blob: 'testResults.xml'
2019-05-29 10:24:34,197: INFO: saferequests(87): request_with_retry: Response complete with status code '201'
2019-05-29 10:24:34,198: INFO: xunit-reporter(86): main: Sending completion event
2019-05-29 10:24:34,198: INFO: event(44): send: Sending event type XUnitTestResult
2019-05-29 10:24:34,422: INFO: saferequests(87): request_with_retry: Response complete with status code '201'
+ exit 1
```
https://mc.dot.net/#/user/coreclr-outerloop-gcstress0x3-gcstress0xc/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fpull~2F24826~2Fhead/test~2Ffunctional~2Fcli~2F/20190528.71/workItem/baseservices.threading/wilogs

The same issue also reproduces on Windows 

Windows.10.Amd64.Open-x64:Checked-no_tiered_compilation 
Details from Job 41e61585-cbcb-4f09-86e2-517bd3f39f71
ExitCode: 1 
```
C:\dotnetbuild\work\41e61585-cbcb-4f09-86e2-517bd3f39f71\Work\b2d6c72b-edd7-461c-9914-d823440f5809\Exec>C:\Users\runner\.vsts-env\Scripts\python.exe C:\dotnetbuild\work\41e61585-cbcb-4f09-86e2-517bd3f39f71\Payload\reporter\run.py https://dev.azure.com/dnceng/ public 4965900 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJlNDI4NWM4Yy0zZmQ1LTQyNjctOWIxYy00MjE5NWM0N2E1NTMiLCJzY3AiOiJMb2NhdGlvblNlcnZpY2UuQ29ubmVjdCBSZWFkQW5kUHVibGlzaFRlc3Q6OWVlNmQ0NzgtZDI4OC00N2Y3LWFhY2MtZjZlNmQwODJhZTZkIFJlYWRBbmRVcGRhdGVCdWlsZEJ5VXJpOjllZTZkNDc4LWQyODgtNDdmNy1hYWNjLWY2ZTZkMDgyYWU2ZC9kb3RuZXQvY29yZWNsci8yMjg6QnVpbGQvQnVpbGQvMjA0NjkwIiwiYXVpIjoiNTY3M2U3OGItZTFiZC00ZTIyLTlhMzktZGU2ZWNjMGZiZThkIiwic2lkIjoiMTFlYmQ5ODktZTFhNS00MjY3LWIxNWQtNjI2MDhiNDAyZTRlIiwiaXNzIjoiYXBwLnZzdG9rZW4udmlzdWFsc3R1ZGlvLmNvbSIsImF1ZCI6ImFwcC52c3Rva2VuLnZpc3VhbHN0dWRpby5jb218dnNvOmI1NWRlNGVkLTRiNWEtNDIxNS1hOGU0LTBhMGE1ZjcxZTdkOCIsIm5iZiI6MTU1OTE2MDE2MCwiZXhwIjoxNTU5MTc1NzYwfQ.2RJo8Z87ygrYioTTEQFkOaHezlovgoI2CHTt_hIR79LKsSFRAdgwqHvcKtbVzRou958JwLJZr2pnUIkGdpWFyaTK2G_6shQJVzY8kCycZG0JhMqEkwhMl8hayKZihB96651CsEDXg0eWqESAsbIYd65z6NVyb6y6QHBb3Kvd_M88jjQaz-geQfgTCLTYifZ4rCDIKuomG85AqHPXLfl-zYhagxvg4F4WOXLpXZG-4_K1YrvM9PTAq4cVFwX1r71I8_A2Yvq__wZEekQzFTIDusp8GzjpQ7tT_73tqPjHfi_ht7kBrX3mAkM771aOIz5ulk7vNVDtc94ULo9GffV_Mw 

Got args https://dev.azure.com/dnceng/ public 4965900 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJlNDI4NWM4Yy0zZmQ1LTQyNjctOWIxYy00MjE5NWM0N2E1NTMiLCJzY3AiOiJMb2NhdGlvblNlcnZpY2UuQ29ubmVjdCBSZWFkQW5kUHVibGlzaFRlc3Q6OWVlNmQ0NzgtZDI4OC00N2Y3LWFhY2MtZjZlNmQwODJhZTZkIFJlYWRBbmRVcGRhdGVCdWlsZEJ5VXJpOjllZTZkNDc4LWQyODgtNDdmNy1hYWNjLWY2ZTZkMDgyYWU2ZC9kb3RuZXQvY29yZWNsci8yMjg6QnVpbGQvQnVpbGQvMjA0NjkwIiwiYXVpIjoiNTY3M2U3OGItZTFiZC00ZTIyLTlhMzktZGU2ZWNjMGZiZThkIiwic2lkIjoiMTFlYmQ5ODktZTFhNS00MjY3LWIxNWQtNjI2MDhiNDAyZTRlIiwiaXNzIjoiYXBwLnZzdG9rZW4udmlzdWFsc3R1ZGlvLmNvbSIsImF1ZCI6ImFwcC52c3Rva2VuLnZpc3VhbHN0dWRpby5jb218dnNvOmI1NWRlNGVkLTRiNWEtNDIxNS1hOGU0LTBhMGE1ZjcxZTdkOCIsIm5iZiI6MTU1OTE2MDE2MCwiZXhwIjoxNTU5MTc1NzYwfQ.2RJo8Z87ygrYioTTEQFkOaHezlovgoI2CHTt_hIR79LKsSFRAdgwqHvcKtbVzRou958JwLJZr2pnUIkGdpWFyaTK2G_6shQJVzY8kCycZG0JhMqEkwhMl8hayKZihB96651CsEDXg0eWqESAsbIYd65z6NVyb6y6QHBb3Kvd_M88jjQaz-geQfgTCLTYifZ4rCDIKuomG85AqHPXLfl-zYhagxvg4F4WOXLpXZG-4_K1YrvM9PTAq4cVFwX1r71I8_A2Yvq__wZEekQzFTIDusp8GzjpQ7tT_73tqPjHfi_ht7kBrX3mAkM771aOIz5ulk7vNVDtc94ULo9GffV_Mw

Main thread starting workers

Worker 0: starting...

Worker 1: starting...

Worker 2: starting...

Worker 3: starting...

Worker 4: starting...

Worker 5: starting...

Worker 6: starting...

Worker 7: starting...

Worker 8: starting...

Worker 9: starting...

Beginning reading of test results.

Uploading results in batches of size 1000

Searching 'C:\dotnetbuild\work\41e61585-cbcb-4f09-86e2-517bd3f39f71\Work\b2d6c72b-edd7-461c-9914-d823440f5809\Exec\..' for log files

Found log 'C:\dotnetbuild\work\41e61585-cbcb-4f09-86e2-517bd3f39f71\Work\b2d6c72b-edd7-461c-9914-d823440f5809\Exec\..\console.3221a1eb.log'

Uri 'https://helixexternalresults.blob.core.windows.net/dotnet-coreclr-refs-pull-24834-merge-41e61585cbcb4f0986/JIT.MyRepro/console.3221a1eb.log?sv=2017-07-29&sr=c&sig=IfJ5JKhy%2BWmLmD4fZBVQLvcLdVIEjUd6jQVWu3kZvT4%3D&se=2019-06-08T20%3A39%3A02Z&sp=rl'

Generated log list: <ul><li><a href='https://helixexternalresults.blob.core.windows.net/dotnet-coreclr-refs-pull-24834-merge-41e61585cbcb4f0986/JIT.MyRepro/console.3221a1eb.log?sv=2017-07-29&sr=c&sig=IfJ5JKhy%2BWmLmD4fZBVQLvcLdVIEjUd6jQVWu3kZvT4%3D&se=2019-06-08T20%3A39%3A02Z&sp=rl' target='_blank'>console.3221a1eb.log</a></li></ul>

Searching 'C:\dotnetbuild\work\41e61585-cbcb-4f09-86e2-517bd3f39f71\Work\b2d6c72b-edd7-461c-9914-d823440f5809\Exec' for test results files

Found results file C:\dotnetbuild\work\41e61585-cbcb-4f09-86e2-517bd3f39f71\Work\b2d6c72b-edd7-461c-9914-d823440f5809\Exec\testResults.xml with format xunit

Main thread finished queueing batches

Worker 0: got error: Traceback (most recent call last):

  File "C:\dotnetbuild\work\41e61585-cbcb-4f09-86e2-517bd3f39f71\Payload\reporter\run.py", line 39, in run

    self.__process(item)

  File "C:\dotnetbuild\work\41e61585-cbcb-4f09-86e2-517bd3f39f71\Payload\reporter\run.py", line 30, in __process

    self.publisher.upload_batch(batch)

  File "C:\dotnetbuild\work\41e61585-cbcb-4f09-86e2-517bd3f39f71\Payload\reporter\azure_devops_result_publisher.py", line 36, in upload_batch

    self.publish_results(test_case_results, results_with_attachments)

  File "C:\dotnetbuild\work\41e61585-cbcb-4f09-86e2-517bd3f39f71\Payload\reporter\azure_devops_result_publisher.py", line 57, in publish_results

    stream=base64.b64encode(text(attachment.text)),

  File "C:\Users\runner\.vsts-env\lib\base64.py", line 58, in b64encode

    encoded = binascii.b2a_base64(s, newline=False)

TypeError: a bytes-like object is required, not 'str'



Main thread exiting



C:\dotnetbuild\work\41e61585-cbcb-4f09-86e2-517bd3f39f71\Work\b2d6c72b-edd7-461c-9914-d823440f5809\Exec>echo  Wed 05/29/2019-20:42:33.12 

 Wed 05/29/2019-20:42:33.12



C:\dotnetbuild\work\41e61585-cbcb-4f09-86e2-517bd3f39f71\Work\b2d6c72b-edd7-461c-9914-d823440f5809\Exec>C:\python3.7.0\python.exe C:\dotnetbuild\work\41e61585-cbcb-4f09-86e2-517bd3f39f71\Payload\xunit-reporter.py 

2019-05-29 20:42:33,670: INFO: xunit-reporter(72): main: Uploading results from C:\dotnetbuild\work\41e61585-cbcb-4f09-86e2-517bd3f39f71\Work\b2d6c72b-edd7-461c-9914-d823440f5809\Exec\testResults.xml

2019-05-29 20:42:33,670: INFO: azure_storage(192): _upload: Uploading single blob: 'testResults.xml'

2019-05-29 20:42:33,717: INFO: saferequests(87): request_with_retry: Response complete with status code '201'

2019-05-29 20:42:33,717: INFO: xunit-reporter(86): main: Sending completion event

2019-05-29 20:42:33,717: INFO: event(44): send: Sending event type XUnitTestResult

2019-05-29 20:42:33,858: INFO: saferequests(87): request_with_retry: Response complete with status code '201'



C:\dotnetbuild\work\41e61585-cbcb-4f09-86e2-517bd3f39f71\Work\b2d6c72b-edd7-461c-9914-d823440f5809\Exec>EXIT /b 1 
```
https://mc.dot.net/#/user/coreclr-ci/pr~2Fdotnet~2Fcoreclr~2Frefs~2Fpull~2F24834~2Fmerge/test~2Ffunctional~2Fcli~2F/20190529.26/workItem/JIT.MyRepro/wilogs

**Comment by MattGal** [comment]
OK I'll dig some more, thanks for the update.

**Comment by MattGal** [comment]
I believe this was fixed in https://github.com/dotnet/arcade/pull/2878, I'll figure out what version has this fixed and make a PR to try.

**Comment by MattGal** [comment]
I confirmed that your Helix Arcade SDK version was just one day too old to get the fix,  made https://github.com/dotnet/coreclr/pull/24843 to bump it to latest.

**Comment by echesakovMSFT** [comment]
@MattGal Confirm that the test results reporting works as of 42ac1e71f77ab8e5036602b0bf673d6d6202923f
