### ISSUE TITLE
[Darc] update-dependencies broken on latest

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2805]
```
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Error: Failed to update dependencies to channel .NET Core 3 Dev
System.InvalidOperationException: The given header was not found.
   at System.Net.Http.Headers.HttpHeaders.GetValues(HeaderDescriptor descriptor)
   at System.Net.Http.Headers.HttpHeaders.GetValues(String name)
   at Microsoft.DotNet.Maestro.Client.PagedResponse`1..ctor(MaestroApi client, Func`3 onFailure, IHttpOperationResponse`1 response) in D:\enlistments\arcade-services2\src\Maestro\Client\src\Generated\PagedResponse.cs:line 49
   at Microsoft.DotNet.Maestro.Client.Builds.ListBuildsAsync(String buildNumber, Nullable`1 channelId, String commit, Nullable`1 loadCollections, Nullable`1 notAfter, Nullable`1 notBefore, Nullable`1 page, Nullable`1 perPage, String repository, CancellationToken cancellationToken) in D:\enlistments\arcade-services2\src\Maestro\Client\src\Generated\Builds.cs:line 96
   at Microsoft.DotNet.DarcLib.MaestroApiBarClient.GetBuildsAsync(String repoUri, String commit) in D:\enlistments\arcade-services2\src\Microsoft.DotNet.Darc\src\DarcLib\MaestroApiBarClient.cs:line 347
   at Microsoft.DotNet.DarcLib.DependencyGraph.BuildDependencyGraphImplAsync(IRemoteFactory remoteFactory, IEnumerable`1 rootDependencies, String repoUri, String commit, DependencyGraphBuildOptions options, Boolean remote, ILogger logger, String reposFolder, IEnumerable`1 remotesMap, String testPath) in D:\enlistments\arcade-services2\src\Microsoft.DotNet.Darc\src\DarcLib\Models\Darc\DependencyGraph.cs:line 486
   at Microsoft.DotNet.DarcLib.DependencyGraph.BuildRemoteDependencyGraphAsync(IRemoteFactory remoteFactory, IEnumerable`1 rootDependencies, String repoUri, String commit, DependencyGraphBuildOptions options, ILogger logger) in D:\enlistments\arcade-services2\src\Microsoft.DotNet.Darc\src\DarcLib\Models\Darc\DependencyGraph.cs:line 197
   at Microsoft.DotNet.DarcLib.Remote.BuildGraphAtDependency(IRemoteFactory remoteFactory, DependencyDetail rootDependency, List`1 updateList, Dictionary`2 nodeCache) in D:\enlistments\arcade-services2\src\Microsoft.DotNet.Darc\src\DarcLib\Actions\Remote.cs:line 553
   at Microsoft.DotNet.DarcLib.Remote.GetRequiredCoherencyUpdatesAsync(IEnumerable`1 dependencies, IRemoteFactory remoteFactory) in D:\enlistments\arcade-services2\src\Microsoft.DotNet.Darc\src\DarcLib\Actions\Remote.cs:line 468
   at Microsoft.DotNet.Darc.Operations.UpdateDependenciesOperation.ExecuteAsync() in D:\enlistments\arcade-services2\src\Microsoft.DotNet.Darc\src\Darc\Operations\UpdateDependenciesOperation.cs:line 180
```

**Comment by mmitche** [comment]
https://github.com/dotnet/arcade-services/pull/417

**Comment by mmitche** [comment]
Fixed and rolled out
