### ISSUE TITLE
Report can crash due to missing null checks in reporter\test_results_reader\__init__.py

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#2835]
As seen here: 

https://github.com/dotnet/corefx/pull/37734/checks?check_run_id=132766170

```
Searching 'C:\dotnetbuild\work\cf8bde42-1f0a-471b-9db7-11fec0e11a56\Work\e1102e7a-c27f-48ba-9ea7-5ba8bca8dbb5\Exec' for test results files
No results file found in any of the following formats: xunit, junit, trx
Traceback (most recent call last):
  File "C:\dotnetbuild\work\cf8bde42-1f0a-471b-9db7-11fec0e11a56\Payload\reporter\run.py", line 95, in <module>
    main()
  File "C:\dotnetbuild\work\cf8bde42-1f0a-471b-9db7-11fec0e11a56\Payload\reporter\run.py", line 84, in main
    for b in batches:
  File "C:\dotnetbuild\work\cf8bde42-1f0a-471b-9db7-11fec0e11a56\Payload\reporter\helpers.py", line 13, in batch
    for item in iterable:
  File "C:\dotnetbuild\work\cf8bde42-1f0a-471b-9db7-11fec0e11a56\Payload\reporter\test_results_reader\__init__.py", line 102, in read_results
    yield add_logs(__no_results_result(), log_list)
  File "C:\dotnetbuild\work\cf8bde42-1f0a-471b-9db7-11fec0e11a56\Payload\reporter\test_results_reader\__init__.py", line 72, in add_logs
    tr.attachments.append(TestResultAttachment(
AttributeError: 'NoneType' object has no attribute 'append'
```
This is an error case where the Xunit console runner exploded due to an unhandled exception, but it should be addressed (simple null check ought to get it)

@wtgodbe , @alexperovich  FYI

**Comment by alexperovich** [comment]
This cannot be a simple null check. It is trying to add an attachment to the list. We should create the list if it is None. It shouldn't skip adding the attachment if the list is None.

**Comment by markwilkie** [comment]
Moving to Helix

**Comment by markwilkie** [comment]
Looks like Chad kicked this out, which implies a lower priority.  Closing.
