### ISSUE TITLE
darc Failed to retrieve subscriptions

### ISSUE THREAD

**Issue by wli3** [dotnet/arcade#2859]
command ` darc get-subscriptions --source-repo arcade --target-repo cli  --bar-uri https://maestro-prod.westus2.cloudapp.azure.com/`

```
darc --version
Microsoft.DotNet 1.1.0-beta.19205.4+6302737da8c98f7c6f3076967e8846f806c31a63
```

```
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Error: Failed to retrieve subscriptions
Newtonsoft.Json.JsonSerializationException: Error converting value "everyWeek" to type 'Microsoft.DotNet.Maestro.Client.Models.SubscriptionPolicyUpdateFrequency'. Path '[11].policy.updateFrequency', line 1, position 5587. ---> System.ArgumentException: Requested value 'everyWeek' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.DotNet.Maestro.Client.Subscriptions.ListSubscriptionsInternalAsync(Nullable`1 channelId, Nullable`1 enabled, String sourceRepository, String targetRepository, CancellationToken cancellationToken) in /_/src/Maestro/Client/src/Generated/Subscriptions.cs:line 165
   at Microsoft.DotNet.Maestro.Client.Subscriptions.ListSubscriptionsAsync(Nullable`1 channelId, Nullable`1 enabled, String sourceRepository, String targetRepository, CancellationToken cancellationToken) in /_/src/Maestro/Client/src/Generated/Subscriptions.cs:line 90
   at Microsoft.DotNet.DarcLib.MaestroApiBarClient.GetSubscriptionsAsync(String sourceRepo, String targetRepo, Nullable`1 channelId) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/MaestroApiBarClient.cs:line 174
   at Microsoft.DotNet.Darc.Operations.GetSubscriptionsOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/GetSubscriptionsOperation.cs:line 35
```

**Comment by jcagme** [comment]
fyi: @mmitche @riarenas

**Comment by alexperovich** [comment]
This is caused by an out-of-date version of darc and/or the Maestro client api. The generated enum for the SubscriptionPolicyUpdateFrequency type doesn't include a definition for the new 'everyWeek' value.

**Comment by riarenas** [comment]
To fix: **rerun eng\common\darc-init.ps1** to get the version of darc that matches the currently deployed version of the Maestro API.

**Comment by wli3** [comment]
I ran again, but i still get version 1.1.0-beta.19205.4+6302737da8c98f7c6f3076967e8846f806c31a63 Where is the arcade feed? I can try manually install

**Comment by jcagme** [comment]
Just tan that and got `1.1.0-beta.19265.2+5c528b7e6e9ae3892202d0e8ed9a9b2206fc950c`. Do you have the latest on Arcade? I know there were some changes done to the scripts in the past couple of weeks.

**Comment by riarenas** [comment]
Are you running it from a repo that isn't currently up to date with Arcade? we made some recent changes on how Darc is downloaded.

You can also just take the script from Arcade
https://github.com/dotnet/arcade/blob/master/eng/common/darc-init.ps1

**Comment by wli3** [comment]
ah, i get it. The version is attached to the script. Now I get it. Thanks!

**Comment by mmitche** [comment]
@wli3 In the newer versions of arcade, the version is no longer in the script, and is identified from the web-service. Are you very out of date?

**Comment by wli3** [comment]
I think because my script it too old. I still use the version attached version
