### ISSUE TITLE
Exceptions from RemoteExecutorHost should get into XML log

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/arcade#3142]
We should try to `tee` the console from RemoteExecutorHost so it gets into the XML test log and thus into the correct test result in Helix. As it is you just get eg (note the code = "some managed exceptoin")
```
Assert.Equal() Failure\r
    Expected: 42\r
    Actual:   -532462766

        Stack Trace:

           at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
```
but if you look at the full console output, aggregated for all the tests in this library, you see the actual exception --
```
2017-05-09 01:33:05,362: INFO: proc(54): run_and_log_output: Output: Hello World
2017-05-09 01:33:05,440: INFO: proc(54): run_and_log_output: Output: Exception from RemoteExecutorConsoleApp(System.Console.Tests, Version=4.1.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb, ConsoleEncoding+<>c, <OutputEncoding_SetWithErrorAndOutputInitialized_ResetsErrorAndOutput>b__6_0):
2017-05-09 01:33:05,440: INFO: proc(54): run_and_log_output: Output: Assembly: System.Console.Tests, Version=4.1.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb
2017-05-09 01:33:05,440: INFO: proc(54): run_and_log_output: Output: Type: ConsoleEncoding+<>c
2017-05-09 01:33:05,440: INFO: proc(54): run_and_log_output: Output: Method: Int32 <OutputEncoding_SetWithErrorAndOutputInitialized_ResetsErrorAndOutput>b__6_0()
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output: Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.IOException: The request is not supported
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    at System.ConsolePal.SetConsoleOutputEncoding(Encoding enc)
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    at System.Console.set_OutputEncoding(Encoding value)
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    at ConsoleEncoding.<>c.<OutputEncoding_SetWithErrorAndOutputInitialized_ResetsErrorAndOutput>b__6_0()
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    --- End of inner exception stack trace ---
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    at RemoteExecutorConsoleApp.Program.Main(String[] args)
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output: 
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output: Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.IOException: The request is not supported
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    at System.ConsolePal.SetConsoleOutputEncoding(Encoding enc)
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    at System.Console.set_OutputEncoding(Encoding value)
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    at ConsoleEncoding.<>c.<OutputEncoding_SetWithErrorAndOutputInitialized_ResetsErrorAndOutput>b__6_0()
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    --- End of inner exception stack trace ---
2017-05-09 01:33:05,487: INFO: proc(54): run_and_log_output: Output:    at RemoteExecutorConsoleApp.Program.Main(String[] args)
2017-05-09 01:33:05,596: INFO: proc(54): run_and_log_output: Output:    ConsoleEncoding.OutputEncoding_SetWithErrorAndOutputInitialized_ResetsErrorAndOutput [FAIL]
2017-05-09 01:33:05,596: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2017-05-09 01:33:05,596: INFO: proc(54): run_and_log_output: Output:       Expected: 42
2017-05-09 01:33:05,596: INFO: proc(54): run_and_log_output: Output:       Actual:   -532462766
2017-05-09 01:33:05,596: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2017-05-09 01:33:05,721: INFO: proc(54): run_and_log_output: Output:             at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
2017-05-09 01:33:05,957: INFO: proc(54): run_and_log_output: Output: Exception from RemoteExecutorConsoleApp(System.Console.Tests, Version=4.1.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb, ConsoleEncoding+<>c, <InputEncoding_SetWithInInitialized_ResetsIn>b__3_0):
2017-05-09 01:33:05,957: INFO: proc(54): run_and_log_output: Output: Assembly: System.Console.Tests, Version=4.1.0.0, Culture=neutral, PublicKeyToken=9d77cc7ad39b68eb
```

**Comment by alexperovich** [comment]
Is this anything more than modifying RemoteExecutor.Invoke here (https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutor/RemoteExecutor.cs#L247) to accept an ITestOutputHelper thing and capture the StdOut/StdErr from the process into it?

**Comment by danmosemsft** [comment]
@ViktorHofer ?

**Comment by ViktorHofer** [comment]
Microsoft.DotNet.RemoteExecutor is currently only tied to xunit in a few places to do an assert. Ideally we would not add more dependency and instead get rid of its dependency so that it can be used outside of xunit.

**Comment by markwilkie** [comment]
This issue is over a year old.  Is there something actionable here that says we should keep it open?

**Comment by markwilkie** [comment]
Closing given no activity or responses.
