### ISSUE TITLE
Dependency flow PRs to dotnet/toolset failing to open due to coherency issues

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3210]
We are not opening dependency update PRs in dotnet/toolset due to the following exception: 
```
Microsoft.DotNet.DarcLib.DarcException: Unable to update Microsoft.DotNet.Cli.Runtime to have coherency with parent Microsoft.NETCore.App. No matching asset found in tree. Either remove the coherency attribute or mark as pinned.
   at Microsoft.DotNet.DarcLib.Remote.GetRequiredCoherencyUpdatesAsync(IEnumerable`1 dependencies, IRemoteFactory remoteFactory) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs:line 496
   at SubscriptionActorService.PullRequestActorImplementation.GetRequiredUpdates(List`1 updates, IRemoteFactory remoteFactory, String targetRepository, String branch) in /_/src/Maestro/SubscriptionActorService/PullRequestActor.cs:line 968
   at SubscriptionActorService.PullRequestActorImplementation.CreatePullRequestAsync(List`1 updates) in /_/src/Maestro/SubscriptionActorService/PullRequestActor.cs:line 603
   at SubscriptionActorService.PullRequestActorImplementation.UpdateAssetsAsync(Guid subscriptionId, Int32 buildId, String sourceRepo, String sourceSha, List`1 assets) in /_/src/Maestro/SubscriptionActorService/PullRequestActor.cs:line 533
   at SubscriptionActorService.ActionRunner.InvokeAction[T](IActionTracker target, ActionMethod method, Object[] arguments)
```

The error comes from here: https://github.com/dotnet/arcade-services/blob/751d20854dcf3be4cc03b7583d995eba9034d48f/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs#L496 where we weren't able to find the coherent asset.

CC @livarcocc, @jcagme

**Comment by jcagme** [comment]
Moving to core-eng so I can make this an FR issue

**Comment by jcagme** [comment]
Issue moved to [dotnet/core-eng #6852](https://github.com/dotnet/core-eng/issues/6852) via [**ZenHub**](https://www.zenhub.com/)
