### ISSUE TITLE
[darc/maestro++] set-repository-policies command returns 500 if the repo provided in --repo doesn't exist

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3212]
```
> darc set-repository-policies --repo aspnet/Blazor --standard-automerge --branch release/0.10.0-preview7 --quiet
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Failed to set merge policies.
Microsoft.DotNet.Maestro.Client.RestApiException`1[Microsoft.DotNet.Maestro.Client.Models.ApiError]: The response contai
ned an invalid status code 500 Internal Server Error

Body: {"message":"An error occured.","errors":null}
   at Microsoft.DotNet.Maestro.Client.Repository.OnSetMergePoliciesFailed(HttpRequestMessage req, HttpResponseMessage re
s) in /_/src/Maestro/Client/src/Generated/Repository.cs:line 284
   at Microsoft.DotNet.Maestro.Client.Repository.SetMergePoliciesInternalAsync(String branch, String repository, IImmuta
bleList`1 body, CancellationToken cancellationToken) in /_/src/Maestro/Client/src/Generated/Repository.cs:line 353
   at Microsoft.DotNet.Maestro.Client.Repository.SetMergePoliciesAsync(String branch, String repository, IImmutableList`
1 body, CancellationToken cancellationToken) in /_/src/Maestro/Client/src/Generated/Repository.cs:line 262
   at Microsoft.DotNet.DarcLib.MaestroApiBarClient.SetRepositoryMergePoliciesAsync(String repoUri, String branch, List`1
mergePolicies) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/MaestroApiBarClient.cs:line 285
   at Microsoft.DotNet.Darc.Operations.SetRepositoryMergePoliciesOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Dar
c/src/Darc/Operations/SetRepositoryMergePoliciesOperation.cs:line 131
```

The full uri: https://github.com/aspnet/Blazor is required.
Instead of returning a 500 error and showing the exception, this should be a 400, and Darc should just report an error to the user about the repo not being found.

**Comment by JohnTortugo** [comment]
This is the error that that command line reports nowadays:

```
warn: Microsoft.DotNet.Darc.Operations.Operation[0]
      Failed to load the darc settings file, may be corrupted
Microsoft.DotNet.DarcLib.DarcException: Unknown repository 'dotnet/roslyn', repo type set to 'None'.
   at Microsoft.DotNet.Darc.Helpers.LocalSettings.GetDarcSettings(CommandLineOptions options, ILogger logger, String repoUri) in C:\Workfolder\arcade-services\src\Microsoft.DotNet.Darc\src\Darc\Helpers\LocalSettings.cs:line 124
Unhandled exception while running Operation
System.ArgumentException: Must supply a valid GitHub/Azure DevOps PAT
   at Microsoft.DotNet.DarcLib.Remote.CheckForValidGitClient() in C:\Workfolder\arcade-services\src\Microsoft.DotNet.Darc\src\DarcLib\Actions\Remote.cs:line 1063
   at Microsoft.DotNet.DarcLib.Remote.GetDependenciesAsync(String repoUri, String branchOrCommit, String name, Boolean loadAssetLocations) in C:\Workfolder\arcade-services\src\Microsoft.DotNet.Darc\src\DarcLib\Actions\Remote.cs:line 1017
   at Microsoft.DotNet.Darc.UxHelpers.VerifyAndConfirmBranchExistsAsync(IRemote remote, String repo, String branch, Boolean prompt) in C:\Workfolder\arcade-services\src\Microsoft.DotNet.Darc\src\Darc\Helpers\UxHelpers.cs:line 269
   at Microsoft.DotNet.Darc.Operations.SetRepositoryMergePoliciesOperation.ExecuteAsync() in C:\Workfolder\arcade-services\src\Microsoft.DotNet.Darc\src\Darc\Operations\SetRepositoryMergePoliciesOperation.cs:line 128
   at Microsoft.DotNet.Darc.Program.RunOperation(CommandLineOptions opts) in C:\Workfolder\arcade-services\src\Microsoft.DotNet.Darc\src\Darc\Program.cs:line 35
```

This line is trowing an exception and the exception is being interpreted as problems loading the settings file.
