### ISSUE TITLE
Python exception thrown in test results reporter for no-XML-results-available scenarios

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#3636]
Full log:
https://helix.dot.net/api/2019-06-17/jobs/d47e9a92-af57-4108-876b-5dc45e7ca70c/workitems/System.Net.Http.Functional.Tests/console

Relevant bits:
```
----- end Thu 08/08/2019 20:11:58.19 ----- exit code -2146232797 ----------------------------------------------------------
 Thu 08/08/2019-20:11:58.19
 Thu 08/08/2019-20:11:58.41
2019-08-08 20:11:58,810: INFO: 1584: run(82): main: Main thread starting 10 workers
Worker 0: starting...
Worker 1: starting...
Worker 2: starting...
Worker 3: starting...
Worker 4: starting...
Worker 5: starting...
Worker 6: starting...
Worker 7: starting...
Worker 8: starting...
Worker 9: starting...
2019-08-08 20:11:58,810: INFO: 1584: run(89): main: Beginning reading of test results.
2019-08-08 20:11:58,810: INFO: 1584: run(95): main: Uploading results in batches of size 1000
Searching 'C:\dotnetbuild\work\d47e9a92-af57-4108-876b-5dc45e7ca70c\Work\840ae698-8896-4647-bd3c-8e351884095b\Exec\..' for log files
Found log 'C:\dotnetbuild\work\d47e9a92-af57-4108-876b-5dc45e7ca70c\Work\840ae698-8896-4647-bd3c-8e351884095b\Exec\..\console.bd117e71.log'
Uri 'https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-corefx-refs-pull-40163-merge-d47e9a92af57410887/System.Net.Http.Functional.Tests/console.bd117e71.log?sv=2017-07-29&sr=c&sig=wVUaJfcOrzXVjQ0f3FOQZWOfFfGiCQWzuftxXAJaWq8%3D&se=2019-08-18T20%3A09%3A11Z&sp=rl'
Generated log list: <ul><li><a href='https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-corefx-refs-pull-40163-merge-d47e9a92af57410887/System.Net.Http.Functional.Tests/console.bd117e71.log?sv=2017-07-29&sr=c&sig=wVUaJfcOrzXVjQ0f3FOQZWOfFfGiCQWzuftxXAJaWq8%3D&se=2019-08-18T20%3A09%3A11Z&sp=rl' target='_blank'>console.bd117e71.log</a></li></ul>
Searching 'C:\dotnetbuild\work\d47e9a92-af57-4108-876b-5dc45e7ca70c\Work\840ae698-8896-4647-bd3c-8e351884095b\Exec' for test results files
No results file found in any of the following formats: xunit, junit, trx
Traceback (most recent call last):
  File "C:\dotnetbuild\work\d47e9a92-af57-4108-876b-5dc45e7ca70c\Payload\reporter\run.py", line 107, in <module>
    main()
  File "C:\dotnetbuild\work\d47e9a92-af57-4108-876b-5dc45e7ca70c\Payload\reporter\run.py", line 97, in main
    for b in batches:
  File "C:\dotnetbuild\work\d47e9a92-af57-4108-876b-5dc45e7ca70c\Payload\reporter\helpers.py", line 13, in batch
    for item in iterable:
  File "C:\dotnetbuild\work\d47e9a92-af57-4108-876b-5dc45e7ca70c\Payload\reporter\test_results_reader\__init__.py", line 101, in read_results
    yield add_logs(__no_results_result(), log_list)
  File "C:\dotnetbuild\work\d47e9a92-af57-4108-876b-5dc45e7ca70c\Payload\reporter\test_results_reader\__init__.py", line 71, in add_logs
    if tr.result != "Pass" and total_added_logs < 50:
AttributeError: 'NoneType' object has no attribute 'result'
 Thu 08/08/2019-20:11:58.82
2019-08-08 20:11:59,091: ERROR: xunit-reporter(69): main: Unable to report xunit results: no test results xml file found.
```

Probably as simple as making sure tr isn't null, have not inspected the scripts yet. 

@wfurt FYI.

**Comment by MattGal** [comment]
Looks like this null ref is https://github.com/dotnet/arcade/blame/master/src/Microsoft.DotNet.Helix/Sdk/tools/azure-pipelines/reporter/test_results_reader/__init__.py#L14 ... specifically given the exit code is -2146232797, the tr object returned is None, leading to this error.

**For whichever FR Person takes this:**  Work with @mjanecke to see if there's a reason this should be null and what the correct behavior is, then either fill out a failed TestResults object instead of null, or add a null check based off that conversation please.

**Comment by mjanecke** [comment]
The reason for this change was so that we weren't creating a failed test result for the test when the work item failed, and we're creating a fake test result for the failure with all the attached files (logs, crash dumps, et cetera). Sorry :(

**Comment by AlitzelMendez** [comment]
Adding a null check based on a conversation with Missy

**Comment by MattGal** [comment]
https://github.com/dotnet/arcade/pull/3670 was merged 2 weeks ago, and I'm  not seeing folks bring this up, so closing (please reactivate if I am in error)
