### ISSUE TITLE
Show core file URL in console.log if core was collected from test run.

### ISSUE THREAD

**Issue by wfurt** [dotnet/arcade#3785]
I had failed test run: https://helix.dot.net/api/2019-06-17/jobs/84ef369e-9795-4f92-bfef-43a2f1558542/workitems/System.Net.Http.Functional.Tests/console

Since the console.log is first landing place developers go to it would be great to spit out more details about corefile, just like we do about console. Download link would be best. 

```
Executed on a000C62

C:\dotnetbuild\work\84ef369e-9795-4f92-bfef-43a2f1558542\Work\f71c1b3b-8b72-4b86-bd6d-38f6b6265b6f\Exec>call RunTests.cmd --runtime-path C:\dotnetbuild\work\84ef369e-9795-4f92-bfef-43a2f1558542\Payload 
----- start Tue 08/27/2019 19:11:27.68 ===============  To repro directly: ===================================================== 
pushd C:\dotnetbuild\work\84ef369e-9795-4f92-bfef-43a2f1558542\Work\f71c1b3b-8b72-4b86-bd6d-38f6b6265b6f\Exec\
"C:\dotnetbuild\work\84ef369e-9795-4f92-bfef-43a2f1558542\Payload\dotnet.exe" exec --runtimeconfig System.Net.Http.Functional.Tests.runtimeconfig.json xunit.console.dll System.Net.Http.Functional.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing 
popd
===========================================================================================================

C:\dotnetbuild\work\84ef369e-9795-4f92-bfef-43a2f1558542\Work\f71c1b3b-8b72-4b86-bd6d-38f6b6265b6f\Exec>"C:\dotnetbuild\work\84ef369e-9795-4f92-bfef-43a2f1558542\Payload\dotnet.exe" exec --runtimeconfig System.Net.Http.Functional.Tests.runtimeconfig.json xunit.console.dll System.Net.Http.Functional.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing  
  Discovering: System.Net.Http.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Http.Functional.Tests (found 320 of 1134 test cases)
  Starting:    System.Net.Http.Functional.Tests (parallel test collections = on, max threads = 2)
    System.Net.Http.Functional.Tests.PlatformHandler_DefaultCredentialsTest.UseDefaultCredentials_SetFalse_Unauthorized [SKIP]
      Condition(s) not met: "ServerAuthenticationTestsEnabled"
    System.Net.Http.Functional.Tests.PlatformHandler_DefaultCredentialsTest.Credentials_SetToBadCredential_Unauthorized [SKIP]
      Condition(s) not met: "ServerAuthenticationTestsEnabled"
    System.Net.Http.Functional.Tests.PlatformHandler_DefaultCredentialsTest.Credentials_SetToWrappedDefaultCredential_ConnectAsCurrentIdentity [SKIP]
      Condition(s) not met: "ServerAuthenticationTestsEnabled"
    System.Net.Http.Functional.Tests.PlatformHandler_DefaultCredentialsTest.UseDefaultCredentials_SetTrue_ConnectAsCurrentIdentity [SKIP]
      Condition(s) not met: "ServerAuthenticationTestsEnabled"
    System.Net.Http.Functional.Tests.PlatformHandler_DefaultCredentialsTest.UseDefaultCredentials_DefaultValue_Unauthorized [SKIP]
      Condition(s) not met: "ServerAuthenticationTestsEnabled"
    System.Net.Http.Functional.Tests.PlatformHandler_DefaultCredentialsTest.Proxy_UseAuthenticatedProxyWithWrappedDefaultCredentials_OK [SKIP]
      Condition(s) not met: "DomainProxyTestsEnabled"
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds [SKIP]
      Condition(s) not met: "ClientSupportsDHECipherSuites"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_DefaultCredentialsTest.UseDefaultCredentials_SetFalse_Unauthorized [SKIP]
      Condition(s) not met: "ServerAuthenticationTestsEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_DefaultCredentialsTest.Credentials_SetToWrappedDefaultCredential_ConnectAsCurrentIdentity [SKIP]
      Condition(s) not met: "ServerAuthenticationTestsEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_DefaultCredentialsTest.UseDefaultCredentials_SetTrue_ConnectAsCurrentIdentity [SKIP]
      Condition(s) not met: "ServerAuthenticationTestsEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_DefaultCredentialsTest.UseDefaultCredentials_DefaultValue_Unauthorized [SKIP]
      Condition(s) not met: "ServerAuthenticationTestsEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_DefaultCredentialsTest.Credentials_SetToBadCredential_Unauthorized [SKIP]
      Condition(s) not met: "ServerAuthenticationTestsEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_DefaultCredentialsTest.Proxy_UseAuthenticatedProxyWithWrappedDefaultCredentials_OK [SKIP]
      Condition(s) not met: "DomainProxyTestsEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds [SKIP]
      Condition(s) not met: "ClientSupportsDHECipherSuites"
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Test.NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds [SKIP]
      Condition(s) not met: "ClientSupportsDHECipherSuites"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ServerCertificates_Test.NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds [SKIP]
      Condition(s) not met: "ClientSupportsDHECipherSuites"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ServerCertificates_Test.NoCallback_BadCertificate_ThrowsException [SKIP]
      Condition(s) not met: "ClientSupportsDHECipherSuites"
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Test.NoCallback_BadCertificate_ThrowsException [SKIP]
      Condition(s) not met: "ClientSupportsDHECipherSuites"
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Proxy_Test.Proxy_UseEnvironmentVariableToSetSystemProxy_RequestGoesThruProxy [SKIP]
      Test needs SocketsHttpHandler
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.HttpListener.DisconnectAsyncResult.IOCompleted(DisconnectAsyncResult asyncResult, UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in /_/src/System.Net.HttpListener/src/System/Net/Windows/HttpListener.Windows.cs:line 1957
   at System.Net.HttpListener.DisconnectAsyncResult.WaitCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in /_/src/System.Net.HttpListener/src/System/Net/Windows/HttpListener.Windows.cs:line 1969
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped) in /_/src/System.Private.CoreLib/src/System/Threading/Overlapped.cs:line 64
----- end Tue 08/27/2019 19:12:57.89 ----- exit code -1073741819 ----------------------------------------------------------
 Tue 08/27/2019-19:12:57.92
 Tue 08/27/2019-19:12:58.20
2019-08-27 19:12:58,660: INFO: 2636: run(82): main: Main thread starting 10 workers
Worker 0: starting...
Worker 1: starting...
Worker 2: starting...
Worker 3: starting...
Worker 4: starting...
Worker 5: starting...
Worker 6: starting...
Worker 7: starting...
Worker 8: starting...
Worker 9: starting...
2019-08-27 19:12:58,676: INFO: 2636: run(89): main: Beginning reading of test results.
2019-08-27 19:12:58,676: INFO: 2636: run(95): main: Uploading results in batches of size 1000
2019-08-27 19:12:58,676: INFO: 2636: run(100): main: Main thread finished queueing batches
2019-08-27 19:12:58,676: INFO: 2636: run(104): main: Main thread exiting
Searching 'C:\dotnetbuild\work\84ef369e-9795-4f92-bfef-43a2f1558542\Work\f71c1b3b-8b72-4b86-bd6d-38f6b6265b6f\Exec\..' for log files
Found log 'C:\dotnetbuild\work\84ef369e-9795-4f92-bfef-43a2f1558542\Work\f71c1b3b-8b72-4b86-bd6d-38f6b6265b6f\Exec\..\console.b09eba4f.log'
Uri 'https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-corefx-refs-pull-40543-merge-84ef369e97954f92bf/System.Net.Http.Functional.Tests/console.b09eba4f.log?sv=2018-03-28&sr=c&sig=Yow60lVW%2FgDZ9OgiHyNGfRR%2F2wWLR2X4KA0brC0whvU%3D&se=2019-09-06T18%3A52%3A28Z&sp=rl'
Generated log list: <ul><li><a href='https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-corefx-refs-pull-40543-merge-84ef369e97954f92bf/System.Net.Http.Functional.Tests/console.b09eba4f.log?sv=2018-03-28&sr=c&sig=Yow60lVW%2FgDZ9OgiHyNGfRR%2F2wWLR2X4KA0brC0whvU%3D&se=2019-09-06T18%3A52%3A28Z&sp=rl' target='_blank'>console.b09eba4f.log</a></li></ul>
Searching 'C:\dotnetbuild\work\84ef369e-9795-4f92-bfef-43a2f1558542\Work\f71c1b3b-8b72-4b86-bd6d-38f6b6265b6f\Exec' for test results files
No results file found in any of the following formats: xunit, junit, trx
 Tue 08/27/2019-19:12:58.69
2019-08-27 19:12:59,004: ERROR: xunit-reporter(69): main: Unable to report xunit results: no test results xml file found.
```

**Comment by markwilkie** [comment]
Thoughts on next steps (if any) @wfurt ?

**Comment by MattGal** [comment]
Taking this one for FR, though I agree that since dumps are a thing we copy up after execution ends appending this to the console log might be tricky (but not impossible).

**Comment by MattGal** [comment]
Removing the FR label as we have plenty in the backlog, this isn't being asked for urgently by users, is a feature request, and has a simple workaround (hit the Helix files API).  Seems like a good thing to cover in a future Helix rewrite.

**Comment by markwilkie** [comment]
@wfurt - is this a priority for you?  If so, please reopen.  (I'm trying to actually close things that we realistically are not currently planning on doing in the foreseeable future.  However, your input can change that!)
