### ISSUE TITLE
[darc/maestro++] "darc update-subscription" is missing "Target Repository URL" and fails when I add it

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#4069]
The popup doesn't show the `Target Repository URL` property, and typing it in manually causes an exception:

```
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Failed to parse input yaml.  Please see help for correct format.
YamlDotNet.Core.YamlException: (Line: 2, Col: 1, Idx: 2) - (Line: 2, Col: 1, Idx: 2): Exception during deserialization ---> System.Runtime.Serialization.SerializationException: Property 'Target Repository URL' not found on type 'Microsoft.DotNet.Darc.Models.PopUps.UpdateSubscriptionPopUp+SubscriptionData'.
   at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at Microsoft.DotNet.Darc.Models.PopUps.UpdateSubscriptionPopUp.ProcessContents(IList`1 contents) in /_/src/Microsoft.DotNet.Darc/src/Darc/Models/PopUps/UpdateSubscriptionPopUp.cs:line 110
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Inputs were invalid, please try again...
```

I would have liked to use this to split a chunk of an existing repo into a different repo. I'll add a subscription instead and just delete this one.

@mmitche @riarenas @JohnTortugo

**Comment by dagood** [comment]
Looks like `Branch` is also missing, now that I'm seeing the update data and add template side by side.

**Comment by mmitche** [comment]
You can't edit the target branch and repo of a subscription today. Those are keys in the service fabric actor (tracking existing PRs and updates), so you have to recreate a new subscription.  I have changes in-flight to update-subscription which allow for update of those elements, though it's just transparently replacing the subscription for you.

**Comment by mmitche** [comment]
This is covered by #3689
