### ISSUE TITLE
NullReferenceException on dispose from Microsoft.DotNet.Helix.Sdk.LoggerExtensions.UpdateCategory

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#4219]
See attempt 1 here: https://dev.azure.com/dnceng/public/_build/results?buildId=404922
From https://github.com/dotnet/corefx/pull/41940
```
Stopping Azure Pipelines Test Run netcoreapp-Windows_NT-Debug-x64-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-61052b7-20190723211353
D:\a\1\s\.packages\microsoft.dotnet.helix.sdk\5.0.0-beta.19525.2\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(75,5): error : Work item f436d4ff-86a8-4c4f-b958-306cf5e9db47/System.Net.Security.Tests in job f436d4ff-86a8-4c4f-b958-306cf5e9db47 has failed. [D:\a\1\s\eng\sendtohelix.proj]
##[error].packages\microsoft.dotnet.helix.sdk\5.0.0-beta.19525.2\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(75,5): error : (NETCORE_ENGINEERING_TELEMETRY=Test) Work item f436d4ff-86a8-4c4f-b958-306cf5e9db47/System.Net.Security.Tests in job f436d4ff-86a8-4c4f-b958-306cf5e9db47 has failed.
D:\a\1\s\.packages\microsoft.dotnet.helix.sdk\5.0.0-beta.19525.2\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(75,5): error : NullReferenceException: Object reference not set to an instance of an object. [D:\a\1\s\eng\sendtohelix.proj]
D:\a\1\s\.packages\microsoft.dotnet.helix.sdk\5.0.0-beta.19525.2\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(75,5): error :    at Microsoft.DotNet.Helix.Sdk.LoggerExtensions.UpdateCategory(TaskLoggingHelper log) in /_/src/Microsoft.DotNet.Helix/Sdk/LoggerExtensions.cs:line 40 [D:\a\1\s\eng\sendtohelix.proj]
D:\a\1\s\.packages\microsoft.dotnet.helix.sdk\5.0.0-beta.19525.2\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(75,5): error :    at Microsoft.DotNet.Helix.Sdk.LoggerExtensions.FailureCategoryScope.Dispose() in /_/src/Microsoft.DotNet.Helix/Sdk/LoggerExtensions.cs:line 88 [D:\a\1\s\eng\sendtohelix.proj]
D:\a\1\s\.packages\microsoft.dotnet.helix.sdk\5.0.0-beta.19525.2\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(75,5): error :    at Microsoft.DotNet.Helix.Sdk.LoggerExtensions.LogError(TaskLoggingHelper log, FailureCategory category, String message, Object[] messageArgs) in /_/src/Microsoft.DotNet.Helix/Sdk/LoggerExtensions.cs:line 48 [D:\a\1\s\eng\sendtohelix.proj]
D:\a\1\s\.packages\microsoft.dotnet.helix.sdk\5.0.0-beta.19525.2\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(75,5): error :    at Microsoft.DotNet.Helix.Sdk.CheckHelixJobStatus.ExecuteCore(CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Sdk/CheckHelixJobStatus.cs:line 38 [D:\a\1\s\eng\sendtohelix.proj]
D:\a\1\s\.packages\microsoft.dotnet.helix.sdk\5.0.0-beta.19525.2\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(75,5): error :    at Microsoft.DotNet.Helix.Sdk.HelixTask.Execute() in /_/src/Microsoft.DotNet.Helix/Sdk/HelixTask.cs:line 53 [D:\a\1\s\eng\sendtohelix.proj]
D:\a\1\s\.packages\microsoft.dotnet.helix.sdk\5.0.0-beta.19525.2\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(75,5): error :  [D:\a\1\s\eng\sendtohelix.proj]
##[error].packages\microsoft.dotnet.helix.sdk\5.0.0-beta.19525.2\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(75,5): error : (NETCORE_ENGINEERING_TELEMETRY=Test) NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Helix.Sdk.LoggerExtensions.UpdateCategory(TaskLoggingHelper log) in /_/src/Microsoft.DotNet.Helix/Sdk/LoggerExtensions.cs:line 40
   at Microsoft.DotNet.Helix.Sdk.LoggerExtensions.FailureCategoryScope.Dispose() in /_/src/Microsoft.DotNet.Helix/Sdk/LoggerExtensions.cs:line 88
   at Microsoft.DotNet.Helix.Sdk.LoggerExtensions.LogError(TaskLoggingHelper log, FailureCategory category, String message, Object[] messageArgs) in /_/src/Microsoft.DotNet.Helix/Sdk/LoggerExtensions.cs:line 48
   at Microsoft.DotNet.Helix.Sdk.CheckHelixJobStatus.ExecuteCore(CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Sdk/CheckHelixJobStatus.cs:line 38
   at Microsoft.DotNet.Helix.Sdk.HelixTask.Execute() in /_/src/Microsoft.DotNet.Helix/Sdk/HelixTask.cs:line 53

D:\a\1\s\.packages\microsoft.dotnet.helix.sdk\5.0.0-beta.19525.2\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(75,5): error MSB4018: The "CheckHelixJobStatus" task failed unexpectedly. [D:\a\1\s\eng\sendtohelix.proj]
D:\a\1\s\.packages\microsoft.dotnet.helix.sdk\5.0.0-beta.19525.2\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(75,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [D:\a\1\s\eng\sendtohelix.proj]
D:\a\1\s\.pac
```

**Comment by alexperovich** [comment]
I just pushed a fix. https://github.com/dotnet/arcade/pull/4218

**Comment by MattGal** [comment]
Thanks @alexperovich , I'll keep this on myself then til it rolls out.

**Comment by MattGal** [comment]
This has been rolled out to affected teams and seems resolved, closing.
