### ISSUE TITLE
xunit-reporter.py needs to handle unicode strings in XUnit result xmls

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#4334]
As part of OSOB signoff activities I noted this subtle-ish bug (See XUnit XML produced by the CoreFx "Invariant.Tests" test for an example.

```
2019-11-12 17:07:46,496: INFO: 4784: run(104): main: Main thread exiting
 Tue 11/12/2019-17:07:46.52
2019-11-12T17:07:47.372Z	INFO   	xunit-reporter.py	xunit-reporter(72)	main	Uploading results from C:\helix\work\workitem\testResults.xml
Traceback (most recent call last):
  File "C:\helix\work\correlation\xunit-reporter.py", line 94, in <module>
    sys.exit(main())
  File "C:\helix\work\correlation\xunit-reporter.py", line 77, in main
    for line in result_file:
  File "C:\Python\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 670: character maps to <undefined>

[END EXECUTION]
Exit Code:0
```

Most likely this has been around since we moved to Python 3, but until we remove this script it should work for arbitrary valid XMLs.

**Comment by adiaaida** [comment]
Do you have a link to the failing job? I'd like to try to test this and would like to download the xml that is causing this to fail.
