### ISSUE TITLE
Helix test reporter failures in arcade release/3.x branch CI Build

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#4484]
https://dev.azure.com/dnceng/public/_build/results?buildId=445313&view=results
and
https://dev.azure.com/dnceng/public/_build/results?buildId=445255&view=results

The Helix workitem logs will need to be investigated to see what's going on.

**Comment by riarenas** [comment]
Another instance: https://dev.azure.com/dnceng/public/_build/results?buildId=447427

**Comment by MattGal** [comment]
Taking a quick peek, this is due to this exception, seemingly specific to TRX file format.   I'll spend  a few more minutes looking for suspicious stuff. 

```
Searching '/home/helixbot/work/975209e9-8983-428e-9f71-1caa3fd126d5/Work/56184a95-2e99-4921-af15-638cc1dcbc2c/Exec' for test results files
Found results file /home/helixbot/work/975209e9-8983-428e-9f71-1caa3fd126d5/Work/56184a95-2e99-4921-af15-638cc1dcbc2c/Exec/trx-results.2.trx with format trx
Found results file /home/helixbot/work/975209e9-8983-428e-9f71-1caa3fd126d5/Work/56184a95-2e99-4921-af15-638cc1dcbc2c/Exec/trx-results.trx with format trx
Found results file /home/helixbot/work/975209e9-8983-428e-9f71-1caa3fd126d5/Work/56184a95-2e99-4921-af15-638cc1dcbc2c/Exec/trx-results.1.trx with format trx
Worker 0: got error: Traceback (most recent call last):
  File "/home/helixbot/work/975209e9-8983-428e-9f71-1caa3fd126d5/Payload/reporter/run.py", line 40, in run
    self.__process(item)
  File "/home/helixbot/work/975209e9-8983-428e-9f71-1caa3fd126d5/Payload/reporter/run.py", line 31, in __process
    self.publisher.upload_batch(batch)
  File "/home/helixbot/work/975209e9-8983-428e-9f71-1caa3fd126d5/Payload/reporter/azure_devops_result_publisher.py", line 35, in upload_batch
    self.publish_results(test_case_results, test_name_order, results_with_attachments)
  File "/home/helixbot/work/975209e9-8983-428e-9f71-1caa3fd126d5/Payload/reporter/azure_devops_result_publisher.py", line 68, in publish_results
    test_client = connection.get_client("azure.devops.v5_1.test.TestClient")  # type: TestClient
  File "/home/helixbot/.vsts-env/lib/python3.5/site-packages/azure/devops/connection.py", line 45, in get_client
    self._client_cache[client_type] = self._get_client_instance(client_class)
  File "/home/helixbot/.vsts-env/lib/python3.5/site-packages/azure/devops/connection.py", line 58, in _get_client_instance
    url = self._get_url_for_client_instance(client_class)
  File "/home/helixbot/.vsts-env/lib/python3.5/site-packages/azure/devops/connection.py", line 70, in _get_url_for_client_instance
    resource_areas = self._get_resource_areas()
  File "/home/helixbot/.vsts-env/lib/python3.5/site-packages/azure/devops/connection.py", line 119, in _get_resource_areas
    self._resource_areas = location_client.get_resource_areas()
  File "/home/helixbot/.vsts-env/lib/python3.5/site-packages/azure/devops/v5_0/location/location_client.py", line 107, in get_resource_areas
    query_parameters=query_parameters)
  File "/home/helixbot/.vsts-env/lib/python3.5/site-packages/azure/devops/client.py", line 77, in _send
    query_parameters=query_parameters)
  File "/home/helixbot/.vsts-env/lib/python3.5/site-packages/azure/devops/client.py", line 119, in _create_request_message
    location = self._get_resource_location(location_id)
  File "/home/helixbot/.vsts-env/lib/python3.5/site-packages/azure/devops/client.py", line 149, in _get_resource_location
    Client._locations_cache[self.config.base_url] = self._get_resource_locations(all_host_types=False)
  File "/home/helixbot/.vsts-env/lib/python3.5/site-packages/azure/devops/client.py", line 197, in _get_resource_locations
    OPTIONS_FILE_CACHE[self.normalized_url] = wrapper.value
  File "/home/helixbot/.vsts-env/lib/python3.5/site-packages/azure/devops/_file_cache.py", line 93, in __setitem__
    self.save_with_retry()
  File "/home/helixbot/.vsts-env/lib/python3.5/site-packages/azure/devops/_file_cache.py", line 73, in save_with_retry
    self.save()
  File "/home/helixbot/.vsts-env/lib/python3.5/site-packages/azure/devops/_file_cache.py", line 57, in save
    self._save()
  File "/home/helixbot/.vsts-env/lib/python3.5/site-packages/azure/devops/_file_cache.py", line 61, in _save
    with os.fdopen(os.open(self.file_name, os.O_RDWR | os.O_CREAT | os.O_TRUNC, 0o600), 'w+') as cred_file:
PermissionError: [Errno 13] Permission denied: '/home/helixbot/.azure-devops/python-sdk/cache/options.json'

2019-12-03 19:30:28,036: INFO: 140329382795008: run(104): main: Main thread exiting
+ date -u +%FT%TZ
```

**Comment by MattGal** [comment]
Basically this broke because we started doing different sudo vs not-sudo between master and 3.x, on the same machines.  
Since most things use what's in master, we need to get the fix for https://github.com/dotnet/arcade/pull/4403 ported appropriately to all arcade release branches. 

@riarenas do you mind handling this along with trying to understand why the fix was not automatically ported to release branches?

**Comment by riarenas** [comment]
> @riarenas do you mind handling this along with trying to understand why the fix was not automatically ported to release branches?

Yep I'll track the commits that need to be ported. There is no auto porting from master to release for arcade, so this is not surprising.

**Comment by riarenas** [comment]
PR that brings everything in the reporter up to date between master and release/3.x: https://github.com/dotnet/arcade/pull/4509

**Comment by riarenas** [comment]
Latest builds of release/3.x did not see reporter issues so it looks like it was just missing the latest changes: https://dev.azure.com/dnceng/public/_build/results?buildId=450441&view=results
https://dev.azure.com/dnceng/public/_build/results?buildId=450435&view=results 

Will reopen if I see this again.
