### ISSUE TITLE
Arcade Helix Reporter failing to set up Azure.Devops Python libraries on OSX

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#4614]
-  Is this issue blocking (no)
-  Is this issue causing unreasonable pain (debatable)

As reported earlier by @akoeplinger .  I've only seen this on OSX 10.13 thus far but am looking around and will update if I see elsewhere.

The symptom here is that we don't try to reinstall the package because we successfully import azure.devops, then a few seconds later on the same machine fail to import from azure.devops.connection.  Happens on every mac so it's unlikely to be just one machine getting corrupt.

```
+ sudo /Users/helix-runner/.vsts-env/bin/python -c 'import azure.devops'
+ echo 'azure-devops module already available'
azure-devops module already available
+ sudo /Users/helix-runner/.vsts-env/bin/python -c 'import future'
+ echo 'future module already available'
future module already available
+ date -u +%FT%TZ
2020-01-09T17:12:52Z
+ sudo -E /Users/helix-runner/.vsts-env/bin/python /tmp/helix/working/0cec0e64-4ec2-4255-aa31-f4e1ddff307f/Payload/reporter/run.py https://dev.azure.com/dnceng/ public yadayadayada
Traceback (most recent call last):
  File "/tmp/helix/working/0cec0e64-4ec2-4255-aa31-f4e1ddff307f/Payload/reporter/run.py", line 11, in <module>
    from azure_devops_result_publisher import AzureDevOpsTestResultPublisher
  File "/private/tmp/helix/working/0cec0e64-4ec2-4255-aa31-f4e1ddff307f/Payload/reporter/azure_devops_result_publisher.py", line 6, in <module>
    from azure.devops.connection import Connection
ModuleNotFoundError: No module named 'azure'```

**Comment by MattGal** [comment]
I'll chat with @alexperovich to strategize on this later.  I can't find a repro manually (i.e. by running stuff from the virtual env on these machines and importing azure devops junk) and the script hasn't changed in ages, but we could perhaps update to the latest beta at the same time and harden the run.sh scripts.

**Comment by MattGal** [comment]
This has been rolled out for some time, closing.
