### ISSUE TITLE
Occasional failure in helix -- The response contained an invalid status code 500 Internal Server Error

### ISSUE THREAD

**Issue by wli3** [dotnet/arcade#4621]
-  Is this issue blocking  -- No
-  Is this issue causing unreasonable pain -- No

I've seen this failure several times. If this is transient error, could we add retry in the client? 

https://github.com/dotnet/sdk/pull/4145/checks?check_run_id=383971764

```
.packages\microsoft.dotnet.helix.sdk\5.0.0-beta.20058.1\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(53,5): error : (NETCORE_ENGINEERING_TELEMETRY=Helix) RestApiException: The response contained an invalid status code 500 Internal Server Error

Body: {"Message":"An error has occurred."}
   at Microsoft.DotNet.Helix.Client.Job.OnPassFailFailed(Request req, Response res) in /_/src/Microsoft.DotNet.Helix/Client/CSharp/generated-code/Job.cs:line 322
   at Microsoft.DotNet.Helix.Client.Job.PassFailAsync(String job, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Client/CSharp/generated-code/Job.cs:line 302
   at Microsoft.DotNet.Helix.Sdk.WaitForHelixJobCompletion.WaitForHelixJobAsync(String jobName, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Sdk/WaitForHelixJobCompletion.cs:line 38
   at Microsoft.DotNet.Helix.Sdk.WaitForHelixJobCompletion.ExecuteCore(CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Sdk/WaitForHelixJobCompletion.cs:line 26
   at Microsoft.DotNet.Helix.Sdk.HelixTask.Execute() in /_/src/Microsoft.DotNet.Helix/Sdk/HelixTask.cs:line 51
```

@MattGal @alexperovich

**Comment by markwilkie** [comment]
Pretty sure this had to do with a database load issue that we've dealt with.  @MattGal can confirm, but afaik you shouldn't keep seeing this.

**Comment by MattGal** [comment]
Based off the time this happened, yes, we saw this during the load event and also during DTU scale up and down.  The good news is that the libraries used already have a fair amount of retry built in.  I believe this issue can be closed.

**Comment by riarenas** [comment]
This is fallout from https://github.com/dotnet/core-eng/issues/8591. Specifically https://github.com/dotnet/core-eng/issues/8591#issuecomment-573211890 when the DTUs were scaled back down after the problem was resolved. The scaling down caused another interruption right around this time.

@wli3 feel free to reopen, or add more details to the linked core-eng issue if you keep seeing this.

**Comment by riarenas** [comment]
(we all typed around the exact same time.)
