### ISSUE TITLE
Newest Darc can't update Roslyn version to .NET 3 Eng

### ISSUE THREAD

**Issue by agocke** [dotnet/arcade#4775]
-  Is this issue blocking (no)
-  Is this issue causing unreasonable pain (no)

Command: `darc update-dependencies --source-repo arcade --channel ".NET 3 Eng"`

Found in https://github.com/dotnet/arcade/issues/4759

Error as follows:

```
Looking up latest build of https://github.com/dotnet/arcade on .NET 3 Eng
Updating 'Microsoft.DotNet.Arcade.Sdk': '5.0.0-beta.20080.4' => '1.0.0-beta.20077.3' (from build '20200127.3' of 'https://github.com/dotnet/arcade')
Checking for coherency updates...
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Error: Failed to update dependencies to channel .NET 3 Eng
Microsoft.DotNet.Maestro.Client.RestApiException`1[Microsoft.DotNet.Maestro.Client.Models.ApiError]: The response contained an invalid status code 404 Not Found

Body:
   at Microsoft.DotNet.Maestro.Client.Assets.OnListAssetsFailed(Request req, Response res) in /_/src/Maestro/Client/src/Generated/Assets.cs:line 215
   at Microsoft.DotNet.Maestro.Client.Assets.ListAssetsPageAsync(Nullable`1 buildId, Nullable`1 loadLocations, String name, Nullable`1 nonShipping, Nullable`1 page, Nullable`1 perPage, String version, CancellationToken cancellationToken) in /_/src/Maestro/Client/src/Generated/Assets.cs:line 180
   at Microsoft.DotNet.Maestro.Client.Assets.<>c__DisplayClass6_0.<<ListAssetsAsync>g__GetPages|0>d.MoveNext() in /_/src/Maestro/Client/src/Generated/Assets.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.Maestro.Client.Assets.<>c__DisplayClass6_0.<<ListAssetsAsync>g__GetPages|0>d.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.DotNet.Maestro.Client.AsyncEnumerable.ToListAsync[T](IAsyncEnumerable`1 that, CancellationToken cancellationToken) in /_/src/Maestro/Client/src/Generated/PagedResponse.cs:line 15
   at Microsoft.DotNet.Maestro.Client.AsyncEnumerable.ToListAsync[T](IAsyncEnumerable`1 that, CancellationToken cancellationToken) in /_/src/Maestro/Client/src/Generated/PagedResponse.cs:line 15
   at Microsoft.DotNet.DarcLib.MaestroApiBarClient.GetAssetsAsync(String name, String version, Nullable`1 buildId, Nullable`1 nonShipping) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/MaestroApiBarClient.cs:line 308
   at Microsoft.DotNet.DarcLib.Remote.AddAssetLocationToDependenciesAsync(IEnumerable`1 dependencies) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs:line 1157
   at Microsoft.DotNet.DarcLib.Local.UpdateDependenciesAsync(List`1 dependencies, IRemoteFactory remoteFactory) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs:line 64
   at Microsoft.DotNet.Darc.Operations.UpdateDependenciesOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateDependenciesOperation.cs:line 226
```

**Comment by riarenas** [comment]
We were tracking this as https://github.com/dotnet/arcade/issues/4728 but it looks like it got closed by mistake. Darc is already fixed, but the endpoint that returns which Darc version we recommend to install to the `darc-init` scripts needs to be updated with a deployment (which we're targetting for next week)

as a workaround, a version parameter can be specified to the install scripts, and any version equal or newer than 1.1.0-beta.20081.2 already has the fixes.

`eng/common/darc-init.ps1 -darcVersion 1.1.0-beta.20081.2`

Closing this in favor of the other issue that has some more information on what happened.
