### ISSUE TITLE
Something isn't correct in Tasks.Feed

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4866]
-  Is this issue blocking: yes
-  Is this issue causing unreasonable pain: yes

Tasks.Feed is failing with the error messages below when we try to use the latest version to publish assets. First noticed the error in the [build promotion pipeline](https://dnceng.visualstudio.com/internal/_build?definitionId=750&_a=summary) but then I was able to repro it locally.

```
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20116.1\tools\SdkTasks\PublishArtifactsInManifest.proj(66,5): error : Unable to upload to assets/symbols/Microsoft.DotNet.Build.Tasks.Packaging.5.0.0-beta.20118.3.symbols.nupkg due to Azure.RequestFailedException: The specified blob does not exist.
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20116.1\tools\SdkTasks\PublishArtifactsInManifest.proj(66,5): error : Status: 404 (The specified blob does not exist.)
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20116.1\tools\SdkTasks\PublishArtifactsInManifest.proj(66,5): error : 
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20116.1\tools\SdkTasks\PublishArtifactsInManifest.proj(66,5): error : ErrorCode: BlobNotFound
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20116.1\tools\SdkTasks\PublishArtifactsInManifest.proj(66,5): error : 
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20116.1\tools\SdkTasks\PublishArtifactsInManifest.proj(66,5): error : Headers:
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20116.1\tools\SdkTasks\PublishArtifactsInManifest.proj(66,5): error : Transfer-Encoding: chunked
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20116.1\tools\SdkTasks\PublishArtifactsInManifest.proj(66,5): error : Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20116.1\tools\SdkTasks\PublishArtifactsInManifest.proj(66,5): error : x-ms-request-id: 7918af1e-301e-0003-25be-e6b290000000
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20116.1\tools\SdkTasks\PublishArtifactsInManifest.proj(66,5): error : x-ms-client-request-id: c626e230-f403-4710-bc29-7c305ca024c9
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20116.1\tools\SdkTasks\PublishArtifactsInManifest.proj(66,5): error : x-ms-version: 2019-02-02
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20116.1\tools\SdkTasks\PublishArtifactsInManifest.proj(66,5): error : x-ms-error-code: BlobNotFound
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20116.1\tools\SdkTasks\PublishArtifactsInManifest.proj(66,5): error : Date: Wed, 19 Feb 2020 00:51:11 GMT
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20116.1\tools\SdkTasks\PublishArtifactsInManifest.proj(66,5): error : 
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20116.1\tools\SdkTasks\PublishArtifactsInManifest.proj(66,5): error :    at Azure.Storage.Blobs.BlobRestClient.Blob.GetPropertiesAsync_CreateResponse(Response response)
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20116.1\tools\SdkTasks\PublishArtifactsInManifest.proj(66,5): error :    at Azure.Storage.Blobs.BlobRestClient.Blob.GetPropertiesAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, String version, String snapshot, Nullable`1 timeout, String leaseId, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, Nullable`1 ifMatch, Nullable`1 ifNoneMatch, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20116.1\tools\SdkTasks\PublishArtifactsInManifest.proj(66,5): error :    at Azure.Storage.Blobs.Specialized.BlobBaseClient.GetPropertiesInternal(BlobRequestConditions conditions, Boolean async, CancellationToken cancellationToken)
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20116.1\tools\SdkTasks\PublishArtifactsInManifest.proj(66,5): error :    at Azure.Storage.Blobs.Specialized.BlobBaseClient.GetPropertiesAsync(BlobRequestConditions conditions, CancellationToken cancellationToken)
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20116.1\tools\SdkTasks\PublishArtifactsInManifest.proj(66,5): error :    at Microsoft.DotNet.Build.CloudTestTasks.AzureStorageUtils.IsFileIdenticalToBlobAsync(String localFileFullPath, BlobClient blob) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/common/AzureStorageUtils.cs:line 89
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20116.1\tools\SdkTasks\PublishArtifactsInManifest.proj(66,5): error :    at Microsoft.DotNet.Build.CloudTestTasks.AzureStorageUtils.IsFileIdenticalToBlobAsync(String localFileFullPath, String blobPath) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/common/AzureStorageUtils.cs:line 75
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20116.1\tools\SdkTasks\PublishArtifactsInManifest.proj(66,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.BlobFeedAction.UploadAssetAsync(ITaskItem item, SemaphoreSlim clientThrottle, PushOptions options) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/BlobFeedAction.cs:line 181.
```

I could repro the issue locally by: Cloned the Arcade master branch and build a local copy of Tasks.Feed and tried to use it to publish a package to dotnetfeed/dotnet-core.

/cc @riarenas @mmitche @MattGal

**Comment by MattGal** [comment]
I thought I was fixing a bug in that the function signatures in the original thing were swapped; I un-swapped them and fixed up all the usages I could find.   Assuming we control them, would it not be more correct to change the callers then to revert back to this?

**Comment by markwilkie** [comment]
Is this affecting our customers?

**Comment by JohnTortugo** [comment]
I think not yet, because no one was using this version of the package.

**Comment by riarenas** [comment]
I haven't seen these symptoms anywhere except the build promotion pipeline.
