### ISSUE TITLE
[darc/Maestro++] Passing an invalid Github PAT to darc  causes operations to hang for a long time before reporting an error

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#4882]
-  Is this issue blocking no
-  Is this issue causing unreasonable pain no

Steps:
* Call `darc-add-default-channel` with an incorrect or invalid GitHub PAT, either from storing it via `darc-authenticate`, or passing it with the `github-pat` option.
* Wait 15 minutes
* Get this call stack:
```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs:line 80
   at Microsoft.DotNet.DarcLib.GitHubClient.ExecuteRemoteGitCommandAsync(HttpMethod method, String requestUri, ILogger logger, String body, String versionOverride, Int32 retryCount, Boolean logFailure) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs:line 512
   at Microsoft.DotNet.DarcLib.GitHubClient.GetFileContentsAsync(String owner, String repo, String filePath, String branch) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs:line 97
   at Microsoft.DotNet.DarcLib.GitHubClient.GetFileContentsAsync(String filePath, String repoUri, String branch) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs:line 78
   at Microsoft.DotNet.DarcLib.GitFileManager.ReadXmlFileAsync(String filePath, String repoUri, String branch) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs:line 579
   at Microsoft.DotNet.DarcLib.GitFileManager.ReadVersionDetailsXmlAsync(String repoUri, String branch) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs:line 62
   at Microsoft.DotNet.DarcLib.GitFileManager.ParseVersionDetailsXmlAsync(String repoUri, String branch, Boolean includePinned) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs:line 118
   at Microsoft.DotNet.DarcLib.Remote.GetDependenciesAsync(String repoUri, String branchOrCommit, String name, Boolean loadAssetLocations) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs:line 1018
   at Microsoft.DotNet.Darc.UxHelpers.VerifyAndConfirmBranchExistsAsync(IRemote remote, String repo, String branch, Boolean prompt) in /_/src/Microsoft.DotNet.Darc/src/Darc/Helpers/UxHelpers.cs:line 269
   at Microsoft.DotNet.Darc.Operations.AddDefaultChannelOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/AddDefaultChannelOperation.cs:line 29
```

We should fail this quicker, and provide a more helpful error message.

**Comment by JohnTortugo** [comment]
Can we just abort the retries if the error is a 401? I don't think there is a stroong case to retry on such errors.

**Comment by riarenas** [comment]
Yep, that makes sense. I'm pretty sure this is taking so long due to keep retrying forever.

**Comment by JohnTortugo** [comment]
Yeah, I had noticed it in my tests locally. It retries by default 15 times..
