### ISSUE TITLE
darc update-dependencies error

### ISSUE THREAD

**Issue by wli3** [dotnet/arcade#4889]
Checkout dotnet core sdk release/3.1.2xx

`darc update-dependencies --coherency-only`
```
warn: Microsoft.DotNet.Darc.Operations.Operation[0]
      https://github.com/dotnet/corefx@7ee84596d92e178bce54c986df31ccc52479e772  does not have an eng/Version.Details.xml.
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Something failed while trying the fetch the dependencies of repo 'https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int' at sha '335ce71fcb05fe54c4885d1ec246e48f9a1969b6'
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Microsoft.DotNet.DarcLib.AzureDevOpsClient.ExecuteAzureDevOpsAPIRequestAsync(HttpMethod method, String accountName, String projectName, String requestPath, ILogger logger, String body, String versionOverride, Boolean logFailure, String baseAddressSubpath, Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs:line 775
```

**Comment by wli3** [comment]
So is  darc update-dependencies --channel ".NET Core SDK 3.1.2xx"

```
Looking up latest build of https://github.com/dotnet/core-setup on .NET Core SDK 3.1.2xx
Looking up latest build of https://github.com/dotnet/aspnetcore on .NET Core SDK 3.1.2xx
Looking up latest build of https://github.com/dotnet/test-templates on .NET Core SDK 3.1.2xx
Looking up latest build of https://github.com/dotnet/toolset on .NET Core SDK 3.1.2xx
Looking up latest build of https://github.com/dotnet/wcf on .NET Core SDK 3.1.2xx
Looking up latest build of https://github.com/dotnet/arcade on .NET Core SDK 3.1.2xx
Checking for coherency updates...
warn: Microsoft.DotNet.Darc.Operations.Operation[0]
      https://github.com/dotnet/corefx@7ee84596d92e178bce54c986df31ccc52479e772  does not have an eng/Version.Details.xml.
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Something failed while trying the fetch the dependencies of repo 'https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int' at sha '335ce71fcb05fe54c4885d1ec246e48f9a1969b6'
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Microsoft.DotNet.DarcLib.AzureDevOpsClient.ExecuteAzureDevOpsAPIRequestAsync(HttpMethod method, String accountName, String projectName, String requestPath, ILogger logger, String body, String versionOverride, Boolean logFailure, String baseAddressSubpath, Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs:line 775
```

**Comment by riarenas** [comment]
I'm not able to repro this, could it be an out of date darc client? `eng/common/darc-init.ps1` should bring in version `1.1.0-beta.20119.2`

**Comment by wli3** [comment]
I did have the latest darc. Although it is no longer repro today too.

**Comment by wli3** [comment]
@riarenas thanks for looking into it
