### ISSUE TITLE
[Darc/Maestro++] Darc add-build-to-channel should fail early if we can detect a problem with the original build

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#4941]
-  Is this issue blocking no
-  Is this issue causing unreasonable pain no

If the build that we want to promote to a channel has been deleted or its artifacts are no longer available, we shouldn't queue the promotion pipeline, as it will undoubtedly fail after wasting some machine time.

**Comment by riarenas** [comment]
This still requires some work. I got the following issues when trying to use `darc-add-build-to-channel` with some invalid configurations:

```
darc add-build-to-channel --id 45596 --channel "General Testing"
Assigning the following build to channel 'General Testing':

Repository:    https://github.com/dotnet/arcade
Branch:        master
Commit:        8cb24a8375c73609de8532a02a3b18e3852044d2
Build Number:  20200311.4
Date Produced: 3/11/2020 2:09 PM
Build Link:    https://dev.azure.com/dnceng/internal/_build/results?buildId=556205
BAR Build Id:  45596
Released:      False
Channels:
- .NET Eng - Latest
- .NET Eng - Validation
warn: Microsoft.DotNet.Darc.Operations.Operation[0]
      There was an error executing method 'GET' against URI '_apis/build/builds/556205/artifacts'. 5 attempts remaining. Exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs:line 80
```

Which suggests we're not going through the code path that gives a better error when a PAT lacks the required auth scopes.

```
darc add-build-to-channel --id 45381 --channel ".NET Core Tooling Dev" --source-branch master --source-sha d4c0251698a93a9b708f183a21b7a39834f5c0b6
Assigning the following build to channel '.NET Core Tooling Dev':

Repository:    https://github.com/microsoft/vstest
Branch:        master
Commit:        3726dae401bd4ca1e8cbe16d869cab5e9d673ed6
Build Number:  20200310-03
Date Produced: 3/10/2020 5:04 AM
Build Link:    https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3538796
BAR Build Id:  45381
Released:      False
Channels:
The build that you want to add to a new channel doesn't have a Build Manifest. That's required for publishing. Aborting.Build 45381 will be assigned to channel '.NET Core Tooling Dev' once this build finishes publishing assets: https://dnceng.visualstudio.com/internal/_build/results?buildId=557020
Waiting '60' seconds for promotion build to complete.
Waiting '60' seconds for promotion build to complete.
```

The resulting build promotion piepeline failed for two reasons: 
* We still haven't hooked up darc-add-build-to-channel to the devdiv promotion pipeline when promoting a devdiv build (known issue): https://github.com/dotnet/arcade/issues/4986
* Looks like there's a bug in the changes from https://github.com/dotnet/arcade-services/pull/1008 as we said we were aborting the operation, but still kept going, even though we knew this was going to fail due to the lack of a build manifest.

**Comment by riarenas** [comment]
I'll work on this alongside #4896 since @johntortugo is on FR

**Comment by riarenas** [comment]
Still working on this one. Split it from https://github.com/dotnet/arcade-services/pull/1048 to unblock that scenario in case I don't get this one working in time for deployment this week.

**Comment by riarenas** [comment]
dotnet/arcade-services#1048  now has the changes for this.
