### ISSUE TITLE
[darc/maestro++] Maestro tests failing for dependency flow Prs that don't include changes to global.json

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5245]
- [x] This issue is blocking 
This issue blocks deployment of arcade-services
- [ ] This issue is causing unreasonable pain

Looks like there's a problem with https://github.com/dotnet/arcade-services/pull/1094. After that change scenario tests are failing because they fail to open any dependency update PRs.

The logs show the following call stack:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at SubscriptionActorService.PullRequestActorImplementation.UpdatePRDescriptionDueConfigFiles(List`1 commitedFiles, StringBuilder globalJsonSection) in /_/src/Maestro/SubscriptionActorService/PullRequestActor.cs:line 837
   at SubscriptionActorService.PullRequestActorImplementation.CalculatePRDescription(UpdateAssetsParameters update, List`1 deps, List`1 committedFiles, StringBuilder description) in /_/src/Maestro/SubscriptionActorService/PullRequestActor.cs:line 952
   at SubscriptionActorService.PullRequestActorImplementation.CommitUpdatesAsync(List`1 requiredUpdates, StringBuilder description, IRemote darc, String targetRepository, String newBranchName) in /_/src/Maestro/SubscriptionActorService/PullRequestActor.cs:line 817
   at SubscriptionActorService.PullRequestActorImplementation.CreatePullRequestAsync(List`1 updates) in /_/src/Maestro/SubscriptionActorService/PullRequestActor.cs:line 695
   at SubscriptionActorService.PullRequestActorImplementation.CreatePullRequestAsync(List`1 updates) in /_/src/Maestro/SubscriptionActorService/PullRequestActor.cs:line 767
   at SubscriptionActorService.PullRequestActorImplementation.UpdateAssetsAsync(Guid subscriptionId, Int32 buildId, String sourceRepo, String sourceSha, List`1 assets) in /_/src/Maestro/SubscriptionActorService/PullRequestActor.cs:line 606
   at SubscriptionActorService.ActionRunner.InvokeAction[T](IActionTracker target, ActionMethod method, Object[] arguments) in /_/src/Maestro/SubscriptionActorService/ActionRunner/ActionRunner.cs:line 0
```

We're probably not checking correctly if the global.json file is part of the updates?

Sample failing build: https://dnceng.visualstudio.com/internal/_build/results?buildId=595187&view=results

**Comment by riarenas** [comment]
CC @JohnTortugo

**Comment by riarenas** [comment]
Verified that the fix sticked, and the tests are passing again. Thanks @JohnTortugo
