### ISSUE TITLE
RemoteExecutor crashes with "`AbandonedMutexException`: The wait completed due to an abandoned mutex."

### ISSUE THREAD

**Issue by RussKie** [dotnet/arcade#5325]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

Version: **5.0.0-beta.20201.2**

Windows Forms has a number of tests that rely on `RemoteExecutor`. Yesterday all of the sudden we tests started randomly crashing with either ([System.Windows.Forms.Tests_netcoreapp5.0_x64.log](https://dev.azure.com/dnceng/public/_build/results?buildId=610393&view=artifacts&type=publishedArtifacts)):
```
Unhandled exception. System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout)
   at System.Threading.WaitHandle.WaitOne()
   at Coverlet.Core.Instrumentation.Tracker.System.Windows.Forms_4cd81754-6b57-47be-9c9b-f84bb7e27431.UnloadModule(Object , EventArgs )
   at System.AppContext.OnProcessExit()
    System.Windows.Forms.Tests.ParkingWindowTests.ParkingWindow_DoesNotThrowOnGarbageCollecting [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   -532462766
      Stack Trace:
        D:\a\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\Application.ParkingWindowTests.cs(37,0): at System.Windows.Forms.Tests.ParkingWindowTests.ParkingWindow_DoesNotThrowOnGarbageCollecting()
    System.Windows.Forms.Layout.Tests.TableLayoutSettingsTests.TableLayoutSettings_Serialize_InvalidStringConverter_DeserializeThrowsTargetInvocationException [SKIP]
      Expected Exception has changed to System.Runtime.Serialization.SerializationException
    System.Windows.Forms.Tests.AxHostTests.AxHost_GetIPictureDispFromPicture_InvokeEnhancedMetafile_Roundtrips [SKIP]
      Expected Exception is COMException - not TargetInvocationException
    System.Windows.Forms.Tests.ToolStripDropDownTests.ToolStripDropDown_KeyboardAccelerators_Test [SKIP]
      Suspect causing deadlocks, see: https://github.com/dotnet/winforms/issues/3095
  Finished:    System.Windows.Forms.Tests
```
or ([System.Windows.Forms.Tests_netcoreapp5.0_x64.log](https://dev.azure.com/dnceng/public/_build/results?buildId=611135&view=artifacts&type=publishedArtifacts)):
```
    System.Windows.Forms.Tests.ApplicationTests.Application_EnableVisualStyles_InvokeBeforeGettingRenderWithVisualStyles_Success [FAIL]
      Half-way through waiting for remote process.
      Memory load: 23
      
      Image Name                     PID Services                                    
      ========================= ======== ============================================
      svchost.exe                    916 PlugPlay                                    
      svchost.exe                    964 BrokerInfrastructure, DcomLaunch, Power,    
                                         SystemEventsBroker                          
      svchost.exe                    500 RpcEptMapper, RpcSs                         
      svchost.exe                    636 LSM                                         
      svchost.exe                   1164 TermService                                 
      svchost.exe                   1208 lmhosts                                     
      svchost.exe                   1216 CoreMessagingRegistrar                      
      svchost.exe                   1288 Schedule                                    
      svchost.exe                   1304 NcbService                                  
      svchost.exe                   1328 TimeBrokerSvc                               
      svchost.exe                   1400 ProfSvc                                     
      svchost.exe                   1500 EventLog                                    
      svchost.exe                   1532 UmRdpService                                
      svchost.exe                   1552 UserManager                                 
      svchost.exe                   1620 nsi                                         
      svchost.exe                   1744 vmicheartbeat                               
      svchost.exe                   1752 vmickvpexchange                             
      svchost.exe                   1772 Dhcp                                        
      svchost.exe                   1780 vmicrdv                                     
      svchost.exe                   1808 vmicshutdown                                
      svchost.exe                   1908 vmicvss                                     
      svchost.exe                   1916 vmictimesync                                
      svchost.exe                   1108 CertPropSvc                                 
      svchost.exe                   2068 EventSystem                                 
      svchost.exe                   2076 SysMain                                     
      svchost.exe                   2116 Themes                                      
      svchost.exe                   2248 LanmanWorkstation                           
      svchost.exe                   2292 NlaSvc                                      
      svchost.exe                   2308 SENS                                        
      svchost.exe                   2384 AudioEndpointBuilder                        
      svchost.exe                   2392 Dnscache                                    
      svchost.exe                   2420 FontCache                                   
      svchost.exe                   2428 SessionEnv                                  
      svchost.exe                   2516 Audiosrv                                    
      svchost.exe                   2580 netprofm                                    
      svchost.exe                   2736 DusmSvc                                     
      svchost.exe                   2748 Wcmsvc                                      
      svchost.exe                   2828 ShellHWDetection                            
Unhandled exception.       svchost.exe                   2900 WinHttpAutoProxySvc                         
      svchost.exe                   3008 BFE, mpssvc                                 
      svchost.exe                   3140 SEMgrSvc                                    
      svchost.exe                   3224 CryptSvc                                    
      svchost.exe                   3232 DiagTrack                                   
      svchost.exe                   3244 DPS                                         
      svchost.exe                   3280 Winmgmt                                     
      svchost.exe                   3320 LanmanServer                                
      svchost.exe                   3424 TrkWks                                      
      svchost.exe                   3432 W32Time                                     
      svchost.exe                   3544 WinRM                                       
      svchost.exe                   3612 WpnService                                  
      svchost.exe                   3636 iphlpsvc                                    
      svchost.exe                   3688 WdiServiceHost                              
      svchost.exe                   4368 PolicyAgent                                 
      svchost.exe                   4640 StateRepository                             
      svchost.exe                   5060 CDPUserSvc_4247c                            
      svchost.exe                   5104 WpnUserService_4247c                        
      svchost.exe                   3080 TokenBroker                                 
      svchost.exe                   5176 TabletInputService                          
      svchost.exe                   5300 CDPSvc                                      
      svchost.exe                   5564 cbdhsvc_4247c                               
      svchost.exe                   6500 LicenseManager                              
      svchost.exe                   6648 WarpJITSvc                                  
      svchost.exe                   7292 pla                                         
      svchost.exe                   7244 SSDPSRV                                     
      svchost.exe                   8816 Appinfo                                     
      svchost.exe                   9020 PcaSvc                                      
      svchost.exe                   5432 WdiSystemHost                               
      svchost.exe                   3600 wuauserv                                    
      svchost.exe                   7160 DoSvc                                       
      svchost.exe                   5584 StorSvc                                     
      svchost.exe                   8172 UsoSvc                                      
      svchost.exe                   7388 wscsvc                                      
      svchost.exe                   6720 OneSyncSvc_4247c                            
      svchost.exe                    452 NgcSvc                                      
      svchost.exe                   8440 NgcCtnrSvc                                  
      svchost.exe                   8524 gpsvc                                       
      Timed out at 4/22/2020 1:28:05 AM after 60000ms waiting for remote process.
      Wrote mini dump to: F:\h\w\B2D20A03\w\C1B00A1B\uploads\9308.1u2vt2qb.ljc.dmp
      	Process ID: 9308
      	Handle: 9888
      	Name: dotnet
      	MainModule: F:\workspace\_work\1\s\.dotnet\dotnet.exe
      	StartTime: 4/22/2020 1:26:52 AM
      	TotalProcessorTime: 00:01:04.8281250
      
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(219,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(54,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        F:\workspace\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ApplicationTests.cs(17,0): at System.Windows.Forms.Tests.ApplicationTests.Application_EnableVisualStyles_InvokeBeforeGettingRenderWithVisualStyles_Success()
System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout)
   at System.Threading.WaitHandle.WaitOne()
   at Coverlet.Core.Instrumentation.Tracker.System.Windows.Forms.Primitives_27ec1ab9-8067-4be0-9359-fb23fef04f49.UnloadModule(Object , EventArgs )
   at System.AppContext.OnProcessExit()
```

I can only guess that something in .NET runtime has changed that started causing this.

**Comment by ViktorHofer** [comment]
cc @stephentoub

**Comment by stephentoub** [comment]
> I can only guess that something in .NET runtime has changed that started causing this.

Did Coverlet get updated to a new version?  I'm guessing it's actually what changed.  Note the exception is coming from a call to WaitHandle.WaitOne in
Coverlet.Core.Instrumentation.Tracker.System.Windows.Forms.Primitives_27ec1ab9-8067-4be0-9359-fb23fef04f49.UnloadModule.  This exception means that this code is trying to Mutex.WaitOne on a Mutex that a thread in the process was holding when the thread went away.

**Comment by ViktorHofer** [comment]
FWIW WinForms is using coverlet.msbuild which suffers from the following problem: https://github.com/tonerdo/coverlet/blob/master/Documentation/KnownIssues.md#1-vstest-stops-process-execution-earlydotnet-test.

The recommended workflow is to use coverlet.collectors in combination with dotnet test as coverlet is available as an in-built data collector there. See an example of how we are doing this in dotnet/runtime: https://github.com/dotnet/runtime/pull/35285/files#diff-5452375519a6101f774bd1f882257923R45-R59

**Comment by ViktorHofer** [comment]
Are you using xunit.console or VSTest in dotnet/winforms?

**Comment by weltkante** [comment]
They are using xunit from console (possibly indirectly through msbuild invoked from command line) - I'm also trying to get things working with xunit inside VS though. If `VSTest` refers to the test framework, I don't think so, as far as I'm aware its all xunit.

**Comment by ViktorHofer** [comment]
https://github.com/dotnet/arcade/pull/5347 should enable VSTest (which is the test runner and supports various test frameworks like xunit, nunit and mstest) in "arcadified" repos. After that change is in, winforms would ideally switch from the xunit.console runner to VSTest, add a .runsettings file with a coverlet data collector configuration node and reference the coverlet.collectors nuget package in the test projects.

**Comment by ViktorHofer** [comment]
> Did Coverlet get updated to a new version, or did we change how we're using it?

The version hasn't changed in the last five months: https://github.com/dotnet/winforms/blame/master/eng/Versions.props#L59. Also from the git history I don't see any changes in how it's being used.

**Comment by danmosemsft** [comment]
> FWIW WinForms is using coverlet.msbuild which suffers from the following problem: https://github.com/tonerdo/coverlet/blob/master/Documentation/KnownIssues.md#1-vstest-stops-process-execution-earlydotnet-test.

That page indicates that vstest terminates the process which it does with [process.Kill](https://github.com/microsoft/vstest/blob/499b57b2def50400614221db6334f26dd89336d3/src/Microsoft.TestPlatform.PlatformAbstractions/common/System/ProcessHelper.cs#L169) which calls TerminateProcess. I wouldn't expect that to end up causing one thread to exit but allow another to continue (and throw). Perhaps someone can correct me if my assumption is wrong.

I guess while the thread is waiting in OnProcessExit, an exception occurred in the Coverlet thread in UnloadModule for some reason, and since the lock is not released [in a finally](https://github.com/tonerdo/coverlet/blob/528a769c9ab98762935490372e40720ed7219618/src/coverlet.core/Instrumentation/ModuleTrackerTemplate.cs#L142) there is a chance for the waiting thread to get scheduled and throw and kill the process before the first exception has bubbled up and killed the process.

If so I would expect the original exception to be in this log but it isn't gathered as part of the test run
https://github.com/tonerdo/coverlet/blob/528a769c9ab98762935490372e40720ed7219618/src/coverlet.core/Instrumentation/ModuleTrackerTemplate.cs#L186

**Comment by RussKie** [comment]
> Are you using xunit.console or VSTest in dotnet/winforms?

> After that change is in, winforms would ideally switch from the xunit.console runner to VSTest, add a .runsettings file with a coverlet data collector configuration node and reference the coverlet.collectors nuget package in the test projects.

We use whatever Arcade is providing us with, so if something needs changing I would expect it to be facilitated by the Arcade.


> Can we gather it? It's next to the executing binary.

I will need to guidance on how to do it. If this is something controlled by Arcade, it would be great if it is done in it too.

. . .

I was unable to replicate failures locally, they only appear to be happening on public builds in `Azure Pipelines` pool on `windows-2019-vs2019` image.
We have moved the master branch to `NetCorePublic-Pool` pool, and I haven't observed any issues in it, but we've disabled the RE tests at the same time. The release/5.0-preview4 branch is still being built in the old pool, and it has the tests enabled.

I'll see if I get the errors by moving release/5.0-preview4 branch to `NetCorePublic-Pool` pool.

**Comment by danmosemsft** [comment]
The log is written with
```
string location = Assembly.GetExecutingAssembly().Location;
 File.AppendAllText(Path.Combine(Path.GetDirectoryName(location), Path.GetFileName(location) + "_tracker.txt"), $"[{DateTime.UtcNow} P:{Process.GetCurrentProcess().Id} T:{Thread.CurrentThread.ManagedThreadId}]{logText}{Environment.NewLine}");
```
So I would expect it to be next to Coverlet.core.dll (?) and named something like "Coverlet.core.dll_tracker.txt"

@ViktorHofer is there a way to gather that file?

**Comment by ericstj** [comment]
This looks similar to dotnet/runtime#13610
