### ISSUE TITLE
NullReferenceException in GenerateAzureDevOpsBuildManifest Task

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5356]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Some Arcade update PRs are blocked right now with the error:

```
.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20221.14\tools\Publish.proj(250,5): error MSB4018: The "GenerateAzureDevOpsBuildManifest" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.AzureDevOps.Build.GenerateAzureDevOpsBuildManifest.Execute() in /_/src/Microsoft.DotNet.AzureDevOps.Build/src/GenerateBuildManifest.cs:line 47
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

This has already been fixed in https://github.com/dotnet/arcade/pull/5327, but didn't make it in the last Arcade update since Arcade's pipeline was blocked due to https://github.com/dotnet/arcade/issues/5328

FYI @missymessa

**Comment by ryanbrandenburg** [comment]
Sounds like the fix is already in, but [here's an instance of this](https://dev.azure.com/dnceng/public/_build/results?buildId=618958&view=logs&j=0bc77094-9fcd-5c38-f6e4-27d2ae131589&t=108c10b7-2c4b-5297-f2c3-f882c6024b18) if it's helpful.

**Comment by riarenas** [comment]
The fix is in, and should be in tomorrow's Arcade update PRs.

**Comment by riarenas** [comment]
Verfied that repos received this arcade update this morning. I triggered the efcore subscription manually since they wouldn't see the fix until next week due to how their subscription is set up.
