### ISSUE TITLE
[darc/maestro++] darc-add-build-to-channel fails when trying to publish to the .net core sdk 3.1.4xx channel

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5360]
- [ ] This issue is blocking 
This is blocking Nuget Insertions into the `.net core sdk 3.1.4xx` channel
- [ ] This issue is causing unreasonable pain

The master branch does not have a publishing implementation for this channel, and attempting to use the release/3.x branch to publish results in an error:

```
darc add-build-to-channel --id 50086 --channel ".NET Core SDK 3.1.4xx" --source-branch release/3.x
Assigning build '50086' to the following channel(s):
        .NET Core SDK 3.1.4xx

Repository:    https://github.com/NuGet/NuGet.Client
Branch:        dev
Commit:        4dbf16e68eabf507b9f156c801b1b7c3b0586e43
Build Number:  5.7.0.6592
Date Produced: 4/25/2020 8:36 AM
Build Link:    https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3675895
BAR Build Id:  50086
Released:      False
Channels:
- .NET 5 Dev
- .NET 5 Preview 5
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      A '400 - BadRequest' status was returned for a HTTP request. We'll set the retries amount to 0. Error details: {"$id":"1","customProperties":{"ValidationResults":[{"result":"error","message":"An error occurred while loading the YAML build pipeline. Could not find /eng/promote-build.yml in repository self hosted on http://github.com/ using commit 769daba9e277df504e79c05008bcb7687c60de53. GitHub reported the error, \"Not Found\""}]},"innerException":null,"message":"Could not queue the build because there were validation errors or warnings.","typeName":"Microsoft.TeamFoundation.Build.WebApi.BuildRequestValidationFailedException, Microsoft.TeamFoundation.Build2.WebApi","typeKey":"BuildRequestValidationFailedException","errorCode":0,"eventId":3000}
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      There was an error executing method 'POST' against URI '_apis/build/builds/' after 0 attempts. Exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs:line 85
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Error: Failed to assign build '50086' to channel '.NET Core SDK 3.1.4xx'.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs:line 85
   at Microsoft.DotNet.DarcLib.AzureDevOpsClient.ExecuteAzureDevOpsAPIRequestAsync(HttpMethod method, String accountName, String projectName, String requestPath, ILogger logger, String body, String versionOverride, Boolean logFailure, String baseAddressSubpath, Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs:line 789
   at Microsoft.DotNet.DarcLib.AzureDevOpsClient.StartNewBuildAsync(String accountName, String projectName, Int32 azdoDefinitionId, String sourceBranch, String sourceVersion, String queueTimeVariables) in /_/src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs:line 1117
   at Microsoft.DotNet.Darc.Operations.AddBuildToChannelOperation.PromoteBuildAsync(Build build, List`1 targetChannels, IRemote remote) in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs:line 211
   at Microsoft.DotNet.Darc.Operations.AddBuildToChannelOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs:line 113
```

We should figure out why we're not able to use the release/3.x branch for build promotion, but we should also keep the publishing implementation for the current 3.x core sdk  channel.

**Comment by riarenas** [comment]
https://github.com/dotnet/arcade/pull/5359 adds publishing to 3.1.4xx from master.

**Comment by riarenas** [comment]
This is no longer blocking NuGet, but we should fix build promotion publishing from the release/3.x branch.

**Comment by riarenas** [comment]
The way we've been resolving these is by adding the channels to master. Publishing v3 will solve this by using a dedicated publishing branch of arcade.
