### ISSUE TITLE
Can't push newest Roslyn build to .NET 5 Preview 3

### ISSUE THREAD

**Issue by agocke** [dotnet/arcade#5408]
- [X] This issue is blocking 
- [X] This issue is causing unreasonable pain

Trying to push the latest build to .NET 5 Preview 3.

```
Assigning build '50041' to the following channel(s):
        .NET 5 Preview 3

Repository:    https://github.com/dotnet/roslyn
Branch:        release/dev16.6-vs-deps
Commit:        3d85b48dd5e533c7d47e916e2cff417f46bdce10
Build Number:  20200424.5
Date Produced: 4/24/2020 3:43 PM
Build Link:    https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3673940
BAR Build Id:  50041
Released:      False
Channels:
- .NET Core SDK 3.1.3xx
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
id":"1","customProperties":{"ValidationResults":[{"result":"error","message":"An error occurred while loading the YAML build pipeline. Could not find /eng/promote-build.yml in repository self hosted on http://github.com/ using commit f6dc83c016f91377a2f3f3d44f08f326652a0337. GitHub reported the error, \"Not Found\""}]},"innerException":null,"message":"Could not queue the build because there were validation errors or warnings.","typeName":"Microsoft.TeamFoundation.Build.WebApi.BuildRequestValidationFailedException, Microsoft.TeamFoundation.Build2.WebApi","typeKey":"BuildRequestValidationFailedException","errorCode":0,"eventId":3000}
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      There was an error executing method 'POST' against URI '_apis/build/builds/' after 0 attempts. Exception: System.N         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs:line 85
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Error: Failed to assign build '50041' to channel '.NET 5 Preview 3'.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs:line 85
   at Microsoft.DotNet.DarcLib.AzureDevOpsClient.ExecuteAzureDevOpsAPIRequestAsync(HttpMethod method, String accountName, String projectName, String requestPath, ILogger logger, String body, String versionOverride, Boolean logFailure, String baseAddressSubpath, Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs:line 789
   at Microsoft.DotNet.DarcLib.AzureDevOpsClient.StartNewBuildAsync(String accountName, String projectName, Int32 azdoDefinitionId, String sourceBranch, String sourceVersion, String queueTimeVariables) in /_/src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs:line 1117
   at Microsoft.DotNet.Darc.Operations.AddBuildToChannelOperation.PromoteBuildAsync(Build build, List`1 targetChannels, IRemote remote) in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs:line 211
   at Microsoft.DotNet.Darc.Operations.AddBuildToChannelOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs:line 113
PS C:\Users\andy\Code\roslyn> darc authenticate
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Cannot start editor 'C:\Program'. Please verify that your git settings (`git config core.editor`) specify the path correctly.
System.ComponentModel.Win32Exception (2): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Darc.Helpers.UxManager.PopUp(EditorPopUp popUp) in /_/src/Microsoft.DotNet.Darc/src/Darc/Helpers/UxManager.cs:line 140
```

**Comment by jaredpar** [comment]
FYI: this is blocking source generators because our bits aren't properly included in the 3.1.3xxx builds.

**Comment by missymessa** [comment]
I'm investigating why the branch is missing this yaml file when it's clearly there in Arcade.

**Comment by agocke** [comment]
Note: we are on Arcade 3.x, and need to stay on it until .NET 5 GA

**Comment by jaredpar** [comment]
> Note: we are on Arcade 3.x, and need to stay on it until .NET 5 GA

Why do we need to be there until .NET 5 GA?

**Comment by agocke** [comment]
https://github.com/dotnet/arcade/issues/5144

**Comment by missymessa** [comment]
It appears that this file is missing from the release/3.x branch of Arcade. 

/cc @JohnTortugo, @riarenas, and @mmitche
