### ISSUE TITLE
The "Microsoft.DotNet.SignTool.SignToolTask" task failed unexpectedly. System.IO.IOException: The process cannot access the file 

### ISSUE THREAD

**Issue by safern** [dotnet/arcade#5492]
One of our builds in dotnet/runtime just hit this:

```
.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\Sign.proj(40,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Build) The "Microsoft.DotNet.SignTool.SignToolTask" task failed unexpectedly.
System.IO.IOException: The process cannot access the file 'F:\workspace\_work\1\s\artifacts\bin\Microsoft.DotNet.PlatformAbstractions\Debug\net45\Microsoft.DotNet.PlatformAbstractions.dll' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Microsoft.DotNet.SignTool.ContentUtil.IsManaged(String filePath) in /_/src/Microsoft.DotNet.SignTool/src/ContentUtil.cs:line 74
   at Microsoft.DotNet.SignTool.Configuration.GetPEInfo(String fullPath) in /_/src/Microsoft.DotNet.SignTool/src/Configuration.cs:line 382
   at Microsoft.DotNet.SignTool.Configuration.ExtractSignInfo(String fullPath, ImmutableArray`1 hash, Boolean forceRepack) in /_/src/Microsoft.DotNet.SignTool/src/Configuration.cs:line 265
   at Microsoft.DotNet.SignTool.Configuration.TrackFile(String fullPath, ImmutableArray`1 contentHash, Boolean isNested, Boolean forceRepack) in /_/src/Microsoft.DotNet.SignTool/src/Configuration.cs:line 206
   at Microsoft.DotNet.SignTool.Configuration.GenerateListOfFiles() in /_/src/Microsoft.DotNet.SignTool/src/Configuration.cs:line 170
   at Microsoft.DotNet.SignTool.SignToolTask.ExecuteImpl() in /_/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs:line 219
   at Microsoft.DotNet.SignTool.SignToolTask.Execute() in /_/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs:line 142
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

https://dev.azure.com/dnceng/public/_build/results?buildId=647310&view=logs&j=be192ad4-4e10-50a8-afff-b3b0f7c75e17

cc: @dotnet/runtime-infrastructure @chcosta

**Comment by missymessa** [comment]
Probably a dupe/same issue as #5491

**Comment by ericstj** [comment]
Interesting.  I just saw this again and it happens to be for the same filename.   

https://dev.azure.com/dnceng/public/_build/results?buildId=652259&view=logs&j=155de1d4-7273-508f-83a6-194b1aa14a21&t=7d169371-9110-5295-cca0-6d28e272e8a4&l=106

Might not be a coincidence.  FWIW @eerhardt is about to remove this assembly from the build.

**Comment by dagood** [comment]
dotnet/runtime has to sign in the middle of the build, so I wouldn't be surprised if this is a concurrency issue in the dotnet/runtime build itself. E.g. something not properly waiting for signing to complete before accessing `Microsoft.DotNet.PlatformAbstractions.dll`.

(This also makes it unlikely to be related to https://github.com/dotnet/arcade/issues/5491, if the manifest is really the cause there--there's no manifest involved here.)

**Comment by garath** [comment]
Triage: This seems resolved. If not, please reopen.
