### ISSUE TITLE
Investigate dotnet/runtime publishing error

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#5558]
Reported by @safern that dotnet/runtime build failed to publish. Here is a sample:

https://dev.azure.com/dnceng/internal/_build/results?buildId=660518&view=results

Error is:

```
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\SdkTasks\PublishArtifactsInManifest.proj(79,5): error : The response contained an invalid status code 404 Not Found
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\SdkTasks\PublishArtifactsInManifest.proj(79,5): error : 
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\SdkTasks\PublishArtifactsInManifest.proj(79,5): error : Body: {"message":"Error adding asset locations.","errors":["The asset with id '0' was not found."]}
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\SdkTasks\PublishArtifactsInManifest.proj(79,5): error :    at Microsoft.DotNet.Maestro.Client.Assets.OnBulkAddLocationsFailed(Request req, Response res)
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\SdkTasks\PublishArtifactsInManifest.proj(79,5): error :    at Microsoft.DotNet.Maestro.Client.Assets.BulkAddLocationsAsync(IImmutableList`1 body, CancellationToken cancellationToken)
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20261.9\tools\SdkTasks\PublishArtifactsInManifest.proj(79,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.PublishArtifactsInManifest.ExecuteAsync() in /_/src/M
```

This is very likely due to recent changes for bulk adding location to assets.

/cc @mmitche @ViktorHofer fyi

**Comment by JohnTortugo** [comment]
I removed the `Critical` label as this seems to be one of a kind. I'm still investigating this as a priority as it might suddenly become frequent.

**Comment by JohnTortugo** [comment]
The failing build used version 5.0.0-beta.20261.9 of the Arcade SDK & Tasks.Feed which doesn't include this important fix: https://github.com/dotnet/arcade/pull/5531 I think this issue might be related. The version currently in use by dotnet/runtime is the latest validated version of the packages, though: https://github.com/dotnet/arcade/#current-version-of-arcade-in-net-eng---latest

I'm going to ran some tests to see if we can override just the version of the tasks.feed package in dotnet/runtime (and any other repo that hits the problem), so we don't need to wait until all Arcade packages are validated.

**Comment by JohnTortugo** [comment]
The Arcade SDK with the fix has been released. Moving to tracking while I monitor whether this happens again or not.

**Comment by JohnTortugo** [comment]
Closing as no further instance of this was reported.
