### ISSUE TITLE
Arcade services local dev environment

### ISSUE THREAD

**Issue by rokonec** [dotnet/arcade#5762]
In order to develop new scenario tests for #3326, we need to be able to run scenario tests locally.

Follow https://github.com/dotnet/arcade-services/blob/master/docs/DevGuide.md to install and setup local dev environment,

**Comment by lwintjen** [comment]
I've followed the DevGuide - still trying to understand why I have this error when I build `MaestroApplication`.

The error I'm currently encountering is `AzureServiceTokenProviderCredential unable to authenticate` with the following stacktrace:

```  
 at Microsoft.DncEng.Configuration.Extensions.AzureServiceTokenProviderCredential.<GetTokenAsync>d__4.MoveNext() in C:\arcade-services\src\Microsoft.DncEng.Configuration.Extensions\ServiceConfigurationExtensions.cs:line 135
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Microsoft.DncEng.Configuration.Extensions.AzureServiceTokenProviderCredential.<>c__DisplayClass5_0.<<GetToken>b__0>d.MoveNext() in C:\arcade-services\src\Microsoft.DncEng.Configuration.Extensions\ServiceConfigurationExtensions.cs:line 141
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.DncEng.Configuration.Extensions.AzureServiceTokenProviderCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken) in C:\arcade-services\src\Microsoft.DncEng.Configuration.Extensions\ServiceConfigurationExtensions.cs:line 141
   at Azure.Identity.ChainedTokenCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
```

The error comes from `GetToken` method in `ServiceConfigurationExtension.cs` file.

**Comment by alexperovich** [comment]
If you have successfully ran this script https://github.com/dotnet/arcade-services/blob/master/src/Maestro/bootstrap.ps1 that error shouldn't happen.

**Comment by alexperovich** [comment]
And... actually you can continue from that error. The ChainedTokenCredential will catch it.

ChainedTokenCredential basically tries multiple forms of auth until one works. You can just ignore the error from that credential, the next one in the chain should work.

**Comment by lwintjen** [comment]
After some discussion with @alexperovich we managed to fix this.

To do so, I had to manually add the private key of the certificate (with  "maestrolocal" as vaultName  and "localhost" as certificateName ) to my machine store and grant read permission. 

In case you wonder how to download the private key pfx file, here's the script that I used : 
```
$cert = Get-AzKeyVaultCertificate -VaultName "maestrolocal" -Name "localhost"
$secret = Get-AzKeyVaultSecret -VaultName "maestrolocal" -Name $cert.Name

$secretByte = [Convert]::FromBase64String($secret.SecretValueText)
$x509Cert = new-object System.Security.Cryptography.X509Certificates.X509Certificate2
$x509Cert.Import($secretByte, "", "Exportable,PersistKeySet")
$type = [System.Security.Cryptography.X509Certificates.X509ContentType]::Pfx
$pfxFileByte = $x509Cert.Export($type, $password)

# Write to a file
[System.IO.File]::WriteAllBytes("KeyValt.pfx", $pfxFileByte)
```

After running this script, you'll have a `KeyValt.pfx` file, you can double click on it and install it on your machine in the personal certificate store.

When that's done, make sure you delete  `DncEngConfiguration` directory which is located in `C:\ProgramData\` and then rerun the bootstrap script `src/Maestro/bootstrap.ps1`. Once that's done, you should be able to build the solution successfully.

**Comment by lwintjen** [comment]
We updated the DevGuide in arcade-services and you probably won't need the solution explained above. You should be able to solve this by installing ngrok as explained in this [PR](https://github.com/dotnet/arcade-services/pull/1322)
