### ISSUE TITLE
Nuget errors in Runtime (Arcade version 5.0.0-beta.20367.6)

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#5813]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

This is blocking because we cannot promote Arcade unless this is fixed. 
This error is not occurring on current master runs of Runtime, which is why I think it's an issue with Arcade. 

Build link: https://dev.azure.com/dnceng/internal/_build/results?buildId=737474&view=results

```
2020-07-20T16:05:54.7002141Z      1>Project "/__w/1/s/.packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.20367.6/tools/Build.proj" (1) is building "/__w/1/s/eng/common/internal/Tools.csproj" (3) on node 1 (Restore target(s)).
2020-07-20T16:05:54.7003182Z      3>Restore:
2020-07-20T16:05:54.7003625Z          Determining projects to restore...
2020-07-20T16:05:55.5402781Z          Evaluated 1 project(s) in 929ms (1 builds, 0 failures).
2020-07-20T16:05:55.6963606Z          Restoring packages for /__w/1/s/eng/common/internal/Tools.csproj...
2020-07-20T16:05:56.2476328Z      3>/__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error : Unable to load the service index for source https://devdiv.pkgs.visualstudio.com/_packaging/dotnet-core-internal-tooling/nuget/v3/index.json. [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2478460Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2480078Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2481406Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2482660Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]() [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2484005Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResourceProvider.TryCreate(SourceRepository sourceRepository, CancellationToken token) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2485338Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2487120Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]() [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2488759Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.SourceRepositoryDependencyProvider.EnsureResource() [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2490218Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.SourceRepositoryDependencyProvider.FindLibraryCoreAsync(LibraryRange libraryRange, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2524440Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.SourceRepositoryDependencyProvider.<>c__DisplayClass19_0.<<FindLibraryAsync>b__0>d.MoveNext() [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2527806Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error : --- End of stack trace from previous location --- [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2529842Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.SourceRepositoryDependencyProvider.FindLibraryAsync(LibraryRange libraryRange, NuGetFramework targetFramework, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2531463Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.DependencyResolver.ResolverUtility.<>c__DisplayClass9_1.<<FindLibraryFromSourcesAsync>b__0>d.MoveNext() [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2532872Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error : --- End of stack trace from previous location --- [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2534229Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.DependencyResolver.ResolverUtility.FindLibraryFromSourcesAsync(LibraryRange libraryRange, IEnumerable`1 providers, Func`2 action) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2535911Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.DependencyResolver.ResolverUtility.FindLibraryByVersionAsync(LibraryRange libraryRange, NuGetFramework framework, IEnumerable`1 providers, SourceCacheContext cacheContext, ILogger logger, CancellationToken token) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2538024Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.DependencyResolver.ResolverUtility.FindPackageLibraryMatchAsync(LibraryRange libraryRange, NuGetFramework framework, IEnumerable`1 remoteProviders, IEnumerable`1 localProviders, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2540196Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.DependencyResolver.ResolverUtility.FindLibraryMatchAsync(LibraryRange libraryRange, NuGetFramework framework, String runtimeIdentifier, IEnumerable`1 remoteProviders, IEnumerable`1 localProviders, IEnumerable`1 projectProviders, IDictionary`2 lockFileLibraries, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2542886Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.DependencyResolver.ResolverUtility.FindLibraryEntryAsync(LibraryRange libraryRange, NuGetFramework framework, String runtimeIdentifier, RemoteWalkContext context, CancellationToken cancellationToken) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2547742Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.DependencyResolver.RemoteDependencyWalker.CreateGraphNode(LibraryRange libraryRange, NuGetFramework framework, String runtimeName, RuntimeGraph runtimeGraph, Func`2 predicate, GraphEdge`1 outerEdge, TransitiveCentralPackageVersions transitiveCentralPackageVersions) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2550051Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.DependencyResolver.RemoteDependencyWalker.CreateGraphNode(LibraryRange libraryRange, NuGetFramework framework, String runtimeName, RuntimeGraph runtimeGraph, Func`2 predicate, GraphEdge`1 outerEdge, TransitiveCentralPackageVersions transitiveCentralPackageVersions) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2551998Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.DependencyResolver.RemoteDependencyWalker.WalkAsync(LibraryRange library, NuGetFramework framework, String runtimeIdentifier, RuntimeGraph runtimeGraph, Boolean recursive) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2553916Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.ProjectRestoreCommand.WalkDependenciesAsync(LibraryRange projectRange, NuGetFramework framework, String runtimeIdentifier, RuntimeGraph runtimeGraph, RemoteDependencyWalker walker, RemoteWalkContext context, CancellationToken token) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2556788Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.ProjectRestoreCommand.TryRestoreAsync(LibraryRange projectRange, IEnumerable`1 frameworkRuntimePairs, NuGetv3LocalRepository userPackageFolder, IReadOnlyList`1 fallbackPackageFolders, RemoteDependencyWalker remoteWalker, RemoteWalkContext context, Boolean forceRuntimeGraphCreation, CancellationToken token, TelemetryActivity telemetryActivity) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2569279Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.RestoreCommand.ExecuteRestoreAsync(NuGetv3LocalRepository userPackageFolder, IReadOnlyList`1 fallbackPackageFolders, RemoteWalkContext context, CancellationToken token, TelemetryActivity telemetryActivity) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2572190Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.RestoreCommand.ExecuteAsync(CancellationToken token) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2573772Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2575419Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.RestoreRunner.ExecuteAndCommitAsync(RestoreSummaryRequest summaryRequest, CancellationToken token) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2576768Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2579122Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.RestoreRunner.RunAsync(IEnumerable`1 restoreRequests, RestoreArgs restoreContext, CancellationToken token) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2583895Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.RestoreRunner.RunAsync(RestoreArgs restoreContext, CancellationToken token) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2589622Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Build.Tasks.BuildTasksUtility.RestoreAsync(DependencyGraphSpec dependencyGraphSpec, Boolean interactive, Boolean recursive, Boolean noCache, Boolean ignoreFailedSources, Boolean disableParallel, Boolean force, Boolean forceEvaluate, Boolean hideWarningsAndErrors, Boolean restorePC, Boolean cleanupAssetsForUnsupportedProjects, ILogger log, CancellationToken cancellationToken) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2593685Z /__w/1/s/.dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error :    at NuGet.Build.Tasks.Console.MSBuildStaticGraphRestore.RestoreAsync(String entryProjectFilePath, IDictionary`2 globalProperties, IReadOnlyDictionary`2 options) [/__w/1/s/eng/common/internal/Tools.csproj]
2020-07-20T16:05:56.2715611Z ##[error].dotnet/sdk/5.0.100-preview.8.20362.3/NuGet.RestoreEx.targets(10,5): error : (NETCORE_ENGINEERING_TELEMETRY=Restore) Unable to load the service index for source https://devdiv.pkgs.visualstudio.com/_packaging/dotnet-core-internal-tooling/nuget/v3/index.json.
   at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
   at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResourceProvider.TryCreate(SourceRepository sourceRepository, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
   at NuGet.Commands.SourceRepositoryDependencyProvider.EnsureResource()
   at NuGet.Commands.SourceRepositoryDependencyProvider.FindLibraryCoreAsync(LibraryRange libraryRange, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
   at NuGet.Commands.SourceRepositoryDependencyProvider.<>c__DisplayClass19_0.<<FindLibraryAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at NuGet.Commands.SourceRepositoryDependencyProvider.FindLibraryAsync(LibraryRange libraryRange, NuGetFramework targetFramework, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
   at NuGet.DependencyResolver.ResolverUtility.<>c__DisplayClass9_1.<<FindLibraryFromSourcesAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at NuGet.DependencyResolver.ResolverUtility.FindLibraryFromSourcesAsync(LibraryRange libraryRange, IEnumerable`1 providers, Func`2 action)
   at NuGet.DependencyResolver.ResolverUtility.FindLibraryByVersionAsync(LibraryRange libraryRange, NuGetFramework framework, IEnumerable`1 providers, SourceCacheContext cacheContext, ILogger logger, CancellationToken token)
   at NuGet.DependencyResolver.ResolverUtility.FindPackageLibraryMatchAsync(LibraryRange libraryRange, NuGetFramework framework, IEnumerable`1 remoteProviders, IEnumerable`1 localProviders, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
   at NuGet.DependencyResolver.ResolverUtility.FindLibraryMatchAsync(LibraryRange libraryRange, NuGetFramework framework, String runtimeIdentifier, IEnumerable`1 remoteProviders, IEnumerable`1 localProviders, IEnumerable`1 projectProviders, IDictionary`2 lockFileLibraries, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken)
   at NuGet.DependencyResolver.ResolverUtility.FindLibraryEntryAsync(LibraryRange libraryRange, NuGetFramework framework, String runtimeIdentifier, RemoteWalkContext context, CancellationToken cancellationToken)
   at NuGet.DependencyResolver.RemoteDependencyWalker.CreateGraphNode(LibraryRange libraryRange, NuGetFramework framework, String runtimeName, RuntimeGraph runtimeGraph, Func`2 predicate, GraphEdge`1 outerEdge, TransitiveCentralPackageVersions transitiveCentralPackageVersions)
   at NuGet.DependencyResolver.RemoteDependencyWalker.CreateGraphNode(LibraryRange libraryRange, NuGetFramework framework, String runtimeName, RuntimeGraph runtimeGraph, Func`2 predicate, GraphEdge`1 outerEdge, TransitiveCentralPackageVersions transitiveCentralPackageVersions)
   at NuGet.DependencyResolver.RemoteDependencyWalker.WalkAsync(LibraryRange library, NuGetFramework framework, String runtimeIdentifier, RuntimeGraph runtimeGraph, Boolean recursive)
   at NuGet.Commands.ProjectRestoreCommand.WalkDependenciesAsync(LibraryRange projectRange, NuGetFramework framework, String runtimeIdentifier, RuntimeGraph runtimeGraph, RemoteDependencyWalker walker, RemoteWalkContext context, CancellationToken token)
   at NuGet.Commands.ProjectRestoreCommand.TryRestoreAsync(LibraryRange projectRange, IEnumerable`1 frameworkRuntimePairs, NuGetv3LocalRepository userPackageFolder, IReadOnlyList`1 fallbackPackageFolders, RemoteDependencyWalker remoteWalker, RemoteWalkContext context, Boolean forceRuntimeGraphCreation, CancellationToken token, TelemetryActivity telemetryActivity)
   at NuGet.Commands.RestoreCommand.ExecuteRestoreAsync(NuGetv3LocalRepository userPackageFolder, IReadOnlyList`1 fallbackPackageFolders, RemoteWalkContext context, CancellationToken token, TelemetryActivity telemetryActivity)
   at NuGet.Commands.RestoreCommand.ExecuteAsync(CancellationToken token)
   at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
   at NuGet.Commands.RestoreRunner.ExecuteAndCommitAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
   at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks)
   at NuGet.Commands.RestoreRunner.RunAsync(IEnumerable`1 restoreRequests, RestoreArgs restoreContext, CancellationToken token)
   at NuGet.Commands.RestoreRunner.RunAsync(RestoreArgs restoreContext, CancellationToken token)
   at NuGet.Build.Tasks.BuildTasksUtility.RestoreAsync(DependencyGraphSpec dependencyGraphSpec, Boolean interactive, Boolean recursive, Boolean noCache, Boolean ignoreFailedSources, Boolean disableParallel, Boolean force, Boolean forceEvaluate, Boolean hideWarningsAndErrors, Boolean restorePC, Boolean cleanupAssetsForUnsupportedProjects, ILogger log, CancellationToken cancellationToken)
   at NuGet.Build.Tasks.Console.MSBuildStaticGraphRestore.RestoreAsync(String entryProjectFilePath, IDictionary`2 globalProperties, IReadOnlyDictionary`2 options)
2020-07-20T16:05:56.2738008Z      3>Done Building Project "/__w/1/s/eng/common/internal/Tools.csproj" (Restore target(s)) -- FAILED.
2020-07-20T16:05:56.2739040Z      1>Done Building Project "/__w/1/s/.packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.20367.6/tools/Build.proj" (default targets) -- FAILED.
```

**Comment by missymessa** [comment]
This is likely an auth issue, however, I'm not seeing the same issue occur on Runtime's builds on master or the last run on a branch on Friday.

**Comment by missymessa** [comment]
List of changes in Arcade between the last promoted and this one. Nothing in here immediately stands out as the source of the issue, though: https://github.com/dotnet/arcade/compare/ff5d4b6c8dbdaeacb6e6159d3f8185118dffd915...f9a6c4e01f5f0a88c08c3d2a233a590ba9f11a48

**Comment by MattGal** [comment]
Just needs the PAT fixed, I'll keep poking at this.

**Comment by MattGal** [comment]
Nope, that's not it.  I think this is actually this line in `\eng\common\tools.ps1`

```
    $env:DOTNET_CLI_HOME=$RepoRoot
```
... testing this theory now (reverting this one line and trying a build w/ a private branch)

**Comment by MattGal** [comment]
This is a legitimate catch by arcade-validation;  this change breaks the internal build and just isn't exercised on the public CI so was missed.  We should revert the changes for https://github.com/dotnet/arcade/issues/5402 and consider attempting a fix in a different way.

**Comment by MattGal** [comment]
Rollback via https://github.com/dotnet/arcade/pull/5815
