### ISSUE TITLE
[maestro++/darc] Investigate Darc add-build-to-channel not working with v3 publishing

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5942]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

During testing of https://github.com/dotnet/arcade/pull/5896, it looks like the changes to the build promotion pipeline are not compatible with the add-build-to-channel command, causing errors:
```
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      A '400 - BadRequest' status was returned for a HTTP request. We'll set the retries amount to 0. Error details: {"$id":"1","customProperties":{"ValidationResults":[{"result":"error","message":"A value for the 'BARBuildId' parameter must be provided."}]},"innerException":null,"message":"Could not queue the build because there were validation errors or warnings.","typeName":"Microsoft.TeamFoundation.Build.WebApi.BuildRequestValidationFailedException, Microsoft.TeamFoundation.Build2.WebApi","typeKey":"BuildRequestValidationFailedException","errorCode":0,"eventId":3000}
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      There was an error executing method 'POST' against URI '_apis/build/builds/' after 0 attempts. Exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs:line 85
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Error: Failed to assign build '60016' to channel ''.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs:line 85
   at Microsoft.DotNet.DarcLib.AzureDevOpsClient.ExecuteAzureDevOpsAPIRequestAsync(HttpMethod method, String accountName, String projectName, String requestPath, ILogger logger, String body, String versionOverride, Boolean logFailure, String baseAddressSubpath, Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs:line 810
   at Microsoft.DotNet.DarcLib.AzureDevOpsClient.StartNewBuildAsync(String accountName, String projectName, Int32 azdoDefinitionId, String sourceBranch, String sourceVersion, String queueTimeVariables) in /_/src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs:line 1138
   at Microsoft.DotNet.Darc.Operations.AddBuildToChannelOperation.PromoteBuildAsync(Build build, List`1 targetChannels, IRemote remote) in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs:line 258
   at Microsoft.DotNet.Darc.Operations.AddBuildToChannelOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs:line 146
Problems using Darc to promote build 60016 to default channels. Stopping execution...
```

My suspicion is this is due to the yaml changes in the PR, which use parameters to the build pipeline instead of queue time variables.

**Comment by riarenas** [comment]
Taking a look at this while @epananth is out.

**Comment by riarenas** [comment]
Wow. It looks like since we're going to use template parameters in the v3 version of the pipeline, we'll need to use a different API to queue the build: https://docs.microsoft.com/en-US/rest/api/azure/devops/pipelines/runs/run%20pipeline?view=azure-devops-rest-6.0

Template parameters don't seem to work well with the queue build API. There are multiple feedback posts asking about this...

**Comment by riarenas** [comment]
Correction. Template parameters don't work at all with the old API. we HAVE to use the new run pipeline API.

**Comment by riarenas** [comment]
THis has been rolled out
