### ISSUE TITLE
[darc/maestro+++] Some dependency update PRs are failing to open due to 503 responses from the azdo API

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5951]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

We are seeing multiple instances throughout the day where we're unable to read a Version.Details.xml file from an AzDO repository. 

```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 503 (Service Unavailable).
at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount) in //src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs:line 85
at Microsoft.DotNet.DarcLib.AzureDevOpsClient.ExecuteAzureDevOpsAPIRequestAsync(HttpMethod method, String accountName, String projectName, String requestPath, ILogger logger, String body, String versionOverride, Boolean logFailure, String baseAddressSubpath, Int32 retryCount) in //src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs:line 819
at Microsoft.DotNet.DarcLib.AzureDevOpsClient.GetFileContentsAsync(String accountName, String projectName, String repoName, String filePath, String branchOrCommit) in //src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs:line 117
at Microsoft.DotNet.DarcLib.GitFileManager.ReadXmlFileAsync(String filePath, String repoUri, String branch) in //src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs:line 722
at Microsoft.DotNet.DarcLib.GitFileManager.ReadVersionDetailsXmlAsync(String repoUri, String branch) in //src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs:line 48
at Microsoft.DotNet.DarcLib.GitFileManager.ParseVersionDetailsXmlAsync(String repoUri, String branch, Boolean includePinned) in //src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs:line 106
at Microsoft.DotNet.DarcLib.Remote.GetDependenciesAsync(String repoUri, String branchOrCommit, String name, Boolean loadAssetLocations) in //src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs:line 1339
at Microsoft.DotNet.DarcLib.DependencyGraph.GetDependenciesAsync(IRemoteFactory remoteFactory, Boolean remote, ILogger logger, String gitExecutable, String repoUri, String commit, Boolean includeToolset, IEnumerable1 remotesMap, String reposFolder, String testPath) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyGraph.cs:line 913 at Microsoft.DotNet.DarcLib.DependencyGraph.BuildDependencyGraphImplAsync(IRemoteFactory remoteFactory, IEnumerable1 rootDependencies, String repoUri, String commit, DependencyGraphBuildOptions options, Boolean remote, ILogger logger, String reposFolder, IEnumerable1 remotesMap, String testPath) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyGraph.cs:line 526 at Microsoft.DotNet.DarcLib.DependencyGraph.BuildRemoteDependencyGraphAsync(IRemoteFactory remoteFactory, IEnumerable1 rootDependencies, String repoUri, String commit, DependencyGraphBuildOptions options, ILogger logger) in //src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyGraph.cs:line 188
at Microsoft.DotNet.DarcLib.Remote.BuildGraphAtDependencyAsync(IRemoteFactory remoteFactory, DependencyDetail rootDependency, List1 updateList, Dictionary2 nodeCache) in //src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs:line 875
at Microsoft.DotNet.DarcLib.Remote.GetRequiredLegacyCoherencyUpdatesAsync(IEnumerable1 dependencies, IRemoteFactory remoteFactory) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs:line 806 at Microsoft.DotNet.DarcLib.Remote.GetRequiredCoherencyUpdatesAsync(IEnumerable1 dependencies, IRemoteFactory remoteFactory, CoherencyMode coherencyMode) in //src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs:line 1044
at SubscriptionActorService.PullRequestActorImplementation.GetRequiredUpdates(List1 updates, IRemoteFactory remoteFactory, String targetRepository, String branch) in /_/src/Maestro/SubscriptionActorService/PullRequestActor.cs:line 1188 at SubscriptionActorService.PullRequestActorImplementation.CreatePullRequestAsync(List1 updates) in /_/src/Maestro/SubscriptionActorService/PullRequestActor.cs:line 828
at SubscriptionActorService.PullRequestActorImplementation.UpdateAssetsAsync(Guid subscriptionId, Int32 buildId, String sourceRepo, String sourceSha, List1 assets) in /_/src/Maestro/SubscriptionActorService/PullRequestActor.cs:line 669 at Microsoft.DotNet.ServiceFabric.ServiceHost.AsyncInterceptor.<>c__DisplayClass8_0.<<InterceptAsync>b__0>d.MoveNext() in /_/src/Microsoft.DotNet.ServiceFabric.ServiceHost/LoggedServiceRemoting/AsyncInterceptor.cs:line 125 --- End of stack trace from previous location where exception was thrown --- at Microsoft.DotNet.ServiceFabric.ServiceHost.Actors.ActorMethodInterceptor1.InterceptAsync[T](IInvocation invocation, Func1 call) in /_/src/Microsoft.DotNet.ServiceFabric.ServiceHost/Actors/DelegatedActor.cs:line 169 at Microsoft.ServiceFabric.Services.Remoting.Builder.MethodDispatcherBase.<>c.<ContinueWith>b__9_0(Task t) at System.Threading.Tasks.ContinuationResultTaskFromTask1.InnerInvoke()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.ServiceFabric.Actors.Runtime.ActorManager.<>c__DisplayClass57_0.b__0(Task1 t) at System.Threading.Tasks.ContinuationResultTaskFromResultTask2.InnerInvoke()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.ServiceFabric.Actors.Runtime.ActorManager.DispatchToActorConcurrencyLockHeldAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, ActorBase actor, Func3 actorFunc, String callContext, CancellationToken cancellationToken) at Microsoft.ServiceFabric.Actors.Runtime.ActorManager.DispatchToActorAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Boolean createIfRequired, Func3 actorFunc, String callContext, Boolean timerCall, CancellationToken cancellationToken)
at Microsoft.ServiceFabric.Actors.Runtime.ActorManager.DispatchToActorAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Boolean createIfRequired, Func3 actorFunc, String callContext, Boolean timerCall, CancellationToken cancellationToken) at Microsoft.ServiceFabric.Services.Remoting.Runtime.ServiceRemotingCancellationHelper.DispatchRequest[T](Int32 interfaceId, Int32 methodId, String callContext, Func2 dispatchFunc)
at Microsoft.ServiceFabric.Actors.Remoting.V2.Runtime.ActorServiceRemotingDispatcher.HandleActorMethodDispatchAsync(IActorRemotingMessageHeaders messageHeaders, IServiceRemotingRequestMessageBody msgBody)
at Microsoft.ServiceFabric.Services.Remoting.V2.FabricTransport.Runtime.FabricTransportMessageHandler.RequestResponseAsync(FabricTransportRequestContext requestContext, FabricTransportMessage fabricTransportMessage)'
```
We have this operation set at 0 retries: https://github.com/dotnet/arcade-services/blob/master/src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs#L117-L133 and it looks like it would be safe to just remove the parameter so that it uses the default 15 retries.

**Comment by riarenas** [comment]
https://github.com/dotnet/arcade-services/pull/1349

**Comment by riarenas** [comment]
We haven't seen any more of these since dotnet/arcade-services#1349 was rolled out.
