### ISSUE TITLE
Publishing should print useful errors when a channel is not available

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6378]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

When a channel is not available for publishing, v3 publishing throws a nullref:

```
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20478.3\tools\SdkTasks\PublishArtifactsInManifest.proj(99,5): error : Object reference not set to an instance of an object.
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20478.3\tools\SdkTasks\PublishArtifactsInManifest.proj(99,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.Model.TargetChannelConfig.Equals(Object other) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/model/TargetChannelConfig.cs:line 93
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20478.3\tools\SdkTasks\PublishArtifactsInManifest.proj(99,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.PublishArtifactsInManifestV3.ExecuteAsync() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs:line 95
```

Instead, it should print an error that makes it more identifiable that:
- The channel should be added to the PublishingConstants.cs collection
- If it's there, ensure that the branch of arcade that is running is updated to a version of arcade that contains the PublishingConstants.cs change.

**Comment by mmitche** [comment]
@riarenas
