### ISSUE TITLE
[darc/maestro++] darc update-dependencies fails if a repository has a .config folder, but no dotnet-tools.json

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#6391]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

To repro:

1. Add a folder named .config to a repository
1. run `darc update-dependencies --channel ".net eng - validation"`

You will see an error about a missing file:

```
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Error: Failed to update dependencies.
System.IO.FileNotFoundException: Could not find file 'C:\dev\arcade\.config\dotnet-tools.json'.
File name: 'C:\dev\arcade\.config\dotnet-tools.json'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path)
   at Microsoft.DotNet.DarcLib.LocalGitClient.GetFileContentsAsync(String relativeFilePath, String repoUri, String branch) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs:line 77
   at Microsoft.DotNet.DarcLib.GitFileManager.ReadDotNetToolsConfigJsonAsync(String repoUri, String branch) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs:line 77
   at Microsoft.DotNet.DarcLib.GitFileManager.UpdateDependencyFiles(IEnumerable`1 itemsToUpdate, String repoUri, String branch, IEnumerable`1 oldDependencies, SemanticVersion incomingDotNetSdkVersion) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs:line 204
   at Microsoft.DotNet.DarcLib.Local.UpdateDependenciesAsync(List`1 dependencies, IRemoteFactory remoteFactory) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs:line 79
   at Microsoft.DotNet.Darc.Operations.UpdateDependenciesOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateDependenciesOperation.cs:line 238
```

**Comment by riarenas** [comment]
CC @MattGal

**Comment by MattGal** [comment]
Addressed and regression coverage added via https://github.com/dotnet/arcade-services/pull/1437

**Comment by MattGal** [comment]
Rolled out yesterday.
