### ISSUE TITLE
[Darc/Maestro++] Maestro++ receiving 403 responses when accessing github APIs

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#6631]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

We've started receiving 403 responses from GitHub when trying to create dependency update PRs starting on 11/27. It's not happening for every dependency update so that makes me think this is more than just dealing with an expired secret.

[App insights query](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fmaestro-prod-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fmaestro-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAyXMMQoCUQyE4V7wDsNWaiVo5QE8gDd4mwRMscnjJYsKHn4jdsP88OVoJIH97ovV1A3yJulZ63%252B%252BnjIEJ5BbNq1zekj0qoLIlmtUYQF7IeYJNVZqWXWlguOG6%252FmCw93HrMxix%252Bmn%252BmAZmD9IXaScpaMFbb5iHduMAAAA/timespan/P7D)

Example exception:

```
Unexpected error processing action: The exception System.Net.Http.HttpRequestException was unhandled on the service and could not be serialized for transferring to the client.
Detailed Remote Exception Information: System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.DotNet.DarcLib.HttpRequestManager.ExecuteAsync(Int32 retryCount) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs:line 86
   at Microsoft.DotNet.DarcLib.GitHubClient.ExecuteRemoteGitCommandAsync(HttpMethod method, String requestUri, ILogger logger, String body, String versionOverride, Int32 retryCount, Boolean logFailure) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs:line 732
   at Microsoft.DotNet.DarcLib.GitHubClient.CreateBranchAsync(String repoUri, String newBranch, String baseBranch) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs:line 183
   at Microsoft.DotNet.DarcLib.Remote.CreateNewBranchAsync(String repoUri, String baseBranch, String newBranch) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs:line 293
   at SubscriptionActorService.PullRequestActorImplementation.CreatePullRequestAsync(List`1 updates) in /_/src/Maestro/SubscriptionActorService/PullRequestActor.cs:line 798
   at SubscriptionActorService.PullRequestActorImplementation.UpdateAssetsAsync(Guid subscriptionId, Int32 buildId, String sourceRepo, String sourceSha, List`1 assets) in /_/src/Maestro/SubscriptionActorService/PullRequestActor.cs:line 639
   at Microsoft.DotNet.ServiceFabric.ServiceHost.AsyncInterceptor.<>c__DisplayClass8_0.<<InterceptAsync>b__0>d.MoveNext() in /_/src/Microsoft.DotNet.ServiceFabric.ServiceHost/LoggedServiceRemoting/AsyncInterceptor.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.ServiceFabric.ServiceHost.Actors.ActorMethodInterceptor`1.InterceptAsync[T](IInvocation invocation, Func`1 call) in /_/src/Microsoft.DotNet.ServiceFabric.ServiceHost/Actors/DelegatedActor.cs:line 169
   at Microsoft.ServiceFabric.Services.Remoting.Builder.MethodDispatcherBase.<>c.<ContinueWith>b__9_0(Task t)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.ServiceFabric.Actors.Runtime.ActorManager.<>c__DisplayClass57_0.<ActorMethodDispatch>b__0(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.ServiceFabric.Actors.Runtime.ActorManager.DispatchToActorConcurrencyLockHeldAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, ActorBase actor, Func`3 actorFunc, String callContext, CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Actors.Runtime.ActorManager.DispatchToActorAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Boolean createIfRequired, Func`3 actorFunc, String callContext, Boolean timerCall, CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Actors.Runtime.ActorManager.DispatchToActorAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Boolean createIfRequired, Func`3 actorFunc, String callContext, Boolean timerCall, CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Services.Remoting.Runtime.ServiceRemotingCancellationHelper.DispatchRequest[T](Int32 interfaceId, Int32 methodId, String callContext, Func`2 dispatchFunc)
   at Microsoft.ServiceFabric.Actors.Remoting.V2.Runtime.ActorServiceRemotingDispatcher.HandleActorMethodDispatchAsync(IActorRemotingMessageHeaders messageHeaders, IServiceRemotingRequestMessageBody msgBody)
   at Microsoft.ServiceFabric.Services.Remoting.V2.FabricTransport.Runtime.FabricTransportMessageHandler.RequestResponseAsync(FabricTransportRequestContext requestContext, FabricTransportMessage fabricTransportMessage)
```

**Comment by riarenas** [comment]
We have stopped seeing these in the last few days. My best guess is some transient github issue. I'll reopen if it starts happening again and actually warrants some investigation.
