### ISSUE TITLE
[Darc/Maestro++] Dependency updates failing with "No dependencies named <dependency-name> found"

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#6633]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

We've started seeing many instances where dependency updates are failing to complete due to not finding certain dependencies. In at least some of the subscriptions, this succeeds eventually and creates the PR, so I don't think this is entirely an error in the dependency files expecting non-existing dependencies.

sample stack:
```
Actor's async method threw an exception. Method name: IPullRequestActor.UpdateAssetsAsync, actor type: PullRequestActor, actor ID: ea219f43-0754-4d2f-576e-08d76e1d56cb, exception: Microsoft.DotNet.DarcLib.DependencyException: No dependencies named 'System.Reflection.MetadataLoadContext' found.
   at Microsoft.DotNet.DarcLib.GitFileManager.UpdateDependencyFiles(IEnumerable`1 itemsToUpdate, String repoUri, String branch, IEnumerable`1 oldDependencies, SemanticVersion incomingDotNetSdkVersion) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs:line 235
   at Microsoft.DotNet.DarcLib.Remote.CommitUpdatesAsync(String repoUri, String branch, IRemoteFactory remoteFactory, List`1 itemsToUpdate, String message) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs:line 1101
   at SubscriptionActorService.PullRequestActorImplementation.CommitUpdatesAsync(List`1 requiredUpdates, StringBuilder description, IRemoteFactory remoteFactory, String targetRepository, String newBranchName) in /_/src/Maestro/SubscriptionActorService/PullRequestActor.cs:line 847
   at SubscriptionActorService.PullRequestActorImplementation.UpdatePullRequestAsync(InProgressPullRequest pr, List`1 updates) in /_/src/Maestro/SubscriptionActorService/PullRequestActor.cs:line 1134
   at SubscriptionActorService.PullRequestActorImplementation.UpdateAssetsAsync(Guid subscriptionId, Int32 buildId, String sourceRepo, String sourceSha, List`1 assets) in /_/src/Maestro/SubscriptionActorService/PullRequestActor.cs:line 639
   at Microsoft.DotNet.ServiceFabric.ServiceHost.AsyncInterceptor.<>c__DisplayClass8_0.<<InterceptAsync>b__0>d.MoveNext() in /_/src/Microsoft.DotNet.ServiceFabric.ServiceHost/LoggedServiceRemoting/AsyncInterceptor.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.ServiceFabric.ServiceHost.Actors.ActorMethodInterceptor`1.InterceptAsync[T](IInvocation invocation, Func`1 call) in /_/src/Microsoft.DotNet.ServiceFabric.ServiceHost/Actors/DelegatedActor.cs:line 169
   at Microsoft.ServiceFabric.Services.Remoting.Builder.MethodDispatcherBase.<>c.<ContinueWith>b__9_0(Task t)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.ServiceFabric.Actors.Runtime.ActorManager.<>c__DisplayClass57_0.<ActorMethodDispatch>b__0(Task`1 t).
```

[App insights query](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fmaestro-prod-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fmaestro-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA0WOsQoCMRBEe8F%252FWFPaXC9YCFp6yIG17G1GDNxlwyaHHvjxRkXshmFm3hRjQabl4klTDBoJD0EqVX3N%252Bw0GkkEnf%252Bl0QMsjaLUld%252BXegmyaIyMX011KQxB%252BF5s9EqJHlPmcPBcczNROphWU1dx%252Fdk2isXCoLNcq%252BV8v1Eexgvwnq%252BZh1M9UwlhZPCbiLC%252BswiMduQAAAA%253D%253D/timespan/P7D)

The attached issues have the specific instances where this has been happening, including which subscriptions it is happening to.

To find out which repositories are involved in the subscription when looking at the attached issues, you can use `darc get-subscriptions --ids <ids of the subscriptions to check>`

**Comment by riarenas** [comment]
These issues only happened one day, and haven't happened since. The builds that produced these asset versions have already been deleted so I couldn't see if there was anything suspicious or if we can chalk it out to underlying infrastructure failures that we don't know how to guard against.

I think there's nothing actionable for FR to look at right now regarding these.
