### ISSUE TITLE
Arcade official build failing during sourceIndexStage1 job

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#6833]
- [ ] This issue is blocking 

Official build is failing

- [ ] This issue is causing unreasonable pain

We're seeing failures in the arcade official pipeline when uploading to azure during the sourceIndexStage1 job.

```
Unhandled exception. System.FormatException: String '2021-01-05T19%3A06%3A06Z' was not recognized as a valid DateTime.
   at System.DateTimeParse.ParseExactMultiple(ReadOnlySpan`1 s, String[] formats, DateTimeFormatInfo dtfi, DateTimeStyles style, TimeSpan& offset)
   at System.DateTimeOffset.ParseExact(String input, String[] formats, IFormatProvider formatProvider, DateTimeStyles styles)
   at Azure.Storage.Sas.SasQueryParameters.ParseSasTime(String dateTimeString)
   at Azure.Storage.Sas.SasQueryParameters..ctor(IDictionary`2 values)
   at Azure.Storage.Sas.BlobSasQueryParameters..ctor(IDictionary`2 values)
   at Azure.Storage.Blobs.BlobUriBuilder..ctor(Uri uri)
   at Azure.Storage.Blobs.BlobContainerClient.GetBlobClient(String blobName)
   at UploadIndexStage1.Program.Main(String[] args) in D:\dotnet\source-indexer\src\UploadIndexStage1\Program.cs:line 59
   at UploadIndexStage1.Program.<Main>(String[] args)

```

**Comment by riarenas** [comment]
@alexperovich something wonky with this new job

**Comment by riarenas** [comment]
It looks like this fixed itself with no changes to arcade. This isn't blocking official builds anymore, but since it happened without code changes, and went away without code changes, we should still try and understand what causes the creation of the invalid datetime strings.

**Comment by alexperovich** [comment]
This was caused by bad escaping from Azure Pipelines. The build has an azure storage sas token as a secret variable, and it was escaped incorrectly.
