### ISSUE TITLE
Onboard MS Build to V3

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#6846]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

In asset manifest , the azureDevOpsUrl is a github url. This fails in Publish Build Asset with the error 
```
MSBuild.dll /nologo -maxcpucount /m -verbosity:m /v:minimal /v:minimal /bl:D:\a\1\s\artifacts\log\Debug\PublishBuildAssets.binlog /clp:Summary /logger:D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20621.10\tools\netcoreapp2.1\Microsoft.DotNet.Arcade.Sdk.dll /nr:False /p:ContinuousIntegrationBuild=True /p:TreatWarningsAsErrors=true /p:Configuration=Debug /p:RepoRoot=D:\a\1\s /p:BaseIntermediateOutputPath=D:\a\1\s\artifacts\toolset\PublishBuildAssets\ /p:ManifestsPath=D:\a\1\a/Download/AssetManifests /p:BuildAssetRegistryToken=*** /p:MaestroApiEndpoint=https://maestro-prod.westus2.cloudapp.azure.com /p:PublishUsingPipelines=true /p:Configuration=Debug /p:OfficialBuildId=20210122.10 /t:Execute /warnaserror D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20621.10\tools\SdkTasks\PublishBuildAssets.proj
  Starting build metadata push to the Build Asset Registry...
  Getting a collection of dependencies from 'eng/Version.Details.xml' in repo 'D:\a\1\s\'...
  Reading 'eng/Version.Details.xml' in repo 'D:\a\1\s\' and branch ''...
  Reading 'eng/Version.Details.xml' from repo 'D:\a\1\s\' and branch '' succeeded!
  Asset 'Microsoft.DotNet.Arcade.Sdk@5.0.0-beta.20621.10' not found in BAR, most likely this is an external dependency, ignoring...
  Calculated Dependencies:
      74834, IsProduct: False
      71622, IsProduct: False
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20621.10\tools\SdkTasks\PublishBuildAssets.proj(43,5): error : ArgumentException: Repository URI should be in the form https://dev.azure.com/:account/:project/_git/:repo or https://:account.visualstudio.com/:project/_git/:repo
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20621.10\tools\SdkTasks\PublishBuildAssets.proj(43,5): error :    at Microsoft.DotNet.DarcLib.AzureDevOpsClient.ParseRepoUri(String repoUri) in /_/src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs:line 939
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20621.10\tools\SdkTasks\PublishBuildAssets.proj(43,5): error :    at Microsoft.DotNet.Maestro.Tasks.PushMetadataToBuildAssetRegistry.GetManifestAsAsset(IImmutableList`1 assets, String location, String manifestFileName) in /_/src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs:line 616
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20621.10\tools\SdkTasks\PublishBuildAssets.proj(43,5): error :    at Microsoft.DotNet.Maestro.Tasks.PushMetadataToBuildAssetRegistry.PushMetadataAsync(CancellationToken cancellationToken) in /_/src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs:line 122
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20621.10\tools\SdkTasks\PublishBuildAssets.proj(43,5): error : 
##[error].packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20621.10\tools\SdkTasks\PublishBuildAssets.proj(43,5): error : (NETCORE_ENGINEERING_TELEMETRY=Publish) ArgumentException: Repository URI should be in the form https://dev.azure.com/:account/:project/_git/:repo or https://:account.visualstudio.com/:project/_git/:repo
   at Microsoft.DotNet.DarcLib.AzureDevOpsClient.ParseRepoUri(String repoUri) in /_/src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs:line 939
   at Microsoft.DotNet.Maestro.Tasks.PushMetadataToBuildAssetRegistry.GetManifestAsAsset(IImmutableList`1 assets, String location, String manifestFileName) in /_/src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs:line 616
   at Microsoft.DotNet.Maestro.Tasks.PushMetadataToBuildAssetRegistry.PushMetadataAsync(CancellationToken cancellationToken) in /_/src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs:line 122


```

So we should make sure that asset manifest and other place should work for both Azure and Github Urls. 

Cc: @mmitche

**Comment by epananth** [comment]
MSbuild started building with azdo build and this is no longer a problem and Msbuild is onboarded to V3. So closing this one
