### ISSUE TITLE
Channel is not configured in PublishingConstants

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#7010]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

When Channel is not configured in PublishingConstants it should be handled better. Probably add more details on the error and think of way to know this before publishing. 
(https://github.com/dotnet/arcade/pull/6999#pullrequestreview-596691622)

```
Defaulting to category 'OTHER' for asset assets/manifests/dotnet-windowsdesktop/6.0.0-preview.2.21122.6/MergedManifest.xml
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21117.1\tools\SdkTasks\PublishArtifactsInManifest.proj(105,5): error : Value cannot be null. (Parameter 'first')
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21117.1\tools\SdkTasks\PublishArtifactsInManifest.proj(105,5): error :    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21117.1\tools\SdkTasks\PublishArtifactsInManifest.proj(105,5): error :    at System.Linq.Enumerable.SequenceEqual[TSource](IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21117.1\tools\SdkTasks\PublishArtifactsInManifest.proj(105,5): error :    at System.Linq.Enumerable.SequenceEqual[TSource](IEnumerable`1 first, IEnumerable`1 second)
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21117.1\tools\SdkTasks\PublishArtifactsInManifest.proj(105,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.Model.TargetChannelConfig.Equals(Object other) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/model/TargetChannelConfig.cs:line 113
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21117.1\tools\SdkTasks\PublishArtifactsInManifest.proj(105,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.PublishArtifactsInManifestV3.ExecuteAsync() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifestV3.cs:line 122
##[error].packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21117.1\tools\SdkTasks\PublishArtifactsInManifest.proj(105,5): error : (NETCORE_ENGINEERING_TELEMETRY=Publish) Value cannot be null. (Parameter 'first')

**Comment by riarenas** [comment]
Is this different from https://github.com/dotnet/arcade/issues/6998?

**Comment by epananth** [comment]
reusing the other issue, and closing this one. Thanks @riarenas
