### ISSUE TITLE
Symreader failing with duplicate FileSignInfos

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7064]
- [x] This issue is blocking symreader official builds
- [ ] This issue is causing unreasonable pain

https://dev.azure.com/dnceng/internal/_build/results?buildId=1026735&view=artifacts&pathAsName=false&type=publishedArtifacts

```
D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21105.12\tools\Publish.proj(151,5): The following files have conflicting FileSignInfo entries: Microsoft.DiaSymReader.dll
   at Microsoft.DotNet.VersionTools.BuildManifest.Model.SigningInformationParsingExtensions.ThrowIfInvalidFileSignInfo(IEnumerable`1 fileSignInfo) in /_/src/Microsoft.DotNet.VersionTools/lib/src/BuildManifest/Model/SigningInformationParsingExtensions.cs:line 116
   at Microsoft.DotNet.VersionTools.BuildManifest.Model.SigningInformationModel.ToXml() in /_/src/Microsoft.DotNet.VersionTools/lib/src/BuildManifest/Model/SigningInformationModel.cs:line 35
   at Microsoft.DotNet.VersionTools.BuildManifest.Model.BuildModel.ToXml() in /_/src/Microsoft.DotNet.VersionTools/lib/src/BuildManifest/Model/BuildModel.cs:line 28
   at Microsoft.DotNet.Build.Tasks.Feed.BuildModelFactory.CreateBuildManifest(IEnumerable`1 blobArtifacts, IEnumerable`1 packageArtifacts, String assetManifestPath, String manifestRepoName, String manifestBuildId, String manifestBranch, String manifestCommit, String[] manifestBuildData, Boolean isStableBuild, PublishingInfraVersion publishingVersion, Boolean isReleaseOnlyPackageVersion, SigningInformationModel signingInformationModel) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/BuildModelFactory.cs:line 118
   at Microsoft.DotNet.Build.Tasks.Feed.PushToAzureDevOpsArtifacts.ExecuteTask(IFileSystem fileSystem, ISigningInformationModelFactory signingInformationModelFactory, IBlobArtifactModelFactory blobArtifactModelFactory, IPackageArtifactModelFactory packageArtifactModelFactory, IBuildModelFactory buildModelFactory) [D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21105.12\tools\Publish.proj]
```

This appears to be a bug, as the file sign info in the repo seems valid: https://github.com/dotnet/symreader/blob/master/eng/Signing.props#L4-L5

There is also a test for this case already in arcade: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.VersionTools/tests/BuildManifest/ManifestModelTests.cs#L140

So, this is a bit of a mystery at the moment.

**Comment by mmitche** [comment]
@missymessa

**Comment by missymessa** [comment]
Fix is merged into Arcade main now. Moving to validate to follow up that it fixes the issue in Symreader.

**Comment by missymessa** [comment]
@tmat and @MichaelSimons, a version of Arcade was promoted yesterday (so should've flowed this morning) that contained a fix for this issue.

**Comment by missymessa** [comment]
Following the breadcrumbs of links, it looks like the Symreader repo needed some changes to accept the latest Arcade. Keeping this in Validate until they are able to get the fix merged.

**Comment by missymessa** [comment]
Huzzah! Symreader builds are working again!!
