### ISSUE TITLE
AddBuildToChannel not handling builds that are already on a channel correctly

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#7084]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

When we call AddBuildToChannel, if a build is already on a channel, we are supposed to return successfully. Today, the code looks like this

```
            Build build = await _context.Builds.FindAsync(buildId);
            if (build == null)
            {
                return NotFound(new ApiError($"The build with id '{buildId}' was not found."));
            }

            // If build is already in channel, nothing to do
            if (build.BuildChannels != null &&
                build.BuildChannels.Any(existingBuildChannels => existingBuildChannels.ChannelId == channelId))
            {
                return StatusCode((int)HttpStatusCode.Created);
            }
```

However, build.BuildChannels is always null, because we don't include BuildChannels when getting the build that should exist. We need to add `.Include(b => b.BuildChannels)` to the build query.

**Comment by missymessa** [comment]
@adiaaida what would be the best way to test/validate this fix?

**Comment by adiaaida** [comment]
Best guess: add a build to a channel, then try to add that build again. I don't know what the state of testing is in arcade-services anymore, but I could see it as an additional scenario test for darc, depending on how darc deals with that, or if we have any other way to test the swagger code. Today, when we run it out of arcade, we get the following error:

```
       D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21125.5\tools\SdkTasks\PublishArtifactsInManifest.proj(106,5): error : Body: {"message":"Build 80564 is already in channel 1752","errors":null}
       D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21125.5\tools\SdkTasks\PublishArtifactsInManifest.proj(106,5): error :    at Microsoft.DotNet.Maestro.Client.Channels.<OnAddBuildToChannelFailed>d__22.MoveNext()
       D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21125.5\tools\SdkTasks\PublishArtifactsInManifest.proj(106,5): error : --- End of stack trace from previous location where exception was thrown ---
       D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21125.5\tools\SdkTasks\PublishArtifactsInManifest.proj(106,5): error :    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21125.5\tools\SdkTasks\PublishArtifactsInManifest.proj(106,5): error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21125.5\tools\SdkTasks\PublishArtifactsInManifest.proj(106,5): error :    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
       D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21125.5\tools\SdkTasks\PublishArtifactsInManifest.proj(106,5): error :    at Microsoft.DotNet.Maestro.Client.Channels.<AddBuildToChannelAsync>d__21.MoveNext()
       D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21125.5\tools\SdkTasks\PublishArtifactsInManifest.proj(106,5): error : --- End of stack trace from previous location where exception was thrown ---
       D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21125.5\tools\SdkTasks\PublishArtifactsInManifest.proj(106,5): error :    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21125.5\tools\SdkTasks\PublishArtifactsInManifest.proj(106,5): error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21125.5\tools\SdkTasks\PublishArtifactsInManifest.proj(106,5): error :    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
       D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21125.5\tools\SdkTasks\PublishArtifactsInManifest.proj(106,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.PublishArtifactsInManifest.<ExecuteAsync>d__156.MoveNext() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifest.cs:line 259
```

Per @mmitche that should not be a failure scenario.

@riarenas What's the best way to test this sort of functionality.

**Comment by riarenas** [comment]
I don't think we have unit testing in place for individual darc commands yet, but this seems like a great candidate for that? I think it'd be overkill to make it part of the scenario tests when it's just verifying that one command doesn't throw.

**Comment by premun** [comment]
There are actually unit tests for the controller, however the local SQL server doesn't throw. I opened a PR but I will do additional validation tomorrow to make sure I actually fixed the bug (debugging of the code shows the correct code path).

**Comment by ilyas1974** [comment]
@premun, is there anything left to do on this issue?
