### ISSUE TITLE
Fix logger in signing extensions

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#7191]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

The file logger in Signing.Extensions has started causing problems. The latest thing is the following error:

```
2021-04-05T20:29:13.2417222Z fail: Microsoft.DotNet.Signing.Extensions.Program[0]
2021-04-05T20:29:13.2417630Z       Unhandled exception while running IOperation
2021-04-05T20:29:13.2811552Z Unhandled exception. System.AggregateException: An error occurred while writing to logger(s). (Arithmetic operation resulted in an overflow.)
2021-04-05T20:29:13.2812316Z  ---> System.OverflowException: Arithmetic operation resulted in an overflow.
2021-04-05T20:29:13.2812735Z    at System.IO.StreamWriter.WriteLine(String value)
2021-04-05T20:29:13.2813497Z    at Microsoft.DotNet.Signing.Extensions.FileLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in C:\A\1\2\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\FileLogger.cs:line 77
2021-04-05T20:29:13.2814475Z    at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
2021-04-05T20:29:13.2815269Z    --- End of inner exception stack trace ---
2021-04-05T20:29:13.2815669Z    at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
2021-04-05T20:29:13.2816232Z    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
2021-04-05T20:29:13.2816955Z    at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
2021-04-05T20:29:13.2817662Z    at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, String message, Object[] args)
2021-04-05T20:29:13.2818257Z    at Microsoft.Extensions.Logging.LoggerExtensions.LogError(ILogger logger, String message, Object[] args)
2021-04-05T20:29:13.2819034Z    at Microsoft.DotNet.Signing.Extensions.Program.RunOperation(CommandLineOptions options, IServiceProvider serviceProvider) in C:\A\1\2\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\Program.cs:line 77
2021-04-05T20:29:13.2820030Z    at Microsoft.DotNet.Signing.Extensions.Program.<>c__DisplayClass1_0.<Main>b__3(CommandLineOptions options) in C:\A\1\2\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\Program.cs:line 56
2021-04-05T20:29:13.2820873Z    at CommandLine.ParserResultExtensions.MapResult[T1,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 notParsedFunc)
2021-04-05T20:29:13.2821585Z    at Microsoft.DotNet.Signing.Extensions.Program.Main(String[] args) in C:\A\1\2\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\Program.cs:line 56
```

We need to either fix it, or remove it.

**Comment by ChadNedzlek** [comment]
This is almost certainly a threading exception.  StreamWriter is not thread safe, and there are no locks in the "Write" method.  So whenever any "async" is involved, we end up with concurrent "Write" calls trampling over each other.

**Comment by adiaaida** [comment]
We have not seen this in a while, so I am going to close this issue. If it comes back, we can reopen.
