### ISSUE TITLE
'End of Central Directory record could not be found' when publishing signed assets in staging

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7281]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

https://dev.azure.com/dnceng/internal/_build/results?buildId=1101138&view=logs&j=6251cfc2-1337-592a-b343-36d32dda23e2&t=a41149ab-39bb-5c8b-b728-382152403798

```
1>D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21160.1\tools\SdkTasks\PublishSignedAssets.proj(52,5): error : End of Central Directory record could not be found.
D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21160.1\tools\SdkTasks\PublishSignedAssets.proj(52,5): error :    at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21160.1\tools\SdkTasks\PublishSignedAssets.proj(52,5): error :    at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21160.1\tools\SdkTasks\PublishSignedAssets.proj(52,5): error :    at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21160.1\tools\SdkTasks\PublishSignedAssets.proj(52,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.src.PublishSignedAssets.<>c.<PushPackagesToFeed>b__22_0(String packagePath) in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishSignedAssets.cs:line 81
D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21160.1\tools\SdkTasks\PublishSignedAssets.proj(52,5): error :    at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21160.1\tools\SdkTasks\PublishSignedAssets.proj(52,5): error :    at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21160.1\tools\SdkTasks\PublishSignedAssets.proj(52,5): error :    at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21160.1\tools\SdkTasks\PublishSignedAssets.proj(52,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.src.PublishSignedAssets.<PushPackagesToFeed>d__22.MoveNext() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishSignedAssets.cs:line 76
D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21160.1\tools\SdkTasks\PublishSignedAssets.proj(52,5): error : --- End of stack trace from previous location where exception was thrown ---
D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21160.1\tools\SdkTasks\PublishSignedAssets.proj(52,5): error :    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21160.1\tools\SdkTasks\PublishSignedAssets.proj(52,5): error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
D:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21160.1\tools\SdkTasks\PublishSignedAssets.proj(52,5): error :    at Microsoft.DotNet.Build.Tasks.Feed.src.PublishSignedAssets.<ExecuteAsync>d__21.MoveNext() in /_/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishSignedAssets.cs:line 58

```

```
```

**Comment by mmitche** [comment]
```
                    using (BinaryReader reader = new BinaryReader(File.Open(packagePath, FileMode.Open)))
                    {
                        PackageArchiveReader packageReader = new PackageArchiveReader(reader.BaseStream);
                        return packageReader.NuspecReader.GetIdentity();
                    }
```

That would be this code. So my hunch is either that the file is corrupted (didn't download properly), or it's trying to load a file which is not a package. Either way, additional logging would help.

**Comment by adiaaida** [comment]
I've noticed this before, but, as far as I remember, only with 6.0 post-build signed packages. I'm wondering if we put them back together incorrectly?

**Comment by adiaaida** [comment]
Looks like this was fixed with the change to what artifacts were downloaded. Closing.
