### ISSUE TITLE
SignToolTask crashes if ItemsToSign is empty

### ISSUE THREAD

**Issue by weshaggard** [dotnet/arcade#759]
If ItemsToSign contains no items the SignToolTask crashes with the following exception. 
```
C:\Users\wesh\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.18456.6\tools\Sign.proj(61,5): error MSB4018: The "Microsoft.DotNet.SignTool.SignToolTask" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.SignTool.SignToolTask.GetEnclosingDirectoryOfItemsToSign() in /_/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs:line 140
   at Microsoft.DotNet.SignTool.SignToolTask.ExecuteImpl() in /_/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs:line 97
   at Microsoft.DotNet.SignTool.SignToolTask.Execute() in /_/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs:line 85
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\Users\wesh\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.18456.6\tools\Sign.proj]
```

While we might want to fail if there isn't anything to sign we shouldn't crash. We need to handle when result is null on line https://github.com/dotnet/arcade/blob/7d8c2ec211f3067177d128889d5b6b65236ed040/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs#L140.

**Comment by jcagme** [comment]
FYI @JohnTortugo
