### ISSUE TITLE
Intermittent failures in IO tests

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade#76]
On my local machine, I intermittently am hitting test failures when running the Microsoft.DotNet.Build.Tasks.IO tests.

```
xUnit.net Console Runner (64-bit .NET Core 4.6.26020.03)
  Discovering: Microsoft.DotNet.Build.Tasks.IO.Tests
  Discovered:  Microsoft.DotNet.Build.Tasks.IO.Tests
  Starting:    Microsoft.DotNet.Build.Tasks.IO.Tests
    Microsoft.DotNet.Build.Tasks.IO.Tests.ZipArchiveTest.CreatesZipFromDirectory(includeBaseDirectory: False) [FAIL]
      System.IO.IOException : The directory is not empty
      Stack Trace:
           at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
           at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
           at System.IO.Directory.Delete(String path, Boolean recursive)
        /_/test/Microsoft.DotNet.Build.Tasks.IO.Tests/ZipArchiveTest.cs(277,0): at Microsoft.DotNet.Build.Tasks.IO.Tests.ZipArchiveTest.Dispose()
        C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs(76,0): at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
  Finished:    Microsoft.DotNet.Build.Tasks.IO.Tests
=== TEST EXECUTION SUMMARY ===
   Microsoft.DotNet.Build.Tasks.IO.Tests  Total: 31, Errors: 0, Failed: 1, Skipped: 0, Time: 2.307s
=== COMMAND LINE ===
"E:\gh\chcosta\arcade\.dotnet\dotnet.exe" exec --depsfile "E:\gh\chcosta\arcade\artifacts\Debug\bin\Microsoft.DotNet.Build.Tasks.IO.Tests\netcoreapp2.0\Microsoft.DotNet.Build.Tasks.IO.Tests.deps.json" --runtimeconfig "E:\gh\chcosta\arcade\artifacts\Debug\bin\Microsoft.DotNet.Build.Tasks.IO.Tests\netcoreapp2.0\Microsoft.DotNet.Build.Tasks.IO.Tests.runtimeconfig.json" "C:\Users\chcosta\.nuget\packages\xunit.runner.console/2.3.1/tools/netcoreapp1.0/xunit.console.dll" "E:\gh\chcosta\arcade\artifacts\Debug\bin\Microsoft.DotNet.Build.Tasks.IO.Tests\netcoreapp2.0\Microsoft.DotNet.Build.Tasks.IO.Tests.dll" -noautoreporters -xml "E:\gh\chcosta\arcade\artifacts\Debug\TestResults\Microsoft.DotNet.Build.Tasks.IO.Tests_netcoreapp2.0_x64.xml"
```

**Comment by natemcmaster** [comment]
As far as I can tell, something is holding the file handle open for a few hundred milliseconds after I would expected it to be released. The hold is very short-lived so I can't figure out what it is -- ZipArchive, FileStream, antivirus, something else. Adding a retry loop around Directory.Delete with a little bit of waiting in between each call works.  See #98

**Comment by natemcmaster** [comment]
Funny, i hit the IOException consistently on Windows 10. I haven't seen it in windows 2012R2. I'm still not sure what is holding the file handle, but if anyone wants to investigate more, just run the tests in a loop.
