### ISSUE TITLE
Signtool telemetry fails for Linux files in release pipeline 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#7621]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Signtool telemetry errors after signing linux files in release pipeline. 

This is the error 

```

D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018: The "Microsoft.DotNet.SignTool.SignToolTask" task failed unexpectedly.
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018: System.TypeInitializationException: The type initializer for 'Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.CoreEventSource' threw an exception.
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:  ---> System.NullReferenceException: Object reference not set to an instance of an object.
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at System.Diagnostics.Tracing.CounterGroup.OnEventSourceCommand(Object sender, EventCommandEventArgs e)
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at System.Diagnostics.Tracing.EventSource.add_EventCommandExecuted(EventHandler`1 value)
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at System.Diagnostics.Tracing.CounterGroup.RegisterCommandCallback()
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at System.Diagnostics.Tracing.CounterGroup..ctor(EventSource eventSource)
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at System.Diagnostics.Tracing.CounterGroup.GetCounterGroup(EventSource eventSource)
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at System.Diagnostics.Tracing.DiagnosticCounter.Publish()
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at System.Diagnostics.Tracing.EventCounter..ctor(String name, EventSource eventSource)
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.CoreEventSource..ctor()
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.CoreEventSource..cctor()
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    --- End of inner exception stack trace ---
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.CoreEventSource.get_IsVerboseEnabled()
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at Microsoft.ApplicationInsights.Channel.InMemoryChannel.Send(ITelemetry item)
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at Microsoft.ApplicationInsights.Extensibility.Implementation.TransmissionProcessor.Process(ITelemetry item)
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Process(ITelemetry item)
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at Microsoft.ApplicationInsights.Extensibility.TelemetrySink.Process(ITelemetry item)
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at Microsoft.ApplicationInsights.Shared.Extensibility.Implementation.PassThroughProcessor.Process(ITelemetry item)
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChain.Process(ITelemetry item)
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at Microsoft.ApplicationInsights.TelemetryClient.Track(ITelemetry telemetry)
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at Microsoft.ApplicationInsights.TelemetryClient.TrackEvent(EventTelemetry telemetry)
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at Microsoft.ApplicationInsights.TelemetryClient.TrackEvent(String eventName, IDictionary`2 properties, IDictionary`2 metrics)
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at Microsoft.DotNet.SignTool.Telemetry.SendEvents() in /_/src/Microsoft.DotNet.SignTool/src/Telemetry.cs:line 40
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at Microsoft.DotNet.SignTool.SignToolTask.ExecuteImpl() in /_/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs:line 266
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at Microsoft.DotNet.SignTool.SignToolTask.Execute() in /_/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs:line 154
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
D:\workspace\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.Signing.Extensions\SignLinuxPackages.proj(37,9): error MSB4018: --- End of stack trace from previous location ---
```

this is sample build -> https://dev.azure.com/dnceng/internal/_build/results?buildId=1227813&view=logs&j=d7f318d2-3658-5f56-29df-16b211ec56a6&t=7851342b-b7f6-561e-0dbe-e63708dfa83e

Versions : 

SignToolVersion : 6.0.0-beta.21357.3
FeedsTaskVersion : 6.0.0-beta.21357.3

cc: @adiaaida @jonfortescue @markwilkie @chcosta

**Comment by riarenas** [comment]
This looks like a potential error in how the job is configured as part of the release pipeline. Is this just tracking ongoing work or does it really need triage and an RCA?

**Comment by chcosta** [comment]
Is this the issue we already discussed or is this a different issue?if it's the same issue, you should probably include some of the info discovered during previous investigations. Thank you!

**Comment by epananth** [comment]
I could not find what was causing this error, the same versions for signToolTask works for other files signing in release pipeline. 

I did a bunch of test around this. I put signing of linux in the same stage as signing of other files 

For example : this is where we sign all the non-linux files 

https://dev.azure.com/dnceng/internal/_build/results?buildId=1233701&view=logs&j=9ff0e0af-24e7-5b0f-fa76-5e12fc9920ef&t=04e39753-8cfe-5fb5-2824-43b4c4b51e3b

So I did a test of signing linux files in the same stage : 

https://dev.azure.com/dnceng/internal/_build/results?buildId=1235314&view=logs&j=9ff0e0af-24e7-5b0f-fa76-5e12fc9920ef&t=3ed1665c-0c8c-543f-7aab-c2b9cc91064a

It failed at the exact same spot as before( mentioned in the description). I am not sure but there is some thing that the signtooltask that it does not like when we sign linux files. 

So I added a temporary fix by adding a flag in signtool to turn telemetry off https://github.com/dotnet/arcade/pull/7623. 

But this problem still persists.

**Comment by riarenas** [comment]
I think this issue should be dealt with by the work that is trying to adapt signtool for new usage. So if this is happening as part of the release epic, it should go into the current release epic that is doing that work. 

I'm also still unsure on why this has the RCA requested label.

**Comment by epananth** [comment]
So for now I am disabling telemetry in linux files to continue with my epic, but we need to understand why this is happening only linux files. So I added RCA tag to this. But I am not sure where this issue should go.

**Comment by riarenas** [comment]
Does the same error happen when the tool runs as part of the old linux signing pipeline?

**Comment by epananth** [comment]
No it does not error in old signing pipeline. 

Old linux signing uses old versions of signtool 

SignToolVersion : 1.0.0-beta.18576.5
FeedTaskVersion : 2.2.0-beta.19280.3

I don't think these even captured telemetry at any point

**Comment by adiaaida** [comment]
The old linux signing pipeline used an extremely old version of sign tool.

Epsi has spent quite a bit of time trying to figure out why this isn't working properly, and we don't have signing experience. *Something* is going wrong, but we don't know what it is. @markwilkie asked her to open an RCA issue for someone to figure out what's going on here (ie, what is different between what the linux stuff is doing vs outside of the linux stuff). In the meantime, she is doing the work around for the telemetry stuff.

**Comment by adiaaida** [comment]
For the record, this isn't actually a problem with signing itself, but the telemetry stuff after signing. There's probably something we are missing, but we can't see what it is.

**Comment by riarenas** [comment]
I think the issue itself is an RCA then. The RCA label makes it so that once this issue is closed it will create another issue asking what happened. I don't think this is what we want in this case, and this issue instead is trying to understand what's going on.

**Comment by adiaaida** [comment]
Yes, that's correct.

**Comment by riarenas** [comment]
For triage, I still think this should be handled by the epic that is trying to adapt the tool to their new scenario, as there aren't any plans for ongoing work on the signtool. 

Alternatively, if the workaround is something we can ship with, it can go into the [signtool is complete epic](https://github.com/dotnet/arcade/issues/1270) to be dealt with when it's funded.

**Comment by adiaaida** [comment]
This appears to be the same issue: https://github.com/microsoft/ApplicationInsights-dotnet/issues/2058

**Comment by chcosta** [comment]
Agreed. I mentioned that in previous discussions, and also that it's unclear when / if it will be fixed.  The quirk being that the appinsights issue is specifically related to core, but sign tool runs on framework.  Here was my comment around that...

> [6/30/2021 1:32 PM] Christopher Costa
I think you're hitting a bug in appinsights.  TypeInitializationException thrown for trimmed applications (worked in beta2 and prior) · Issue #2058 · microsoft/ApplicationInsights-dotnet (github.com) or something similar
TypeInitializationException thrown for trimmed applications (worked in beta2 and prior) · Issue #2058 · microsoft/ApplicationInsights-dotnet
List of NuGet packages and version that you are using: Primary: Microsoft.ApplicationInsights 2.15.0-beta3 or 2.15.0 Secondary: Microsoft.ApplicationInsights.WorkerService 2.15.0-beta3 or 2.15.0 (o...

> [6/30/2021 1:33 PM] Christopher Costa
i'm not certain if it's the exact same bug, you might need to file a new issue

I mention that if only to say that the important thing is the last thing I wrote.  We should make sure we're communicating with the app insights team about this and at least relaying our scenario (framework).  It would be disappointing if they decided to finally fix this but only for core and we remain broken even longer than necessary.  They might also say "no, that's something else".  Which is a fine response.

**Comment by epananth** [comment]
Yes I followed up and created an issue in application insights -https://github.com/microsoft/ApplicationInsights-dotnet/issues/2323 no response yet.

**Comment by markwilkie** [comment]
Moving to signtool is complete
