### ISSUE TITLE
DarcCoherencyException is not serializable, breaks logging for non-coherent dependency update

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#7639]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

As automatedly reported by https://github.com/dotnet/core-eng/issues/13727, we need to make Microsoft.DotNet.DarcLib.DarcCoherencyException  de-serializeable (Writing a simple ctor overload should solve this).

Users have the mitigation step (after education) of just running `darc update-dependencies` locally and seeing the exceptions get printed, but it should be straightforward to fix this, which should result in fewer FR issues.

```
Unexpected error processing action: Failed to deserialize and get remote exception System.Runtime.Serialization.SerializationException: The constructor to deserialize an object of type Microsoft.DotNet.DarcLib.DarcCoherencyException was not found.
---> System.Runtime.Serialization.SerializationException: The constructor to deserialize an object of type Microsoft.DotNet.DarcLib.DarcCoherencyException was not found.
at System.Runtime.Serialization.ObjectManager.GetDeserializationConstructor[Type t]
at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject[Object obj, SerializationInfo info, StreamingContext context]
--- End of inner exception stack trace ---
at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject[Object obj, SerializationInfo info, StreamingContext context]
at System.Runtime.Serialization.ObjectManager.FixupSpecialObject[ObjectHolder holder]
at System.Runtime.Serialization.ObjectManager.DoFixups[]
at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize[BinaryParser serParser, Boolean fCheck]
at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize[Stream serializationStream, Boolean check]
at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize[Stream serializationStream]
at Microsoft.ServiceFabric.Services.Remoting.V2.RemoteException.TryDeserializeException[Stream data, Exception& result]')
Subscription id : '1e4fa27f-25cc-4275-f3f1-08d8e97c775d'
Error Message : 'Unexpected error processing action: Failed to deserialize and get remote exception System.Runtime.Serialization.SerializationException: The constructor to deserialize an object of type 'Microsoft.DotNet.DarcLib.DarcCoherencyException' was not found.
---> System.Runtime.Serialization.SerializationException: The constructor to deserialize an object of type 'Microsoft.DotNet.DarcLib.DarcCoherencyException' was not found.
at System.Runtime.Serialization.ObjectManager.GetDeserializationConstructor(Type t)
at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
--- End of inner exception stack trace ---
at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
at System.Runtime.Serialization.ObjectManager.DoFixups()
at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
at Microsoft.ServiceFabric.Services.Remoting.V2.RemoteException.TryDeserializeException(Stream data, Exception& result)'
Method : 'UpdateAsync'
Action : 'Updating subscription for build 97721'
```

**Comment by riarenas** [comment]
Since this ends up hiding actual failures, I think this should be done as part of FR.

**Comment by riarenas** [comment]
No more input, putting it in FR for now. FYI @ilyas1974

**Comment by MattGal** [comment]
@ilyas1974 I'm back on FR next week and am pretty sure this is super easy, I'll take it then

**Comment by MattGal** [comment]
I believe this is rolled out, closing
