### ISSUE TITLE
Darc clone fails on App Insights

### ISSUE THREAD

**Issue by crummel** [dotnet/arcade#7698]
Recently tried to upgrade source-build's version of Darc from 1.1.0-beta.19568.2 to 1.1.0-beta.21378.3 and I'm getting this issue:
```
  dbug: Microsoft.DotNet.Darc.Operations.Operation[0]
        Starting master copy for https://github.com/Microsoft/ApplicationInsights-dotnet in /home/chris/sb2/artifacts/src/ApplicationInsights-dotnet with .gitdir /home/chris/sb2/.git/modules/src/ApplicationInsights-dotnet.git
  dbug: Microsoft.DotNet.Darc.Operations.Operation[0]
        Master .gitdir /home/chris/sb2/.git/modules/src/ApplicationInsights-dotnet.git exists
  dbug: Microsoft.DotNet.Darc.Operations.Operation[0]
        Master .gitdir exists and master folder /home/chris/sb2/artifacts/src/ApplicationInsights-dotnet also exists.  Redirecting master folder.
  dbug: Microsoft.DotNet.Darc.Operations.Operation[0]
        Setting up /home/chris/sb2/artifacts/src/ApplicationInsights-dotnet.53b80940842204f78708a538628288ff5d741a1d with .gitdir redirect
  info: Microsoft.DotNet.Darc.Operations.Operation[0]
        Checking out 53b80940842204f78708a538628288ff5d741a1d in /home/chris/sb2/artifacts/src/ApplicationInsights-dotnet.53b80940842204f78708a538628288ff5d741a1d
  dbug: Microsoft.DotNet.Darc.Operations.Operation[0]
        Checking out 53b80940842204f78708a538628288ff5d741a1d
  dbug: Microsoft.DotNet.Darc.Operations.Operation[0]
        Reading local repo from /home/chris/sb2/artifacts/src/ApplicationInsights-dotnet.53b80940842204f78708a538628288ff5d741a1d
  dbug: Microsoft.DotNet.Darc.Operations.Operation[0]
        Attempting to check out 53b80940842204f78708a538628288ff5d741a1d in /home/chris/sb2/artifacts/src/ApplicationInsights-dotnet.53b80940842204f78708a538628288ff5d741a1d
  dbug: Microsoft.DotNet.Darc.Operations.Operation[0]
        Trying safe checkout of /home/chris/sb2/artifacts/src/ApplicationInsights-dotnet.53b80940842204f78708a538628288ff5d741a1d/ at 53b80940842204f78708a538628288ff5d741a1d
  dbug: Microsoft.DotNet.Darc.Operations.Operation[0]
        Beginning clean of /home/chris/sb2/artifacts/src/ApplicationInsights-dotnet.53b80940842204f78708a538628288ff5d741a1d/ and 0 submodules
  dbug: Microsoft.DotNet.Darc.Operations.Operation[0]
        Deleted 0 untracked files
  dbug: Microsoft.DotNet.Darc.Operations.Operation[0]
        Starting to look for dependencies in /home/chris/sb2/artifacts/src/ApplicationInsights-dotnet.53b80940842204f78708a538628288ff5d741a1d
  info: Microsoft.DotNet.Darc.Operations.Operation[0]
        Getting a collection of dependencies from 'eng/Version.Details.xml' in repo '/home/chris/sb2/artifacts/src/ApplicationInsights-dotnet.53b80940842204f78708a538628288ff5d741a1d'...
  info: Microsoft.DotNet.Darc.Operations.Operation[0]
        Reading 'eng/Version.Details.xml' in repo '/home/chris/sb2/artifacts/src/ApplicationInsights-dotnet.53b80940842204f78708a538628288ff5d741a1d' and branch ''...
  dbug: Microsoft.DotNet.Darc.Operations.Operation[0]
        Deleting .gitdir redirect /home/chris/sb2/artifacts/src/ApplicationInsights-dotnet.53b80940842204f78708a538628288ff5d741a1d/.git
  fail: Microsoft.DotNet.Darc.Operations.Operation[0]
        Something failed while cloning.
  Microsoft.DotNet.DarcLib.DependencyFileNotFoundException: Found parent-directory path ('{parentTwoDirectoriesUp}') but unable to find specified file ('{relativeFilePath}')
     at Microsoft.DotNet.DarcLib.LocalGitClient.GetFileContentsAsync(String relativeFilePath, String repoUri, String branch)
     at Microsoft.DotNet.DarcLib.GitFileManager.ReadXmlFileAsync(String filePath, String repoUri, String branch)
     at Microsoft.DotNet.DarcLib.GitFileManager.ReadVersionDetailsXmlAsync(String repoUri, String branch)
     at Microsoft.DotNet.DarcLib.GitFileManager.ParseVersionDetailsXmlAsync(String repoUri, String branch, Boolean includePinned)
     at Microsoft.DotNet.DarcLib.Local.GetDependenciesAsync(String name, Boolean includePinned)
     at Microsoft.DotNet.Darc.Operations.CloneOperation.ExecuteAsync()
```

It looks like missing the `eng` directory is confusing it, and also the error message is trying to use an interpolated string but missing the `$`.

**Comment by ChadNedzlek** [comment]
Isn't having an "eng" directory part of using darc?

**Comment by alexperovich** [comment]
darc is useless without an eng directory. We use the eng/Version.Details.xml to drive everything darc does. What are you trying to do?

**Comment by riarenas** [comment]
From what I understand, darc clone is a command that, given a build, will clone all repos involved in dependencies at the specific SHA. App insights doesn't publish to dependency flow from what I can tell, and I think it's just a leaf so we don't really need to see if they have dependencies. 

Can we even ask App insights to onboard onto dependency flow? Or maybe we should change the remote class again so that it doesn't automatically assume it's a darc enabled repo and at least tries to do the operations before crashing?

**Comment by ChadNedzlek** [comment]
I'm not sure what the actual ask is here. And no one seems to be commenting on it... can this be closed?
