### ISSUE TITLE
[Maestro++/Darc] Maestro staging swagger broken

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#8064]
- [X] This issue is blocking 
This blocks production deployments

- [ ] This issue is causing unreasonable pain

Going to https://maestro-int.westus2.cloudapp.azure.com/swagger/ui/index.html shows:

![image](https://user-images.githubusercontent.com/23242101/137947424-738edb85-9180-4b09-831c-eacc0a0691db.png)

and has a link to https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fmaestro-int.westus2.cloudapp.azure.com%2Fapi%2F2020-02-20%2Fswagger.json

which shows:

```json
{
     "schemaValidationMessages": [
     {
        "level": "error",
        "message": "Can't read from file https://maestro-int.westus2.cloudapp.azure.com/api/2020-02-20/swagger.json"
    }]
}
```

This is likely related to the deletion of one of the 2020-02-20 controllers here: https://github.com/dotnet/arcade-services/pull/1745.

I attempted to run the https://github.com/dotnet/arcade-services/blob/722d732c4c202f7f92ed96355c7d5c59b719fbf3/src/Maestro/maestro-angular/src/maestro-client/generate-client.cmd script while pointing to the int website, and received an error:

```
HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error). 
    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() 
    at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) 
    at Microsoft.DotNet.SwaggerGenerator.MSBuild.GenerateSwaggerCode.GetSwaggerDocument(String input) in /_/src/Microsoft.DotNet.SwaggerGenerator/Microsoft.DotNet.SwaggerGenerator.MSBuild/GenerateSwaggerCode.cs:line 97 
    at Microsoft.DotNet.SwaggerGenerator.MSBuild.GenerateSwaggerCode.ExecuteAsync() in /_/src/Microsoft.DotNet.SwaggerGenerator/Microsoft.DotNet.SwaggerGenerator.MSBuild/GenerateSwaggerCode.cs:line 57
    at Microsoft.DotNet.SwaggerGenerator.MSBuild.GenerateSwaggerCode.Execute() in /_/src/Microsoft.DotNet.SwaggerGenerator/Microsoft.DotNet.SwaggerGenerator.MSBuild/GenerateSwaggerCode.cs:line 37
```

which seems related to the fact that we're already getting the swagger errors.

**Comment by riarenas** [comment]
Adding this to FR as it's a rollout blocker.
