### ISSUE TITLE
Make blob retry policy user-settable

### ISSUE THREAD

**Issue by dougbu** [dotnet/arcade#8415]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

We have a way users can submit Helix work items from their desktop in the dotnet/aspnetcore repo -- https://github.com/dotnet/aspnetcore/blob/main/eng/scripts/RunHelix.ps1. This script generally works but falls over w/ a long stack trace when the network isn't up to publishing all correlation and work item content. Would be great if it didn't take ages to get to the failure i.e. I'd like the scenario to fail faster, expecially because retries don't seem to help.

Ideal would be a way to control the retries (11 is a lot) from `msbuild`. Failing that, make the error message in this case more helpful. Which payload failed to upload❔

<details>
<summary>Stack trace</summary>

...\.nuget\packages\microsoft.dotnet.helix.sdk\7.0.0-beta.22071.6\tools\Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(46,5): AggregateException: Retry failed after 11 tries. Retry settings can be adjusted in ClientOptions.Retry. (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Storage.Blobs.BlockBlobRestClient.UploadAsync(Int64 contentLength, Stream body, Nullable`1 timeout, Byte[] transactionalContentMD5, String blobContentType, String blobContentEncoding, String blobContentLanguage, Byte[] blobContentMD5, String blobCacheControl, IDictionary`2 metadata, String leaseId, String blobContentDisposition, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, String encryptionScope, Nullable`1 tier, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, String ifMatch, String ifNoneMatch, String ifTags, String blobTagsString, Nullable`1 immutabilityPolicyExpiry, Nullable`1 immutabilityPolicyMode, Nullable`1 legalHold, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.UploadInternal(Stream content, BlobHttpHeaders blobHttpHeaders, IDictionary`2 metadata, IDictionary`2 tags, BlobRequestConditions conditions, Nullable`1 accessTier, BlobImmutabilityPolicy immutabilityPolicy, Nullable`1 legalHold, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.<>c__DisplayClass62_0.<<GetPartitionedUploaderBehaviors>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Storage.PartitionedUploader`2.UploadInternal(Stream content, TServiceSpecificArgs args, IProgress`1 progressHandler, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobClient.StagedUploadInternal(Stream content, BlobUploadOptions options, Boolean async, CancellationToken cancellationToken)
   at Microsoft.DotNet.Helix.Client.ContainerBase.UploadFileAsync(Stream stream, String blobName, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/JobSender/StorageHelpers/ContainerBase.cs:line 21
   at Microsoft.DotNet.Helix.Client.DirectoryPayload.DoUploadAsync(IBlobContainer payloadContainer, Action`1 log, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/JobSender/Payloads/DirectoryPayload.cs:line 71
   at Microsoft.Arcade.Common.Helpers.<>c__DisplayClass6_0`1.<DirectoryMutexExec>b__0() in /_/src/Common/Microsoft.Arcade.Common/Helpers.cs:line 67
   at Microsoft.Arcade.Common.Helpers.MutexExec[T](Func`1 function, String mutexName) in /_/src/Common/Microsoft.Arcade.Common/Helpers.cs:line 45
   at Microsoft.Arcade.Common.Helpers.DirectoryMutexExec[T](Func`1 function, String path) in /_/src/Common/Microsoft.Arcade.Common/Helpers.cs:line 64
   at Microsoft.Arcade.Common.Helpers.DirectoryMutexExec[T](Func`1 function, String path) in /_/src/Common/Microsoft.Arcade.Common/Helpers.cs:line 67
   at Microsoft.DotNet.Helix.Client.DirectoryPayload.UploadAsync(IBlobContainer payloadContainer, Action`1 log, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/JobSender/Payloads/DirectoryPayload.cs:line 33
   at Microsoft.DotNet.Helix.Client.WorkItemDefinition.SendAsync(IBlobContainer payloadStorage, String containerName, Action`1 log, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/JobSender/WorkItemDefinition.cs:line 116
   at Microsoft.DotNet.Helix.Client.JobDefinition.<>c__DisplayClass74_0.<<SendAsync>b__3>d.MoveNext() in /_/src/Microsoft.DotNet.Helix/JobSender/JobDefinition.cs:line 179
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Helix.Client.JobDefinition.SendAsync(Action`1 log, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/JobSender/JobDefinition.cs:line 176
   at Microsoft.DotNet.Helix.Sdk.SendHelixJob.ExecuteCore(CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Sdk/SendHelixJob.cs:line 267
   at Microsoft.DotNet.Helix.Sdk.HelixTask.Execute() in /_/src/Microsoft.DotNet.Helix/Sdk/HelixTask.cs:line 58
TaskCanceledException: The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.
   at Azure.Core.Pipeline.ResponseBodyPolicy.ThrowIfCancellationRequestedOrTimeout(CancellationToken originalToken, CancellationToken timeoutToken, Exception inner, TimeSpan timeout)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.<ProcessAsync>g__ProcessAsyncInner|4_0(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
TaskCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
SocketException: The I/O operation has been aborted because of either a thread exit or an application request.

 [...\aspnetcore\eng\helix\helix.proj]
</details>

### Side note

Root cause of the problem is submission was attempting to upload all *.nupkg files in case the tests needed them. That's fine on the CI but the tests I was running didn't need the baggage.

**Comment by dougbu** [comment]
See also https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Helix/JobSender/StorageHelpers/StorageRetryPolicy.cs and note use of that class in all or most cases where `BlobClientOptions` is needed. Nothing seems to intervene and change the settings later.

I'm also unsure the `MaxDelay` value is honoured because that would mean uploading (say) a Helix work item payload should take at most 5 minutes. My terminal window has been locked up for far longer than that.

**Comment by Chrisboh** [comment]
Moving this back to Triage as we dont believe it belongs in Helix Client Testability and Stability as this needs to change in the sdk

**Comment by garath** [comment]
@dougbu Do you want the configurability, or do you just want it to be less than 11 (which I agree seems like a lot). What if we just set the retry limit to, say, 3?

**Comment by dougbu** [comment]
> @dougbu Do you want the configurability, or do you just want it to be less than 11 (which I agree seems like a lot). What if we just set the retry limit to, say, 3?

@garath a lower retry limit would be fine, I think. I'm not sure of the root cause for the incredibly long hangs before my local Helix jobs fail and anything that either fails fast or allows our large correlation payloads to upload works for me.

**Comment by riarenas** [comment]
Moving back to triage. Do we want to make investments in the helix local job sending story?
