### ISSUE TITLE
Signing of dylib binary failed

### ISSUE THREAD

**Issue by tmat** [dotnet/arcade#858]
```
E:\A\_work\55\a\MicroBuild\Plugins\MicroBuild.Plugins.Signing.1.1.4\build\MicroBuild.Plugins.Signing.targets(30,5): Could not find the specified Authenticode cert Apple [E:\A\_work\55\s\artifacts\tmp\Release\Signing\Round0.proj]

E:\A\_work\55\a\MicroBuild\Plugins\MicroBuild.Plugins.Signing.1.1.4\build\MicroBuild.Plugins.Signing.targets(30,5): error MSB4018: The "SignFiles" task failed unexpectedly.
System.ArgumentException: certifcates must contain at lease one cerficate
   at Microsoft.VisualStudio.Tools.Build.SignRecord..ctor(String fileSpec, String signedFileSpec, String[] certificates)
   at MicroBuild.Signing.SignFiles.ValidateAndParseInputs() in E:\MicroBuild\src\Plugins\Signing\SignFiles.cs:line 184
   at MicroBuild.Signing.SignFiles.Execute() in E:\MicroBuild\src\Plugins\Signing\SignFiles.cs:line 71
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [E:\A\_work\55\s\artifacts\tmp\Release\Signing\Round0.proj]

```

**Comment by jcagme** [comment]
FYI @JohnTortugo

**Comment by JohnTortugo** [comment]
@tmat is this a blocking issue for you?

I did some [reading](https://microsoft.sharepoint.com/:o:/r/teams/DD_CoEng/_layouts/15/WopiFrame.aspx?sourcedoc=%7B67a1015a-0742-49d3-8556-de2a101d97d8%7D&action=edit&wd=target%28MicroBuild%2Eone%7CA0381102-446A-4329-B353-B97A11F92C8B%2FSigning%20Cert%20Guidance%7C7613DFA3-88E2-433C-AE0D-EA27A8605D5C%2F%29) (+ asking around) and it seems the process to sign those .dylib files is different from what we do for the other files (i.e., dll, exe, etc) and if that's the case it seems we might need to discuss the better way to approach this.

**Comment by tmat** [comment]
Not blocking. If it's different we should remove `dylib` from the extensions mapping.

**Comment by tmat** [comment]
We don't need to sign dylib, but the tool is attempting to do so if it finds such file in a package.
