### ISSUE TITLE
Stage-dotnet unable to create containers for -quality signed bits

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#8685]
- [x] This issue is blocking 
- [x] This issue is causing unreasonable pain

Error is 

```
Error creating containers System.String[],System.String[] in storage account dotnetstage
Microsoft.WindowsAzure.Storage.StorageException: The specified resource does not exist.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.CreateIfNotExistsAsync(BlobContainerPublicAccessType accessType, BlobRequestOptions options, OperationContext operationContext, CancellationToken cancellationToken)
   at Microsoft.DotNet.ReleaseLib.Helpers.CloudStorageHelper.GetOrCreateCloudBlobContainer(String accountName, String accountSas, String containerName, Boolean createTempContainer, Boolean randomizeContainerName, Boolean hasPublicAccess) in D:\a\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.ReleaseLib\Helpers\CloudStorageHelper.cs:line 25
   at Microsoft.DotNet.ReleaseCli.Operations.CreateStorageContainersOperation.ExecuteAsync() in D:\a\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.ReleaseCli\src\Operations\CreateStorageContainersOperation.cs:line 36
```

This blocks users of the dotnet-install scripts from using the -Quality signed option, and causes confusion in the release process for the release team.

See https://dev.azure.com/dnceng/internal/_build/results?buildId=1676812&view=logs&j=06e47235-ea4e-5696-bf7a-60141ec0f646&t=07a9ec1f-b7cf-539f-05be-963e95159b69

**Comment by adiaaida** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/22021
