### ISSUE TITLE
Current sdk version (7.0*preview2) breaks `dotnet/runtime` tests, blocking the arcade update

### ISSUE THREAD

**Issue by radical** [dotnet/arcade#9011]
- [ ] This issue is blocking 

The [update PR](https://github.com/dotnet/runtime/pull/67771) for `arcade` in `runtime` [breaks](https://github.com/dotnet/runtime/pull/67771#issuecomment-1093513385):
```
   System.Net.Security.Tests.SslStreamTls11NetworkConformanceTests.ZeroByteWrite_OtherDataReceivedSuccessfully(mode: SyncArray) [FAIL]
      System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
      ---- System.ComponentModel.Win32Exception : The client and server cannot communicate, because they do not possess a common algorithm.
      Stack Trace:
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs(160,0): at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs(723,0): at System.Net.Security.SecureChannel.AcquireCredentialsHandle(SslAuthenticationOptions sslAuthenticationOptions)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs(610,0): at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs(834,0): at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs(777,0): at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(322,0): at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(120,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(90,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamConformanceTests.cs(28,0): at System.Net.Security.Tests.SslStreamConformanceTests.CreateWrappedConnectedStreamsAsync(StreamPair wrapped, Boolean leaveOpen)
        /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs(2233,0): at System.IO.Tests.ConnectedStreamConformanceTests.ZeroByteWrite_OtherDataReceivedSuccessfully(ReadWriteMode mode)
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
        /_/src/libraries/Common/src/Interop/Windows/SspiCli/SSPIWrapper.cs(138,0): at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCH_CREDENTIALS* scc)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs(605,0): at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCH_CREDENTIALS* secureCredential)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs(305,0): at System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchCredentials(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs(147,0): at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
```

This was fixed in https://github.com/dotnet/runtime/pull/65886 , but the p2 sdk doesn't contain the fix. It was breaking for `aspnetcore` also, but IIUC, they [updated](https://github.com/dotnet/aspnetcore/pull/40507/commits/e812f1708fae2f960fa23fbae7b5eb027f9838d8) to `7.0.100-preview.3.22159.27` which contains the fix.

This is blocking the `arcade` update, and bump to net7 .

Also, maybe an explicit test is needed for this case of zipping/unzipping unicode file paths.

cc @lewing

**Comment by riarenas** [comment]
It is expected that new versions of the SDK will include changes that break builds and tests. Arcade and dependency flow only control the minimum version of the SDK that a repo will use. Repos are encouraged to use newer SDKs if they help solve any issues with the publicly available released previews. 

I'm going to close this issue as there doesn't seem to be anything for Arcade to do here.
