### ISSUE TITLE
Validation scheduling pipeline is failing with HttpRequestException Bad Request

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#9375]
- [x] This issue is blocking 
- [x] This issue is causing unreasonable pain

We are seeing the following error when trying to create the auto-generated Validation Pipeline runs:

```
##[error](NETCORE_ENGINEERING_TELEMETRY=ReleaseStaging-Infra) There was an error trying to schedule a validation run for repo 'https://github.com/dotnet/sdk' and channel .NET 7.0.1xx SDK. Exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.DotNet.ReleaseCli.Operations.ScheduleValidationPipelineOperation.ExecuteAsync() in D:\a\_work\1\s\src\Microsoft.DotNet.Release\Microsoft.DotNet.ReleaseCli\src\Operations\ScheduleValidationPipelineOperation.cs:line 122
```

https://dev.azure.com/dnceng/internal/_build/results?buildId=1772548&view=logs&j=559e8c61-8d51-558d-7b08-43d2f6c6578c&t=67a4272e-b412-5521-fd1f-95beadaad539&l=4806

This blocks post-build validation, including all SDL testing on the product repos. This has been happening since April 16, 2022.

**Comment by adiaaida** [comment]
The issue was that the validation pipeline had been disabled, probably back when we had an influx of validation runs we had to cancel because they had gotten blocked by an approval on a variable group or something. Renabled the pipeline, going to confirm the validation pipeline is ok, then will close this

**Comment by adiaaida** [comment]
That all seemed to be ok, but the warnings about the docker files is causing issues.
