### ISSUE TITLE
Dependency registration tests are failing in arcade-services / helix-service

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#9395]
- [X] This issue is blocking 

This has all PRs / CI and official builds for Arcade-services and helix-service failing.
- [ ] This issue is causing unreasonable pain

Yesterday at ~1PM PT, we started seeing failures in the dependency injection tests in arcade-services with the following error:

```
System.ArgumentNullException : Value cannot be null. (Parameter 'vaultBaseUrl')
```

and stacks similar to this one:

```
at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetKeyAsync(IKeyVaultClient operations, String vaultBaseUrl, String keyName, CancellationToken cancellationToken)
   at Maestro.Web.Startup.ConfigureServices(IServiceCollection services) in /_/src/Maestro/Maestro.Web/Startup.cs:line 153
   at Microsoft.DotNet.Internal.DependencyInjection.Testing.DependencyInjectionValidation.IsDependencyResolutionCoherent(Action`1 register, String& errorMessage, IEnumerable`1 additionalScopedTypes, IEnumerable`1 additionalSingletonTypes) in /_/src/Shared/Microsoft.DotNet.Internal.DependencyInjection.Testing/DependencyInjectionValidation.cs:line 43
   at Maestro.Web.Tests.DependencyRegistrationTests.AreDependenciesRegistered() in /_/src/Maestro/Maestro.Web.Tests/DependencyRegistrationTests.cs:line 38
```

This points to a failure in detecting the development environment that should skip attempting to reach a real key vault here when configuring services.

The environment is set by the tests in this pattern: https://github.com/dotnet/arcade-services/blob/main/src/Maestro/Maestro.Web.Tests/DependencyRegistrationTests.cs#L22

which should then short circuit the services configuration in the startup, such as in:

https://github.com/dotnet/arcade-services/blob/86fab8594c8be4687f2bd700fb6079bcfdf575c9/src/Maestro/Maestro.Web/Startup.cs#L140

This started happening without any code or machine changes. and the failures do not repro locally with Visual Studio or calling `dotnet test` directly. It only happens in the build machines.

**Comment by riarenas** [comment]
Some examples:

Arcade-services:
https://dev.azure.com/dnceng/public/_build/results?buildId=1775899&view=results

helix-service:
https://dev.azure.com/dnceng/internal/_build/results?buildId=1776814&view=results

**Comment by garath** [comment]
PR for helix-service: [23036](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/23036)
