### ISSUE TITLE
Find a way to handle spa-templates-localization with maestro

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#9851]
The spa-templates-localization pipeline/repo has a pretty non-traditional layout and requirements.  We should consider what would be necessary to help support that scenario, or if this is outside our scope right now.

**Comment by dougbu** [comment]
[dotnet/spa-templates](https://github.com/dotnet/spa-templates) doesn't do regular builds except as a submodule of [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore). Our only pipeline (once `spa-templates-localization` exists) needs eng/common/templates/ files and I'd like to keep those files up to date. It's the submodule use that's breaking things here.

The two main requirements that get in the way of using Maestro++ to update eng/common/ files are:
- We can't set the .NET SDK version in global.json without breaking [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore) builds.
- We can't add a NuGet.config file because that _must_ include a `<clear/>` and doing so would also break [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore) builds.

**Comment by dougbu** [comment]
A few attempts at `update-dependencies` in the branch adding eng/common/ files:
1. With a mostly empty Version.Details.xml file:
  ``` text
  > darc update-dependencies --channel '.NET Eng - Latest' --source-repo arcade
  Found no dependencies to update.
  ```
2. With a toolset dependency for the Arcade SDK:
  ``` text
  > darc update-dependencies --channel '.NET Eng - Latest' --source-repo arcade
  Looking up latest build of https://github.com/dotnet/arcade on .NET Eng - Latest
  Updating 'Microsoft.DotNet.Arcade.Sdk': '7.0.0-beta.22327.1' => '7.0.0-beta.22327.2' (from build '20220627.2' of 'https://github.com/dotnet/arcade')
  Checking for coherency updates...
  Using 'Strict' coherency mode. If this fails, a second attempt utilizing 'Legacy' Coherency mode will be made.
  fail: Microsoft.DotNet.Darc.Operations.Operation[0]
        Error: Failed to update dependencies.
  Microsoft.DotNet.DarcLib.DependencyFileNotFoundException: Could not find C:/dd/dnx/spa-templates\global.json
     at Microsoft.DotNet.DarcLib.LocalGitClient.GetFileContentsAsync(String relativeFilePath, String repoUri, String branch) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs:line 82
     at Microsoft.DotNet.DarcLib.GitFileManager.ReadGlobalJsonAsync(String repoUri, String branch) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs:line 68
     at Microsoft.DotNet.DarcLib.GitFileManager.UpdateDependencyFiles(IEnumerable`1 itemsToUpdate, String repoUri, String branch, IEnumerable`1 oldDependencies, SemanticVersion incomingDotNetSdkVersion) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs:line 206
     at Microsoft.DotNet.DarcLib.Local.UpdateDependenciesAsync(List`1 dependencies, IRemoteFactory remoteFactory) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs:line 79
     at Microsoft.DotNet.Darc.Operations.UpdateDependenciesOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateDependenciesOperation.cs:line 238
  ```
3. With only a `"msbuild-sdks"` property in global.json for the Arcade SDK:
  ``` text
  > darc update-dependencies --channel '.NET Eng - Latest' --source-repo arcade
  Looking up latest build of https://github.com/dotnet/arcade on .NET Eng - Latest
  Updating 'Microsoft.DotNet.Arcade.Sdk': '7.0.0-beta.22327.1' => '7.0.0-beta.22327.2' (from build '20220627.2' of 'https://github.com/dotnet/arcade')
  Checking for coherency updates...
  Using 'Strict' coherency mode. If this fails, a second attempt utilizing 'Legacy' Coherency mode will be made.
  fail: Microsoft.DotNet.Darc.Operations.Operation[0]
        Error: Failed to update dependencies.
  Microsoft.DotNet.DarcLib.DependencyFileNotFoundException: Could not find C:/dd/dnx/spa-templates\NuGet.config
     at Microsoft.DotNet.DarcLib.LocalGitClient.GetFileContentsAsync(String relativeFilePath, String repoUri, String branch) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs:line 82
     at Microsoft.DotNet.DarcLib.GitFileManager.ReadXmlFileAsync(String filePath, String repoUri, String branch) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs:line 868
     at Microsoft.DotNet.DarcLib.GitFileManager.ReadNugetConfigAsync(String repoUri, String branch) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs:line 97
     at Microsoft.DotNet.DarcLib.GitFileManager.UpdateDependencyFiles(IEnumerable`1 itemsToUpdate, String repoUri, String branch, IEnumerable`1 oldDependencies, SemanticVersion incomingDotNetSdkVersion) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs:line 208
     at Microsoft.DotNet.DarcLib.Local.UpdateDependenciesAsync(List`1 dependencies, IRemoteFactory remoteFactory) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs:line 79
     at Microsoft.DotNet.Darc.Operations.UpdateDependenciesOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateDependenciesOperation.cs:line 238
  ```
4. With a **temporary** (should never be checked in) NuGet.config file copied from somewhere else:
  ``` text
  > darc update-dependencies --channel '.NET Eng - Latest' --source-repo arcade
  Looking up latest build of https://github.com/dotnet/arcade on .NET Eng - Latest
  Updating 'Microsoft.DotNet.Arcade.Sdk': '7.0.0-beta.22327.1' => '7.0.0-beta.22327.2' (from build '20220627.2' of 'https://github.com/dotnet/arcade')
  Checking for coherency updates...
  Using 'Strict' coherency mode. If this fails, a second attempt utilizing 'Legacy' Coherency mode will be made.
  fail: Microsoft.DotNet.Darc.Operations.Operation[0]
        Failed to update Dotnet version for global.json. Skipping update to version sections.
  System.NullReferenceException: Object reference not set to an instance of an object.
     at Microsoft.DotNet.DarcLib.GitFileManager.UpdateDotnetVersionGlobalJson(SemanticVersion incomingDotnetVersion, JObject globalJson) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs:line 307
  Local dependencies updated from channel '.NET Eng - Latest'.
  ```

**Comment by dougbu** [comment]
As-is, this issue blocks localization of [dotnet/spa-templates](https://github.com/dotnet/spa-templates). One option might be changing https://github.com/dotnet/arcade-services/blob/722d732c4c202f7f92ed96355c7d5c59b719fbf3/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs#L82 to special case a new entry like
``` xml
    <Dependency Name="/eng/common/" Version="7.0.0-beta.22327.1">
      <Uri>https://github.com/dotnet/arcade</Uri>
      <Sha>640c1cc2a140b322c4f30f6d6b85f35f0c4c7313</Sha>
    </Dependency>
```
plus confirm the Maestro++ service can work w/o a NuGet.config file in the repo.

**Comment by dougbu** [comment]
Realized this isn't actually blocking anything: We could, if necessary, use a GitHub action to synchronize files we need e.g. from [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore) to [dotnet/spa-templates](https://github.com/dotnet/spa-templates). I'm not sure that's better or worse than a small change (if one is possible) in [dotnet/arcade-services](https://github.com/dotnet/arcade-services)

**Comment by dougbu** [comment]
Haven't hit any reason why a GitHub action similar to what we have in dotnet/aspnetcore won't work for this case. In fact, an action is starting to feel like the **right** way to synchronize the eng/common/ files in the (rare❔) case that a repo isn't involved in dependency flow.

Feel free to reopen this issue and use it for the case where a repo _is_ interested in dependency flow but doesn't check in both global.json and NuGet.config files e.g. @rolfbjarne's [FR thread](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1656601843804?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1656601843804&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1656601843804) w/ @riarenas and others
