### ISSUE TITLE
PublishToAzureDevOpsArtifacts cannot preserve folders for non-nupkg files

### ISSUE THREAD

**Issue by directhex** [dotnet/arcade#9876]
- [x] This issue is blocking
- [X] This issue is causing unreasonable pain

There are cases where we need to upload multiple artifacts with the same filename - for example, whilst we are on SDK band 6.0.300, we may also need to build files for band 6.0.200 and 6.0.100. We produce multiple versions via `CreateVisualStudioWorkload`, but in Runtime we're using `PublishToAzureDevOpsArtifacts` to do the uploads, and it dies.

Analysis of the issue is in https://github.com/dotnet/runtime/issues/71150 (especially the later comments), and I have a test repro at https://github.com/directhex/arcade-repro / https://dev.azure.com/joshield/testing/_build?definitionId=1&_a=summary

Problems look something like:

```
2022-07-05T18:55:10.5318885Z Total file: 1 ---- Processed file: 0 (0%)
2022-07-05T18:55:20.5387974Z Total file: 1 ---- Processed file: 0 (0%)
2022-07-05T18:55:30.5486060Z Total file: 1 ---- Processed file: 0 (0%)
2022-07-05T18:55:40.5499786Z Total file: 1 ---- Processed file: 0 (0%)
2022-07-05T18:55:50.5538748Z Total file: 1 ---- Processed file: 0 (0%)
2022-07-05T18:56:00.5586925Z Total file: 1 ---- Processed file: 0 (0%)
2022-07-05T18:56:03.5620064Z Fail to upload '/home/vsts/work/1/s/assets/2/Microsoft.Mono.tvossimulator-x64.6.0.7.msi' due to 'Bad Request'.
2022-07-05T18:56:03.5623003Z Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Bad Request
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Byte[] contentId, Int64 fileLength, Boolean isGzipped, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Int32 chunkRetryTimes, Boolean uploadFirstChunk, Object userState)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Boolean uploadFirstChunk, Object userState, Boolean compressStream)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.FileContainerServer.UploadAsync(IAsyncCommandContext context, Int32 uploaderId, CancellationToken token)
2022-07-05T18:56:03.5625972Z Detail upload trace for file that fail to upload: BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi
2022-07-05T18:56:03.5626595Z Begin chunking upload file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', chunk size '4194304 Bytes', total chunks '15'.
2022-07-05T18:56:03.5627178Z Attempt '1' for uploading chunk '1' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi'.
2022-07-05T18:56:03.5627753Z Generate new HttpRequest for uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', chunk '1' of '15'.
2022-07-05T18:56:03.5628343Z Start uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi' to server, chunk '1'.
2022-07-05T18:56:03.5628925Z Finished upload chunk '1' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', elapsed 555 (ms), response code 'Accepted'.
2022-07-05T18:56:03.5630048Z Attempt '1' for uploading chunk '2' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi'.
2022-07-05T18:56:03.5630636Z Generate new HttpRequest for uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', chunk '2' of '15'.
2022-07-05T18:56:03.5631191Z Start uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi' to server, chunk '2'.
2022-07-05T18:56:03.5631776Z Finished upload chunk '2' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', elapsed 530 (ms), response code 'Accepted'.
2022-07-05T18:56:03.5632519Z Attempt '1' for uploading chunk '3' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi'.
2022-07-05T18:56:03.5633094Z Generate new HttpRequest for uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', chunk '3' of '15'.
2022-07-05T18:56:03.5633642Z Start uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi' to server, chunk '3'.
2022-07-05T18:56:03.5634242Z Finished upload chunk '3' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', elapsed 438 (ms), response code 'Accepted'.
2022-07-05T18:56:03.5634849Z Attempt '1' for uploading chunk '4' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi'.
2022-07-05T18:56:03.5635404Z Generate new HttpRequest for uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', chunk '4' of '15'.
2022-07-05T18:56:03.5635969Z Start uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi' to server, chunk '4'.
2022-07-05T18:56:03.5636579Z Finished upload chunk '4' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', elapsed 469 (ms), response code 'Accepted'.
2022-07-05T18:56:03.5637160Z Attempt '1' for uploading chunk '5' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi'.
2022-07-05T18:56:03.5637722Z Generate new HttpRequest for uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', chunk '5' of '15'.
2022-07-05T18:56:03.5638287Z Start uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi' to server, chunk '5'.
2022-07-05T18:56:03.5638878Z Finished upload chunk '5' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', elapsed 469 (ms), response code 'Accepted'.
2022-07-05T18:56:03.5639455Z Attempt '1' for uploading chunk '6' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi'.
2022-07-05T18:56:03.5640019Z Generate new HttpRequest for uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', chunk '6' of '15'.
2022-07-05T18:56:03.5640593Z Start uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi' to server, chunk '6'.
2022-07-05T18:56:03.5641171Z Finished upload chunk '6' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', elapsed 501 (ms), response code 'Accepted'.
2022-07-05T18:56:03.5641761Z Attempt '1' for uploading chunk '7' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi'.
2022-07-05T18:56:03.5642344Z Generate new HttpRequest for uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', chunk '7' of '15'.
2022-07-05T18:56:03.5642893Z Start uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi' to server, chunk '7'.
2022-07-05T18:56:03.5643474Z Finished upload chunk '7' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', elapsed 270 (ms), response code 'Accepted'.
2022-07-05T18:56:03.5644064Z Attempt '1' for uploading chunk '8' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi'.
2022-07-05T18:56:03.5644832Z Generate new HttpRequest for uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', chunk '8' of '15'.
2022-07-05T18:56:03.5645652Z Start uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi' to server, chunk '8'.
2022-07-05T18:56:03.5646250Z Finished upload chunk '8' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', elapsed 366 (ms), response code 'Accepted'.
2022-07-05T18:56:03.5646981Z Attempt '1' for uploading chunk '9' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi'.
2022-07-05T18:56:03.5647539Z Generate new HttpRequest for uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', chunk '9' of '15'.
2022-07-05T18:56:03.5648110Z Start uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi' to server, chunk '9'.
2022-07-05T18:56:03.5648709Z Finished upload chunk '9' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', elapsed 310 (ms), response code 'Accepted'.
2022-07-05T18:56:03.5649365Z Attempt '1' for uploading chunk '10' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi'.
2022-07-05T18:56:03.5649935Z Generate new HttpRequest for uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', chunk '10' of '15'.
2022-07-05T18:56:03.5650519Z Start uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi' to server, chunk '10'.
2022-07-05T18:56:03.5651107Z Finished upload chunk '10' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', elapsed 325 (ms), response code 'Accepted'.
2022-07-05T18:56:03.5651702Z Attempt '1' for uploading chunk '11' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi'.
2022-07-05T18:56:03.5652291Z Generate new HttpRequest for uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', chunk '11' of '15'.
2022-07-05T18:56:03.5652844Z Start uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi' to server, chunk '11'.
2022-07-05T18:56:03.5653434Z Finished upload chunk '11' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', elapsed 315 (ms), response code 'Accepted'.
2022-07-05T18:56:03.5654033Z Attempt '1' for uploading chunk '12' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi'.
2022-07-05T18:56:03.5654604Z Generate new HttpRequest for uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', chunk '12' of '15'.
2022-07-05T18:56:03.5655162Z Start uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi' to server, chunk '12'.
2022-07-05T18:56:03.5655756Z Finished upload chunk '12' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', elapsed 290 (ms), response code 'Accepted'.
2022-07-05T18:56:03.5656362Z Attempt '1' for uploading chunk '13' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi'.
2022-07-05T18:56:03.5656917Z Generate new HttpRequest for uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', chunk '13' of '15'.
2022-07-05T18:56:03.5657481Z Start uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi' to server, chunk '13'.
2022-07-05T18:56:03.5658089Z Finished upload chunk '13' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', elapsed 322 (ms), response code 'Accepted'.
2022-07-05T18:56:03.5658671Z Attempt '1' for uploading chunk '14' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi'.
2022-07-05T18:56:03.5659239Z Generate new HttpRequest for uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', chunk '14' of '15'.
2022-07-05T18:56:03.5659798Z Start uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi' to server, chunk '14'.
2022-07-05T18:56:03.5660393Z Finished upload chunk '14' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', elapsed 318 (ms), response code 'Accepted'.
2022-07-05T18:56:03.5660978Z Attempt '1' for uploading chunk '15' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi'.
2022-07-05T18:56:03.5661548Z Generate new HttpRequest for uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', chunk '15' of '15'.
2022-07-05T18:56:03.5662121Z Start uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi' to server, chunk '15'.
2022-07-05T18:56:03.5664846Z Chunk '15' attempt '1' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi' fail to send request to server. Error: Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Blob is incomplete (missing block). Blob: 7252fff493fcec11b47ae42aac79d400, Expected Offset: 0, Actual Offset: 54525952
 ---> System.InvalidOperationException: Blob is incomplete (missing block). Blob: 7252fff493fcec11b47ae42aac79d400, Expected Offset: 0, Actual Offset: 54525952
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Byte[] contentId, Int64 fileLength, Boolean isGzipped, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Int32 chunkRetryTimes, Boolean uploadFirstChunk, Object userState).
2022-07-05T18:56:03.5668149Z Backoff 5.448 seconds before attempt '2' chunk '15' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi'.
2022-07-05T18:56:03.5669086Z Attempt '2' for uploading chunk '15' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi'.
2022-07-05T18:56:03.5669718Z Generate new HttpRequest for uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', chunk '15' of '15'.
2022-07-05T18:56:03.5670286Z Start uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi' to server, chunk '15'.
2022-07-05T18:56:03.5672444Z Chunk '15' attempt '2' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi' fail to send request to server. Error: Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Bad Request
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Byte[] contentId, Int64 fileLength, Boolean isGzipped, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Int32 chunkRetryTimes, Boolean uploadFirstChunk, Object userState).
2022-07-05T18:56:03.5674651Z Backoff 8.413 seconds before attempt '3' chunk '15' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi'.
2022-07-05T18:56:03.5675236Z Attempt '3' for uploading chunk '15' of file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi'.
2022-07-05T18:56:03.5675799Z Generate new HttpRequest for uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi', chunk '15' of '15'.
2022-07-05T18:56:03.5676375Z Start uploading file 'BlobArtifacts/Microsoft.Mono.tvossimulator-x64.6.0.7.msi' to server, chunk '15'.
2022-07-05T18:56:03.5676828Z 1 files failed to upload, retry these files after a minute.
```

**Comment by tkapin** [comment]
Triage - this needs some attention. Do we see that fitting an existing epic so it can get traction? Based on request from @steveisok:
 > This relates to our ability (or right now inability) to modify runtime's workload build to support similar file names under different SDK bands. I anticipate it being a blocker sooner rather than later.

**Comment by joeloff** [comment]
In case it helps, we have automation in the release pipeline we want use, but can't until we have everything laid out correctly. The new tooling for workloads ensures that all the files for a specific workload is laid out without pulling in items related to other featurebands (and thus VS versions). While the workload manifests can have duplicated packs, we want to create the installer once, then lay it out in N different folders (one for each featureband). The folders are processed as a a whole to generate the VS manifest we used when inserting through VSDROP and some of the manifests may be built by different tools because of differences in VS.

We are already publishing it this way to some degree, but it seems that all the artifacts are duplicated in a flat container as well and that's not able to ignore duplicate items.

**Comment by MattGal** [comment]
Discussed with @mmitche , some context from email thread:

_The artifacts that are handled by publishing, staging, etc. are not the fine grained files. They’re the top level files (SDKs, transport packages, MSIs, etc.), and those are always uniquely named. Signing does have to deal with them, and it has a ton of complex logic to try and differentiate files within a nuget package that may need different certs but look the same. However, even the top level logic around which artifacts should be passed through signing is based around unique file name assumptions._
 
@joeloff has some prior work that makes the duplicate-name checks happy he is going to revive to address the issue at the repository level.
